WIP Scoreboard Mappings
asiekierka/MinecraftPOMF pull request #101
Opened 2016-09-29 11:52 UTC by maxpowa

Definitely some mappings I'm iffy about (ScoreboardServer particularily). I'll probably add some more mappings to this, as coverage on some of these Scoreboard classes is pretty lacking, just wanted to get a commit down so I could get feedback on current state.

Existing mapping changes:
`IScoreboardObjective` -> `IScoreboardCriterion`
`ScoreboardObjective` -> `ScoreboardCriterion`
`ScoreboardObjectiveReadOnly` -> `ScoreboardCriterionReadOnly`
`ScoreboardObjectiveHearts` -> `ScoreboardCriterionHearts`
`MapContainer` -> `MapState`
`net.mc.sortme.ScoreSomething` -> `net.mc.scoreboard.ScoreboardPlayerScore`

2016-09-29 13:34 UTC, copygirl requested changes

2016-09-29 13:34 UTC, copygirl commented on mappings/net/minecraft/nbt/CompoundWrapper.mapping
> +		ARG 0 dirty
Setters should always use `value`.

2016-09-29 13:34 UTC, copygirl commented on mappings/net/minecraft/scoreboard/ScoreboardTeam.mapping
> +		ARG 0 suffix
Again, setters should be `value`.

2016-09-29 13:34 UTC, copygirl commented on mappings/net/minecraft/scoreboard/ScoreboardTeamBase.mapping
> +		FIELD g NAME_TO_RULE_MAP Ljava/util/Map;
Could also be `LOOKUP`, same with `VisibilityRule`.

2016-09-29 13:34 UTC, copygirl commented on mappings/net/minecraft/scoreboard/ScoreboardTeamBase.mapping
> +	METHOD a equals (Lnone/bdd;)Z
I believe @asiekierka once said we shouldn't use `equals` and such.

2016-09-29 17:32 UTC, copygirl approved these changes

2016-09-29 17:33 UTC, copygirl commented on mappings/net/minecraft/scoreboard/IScoreboardCriterion.mapping
> +		FIELD c NAME_LOOKUP Ljava/util/Map;
`TYPE_LOOKUP` if anything, I still suggest `LOOKUP` - would like some input from the other.

2016-10-01 05:59 UTC, asiekierka commented
Will apply feedback myself as we're moving to 16w39c.

2016-10-01 05:59 UTC, merged