Fix up Identifier
asiekierka/MinecraftPOMF pull request #1059
Opened 2020-01-14 11:14 UTC by natanfudge

2020-01-14 15:37 UTC, Pyrofab commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT The namespace and path must only contain either [a-z] (a letter), [0-9] (a digit), or the characters '_', '.', and '-'.
Doesn't the path accept `/` too ?

2020-01-17 02:23 UTC, liach requested changes

2020-01-17 02:23 UTC, liach commented on mappings/net/minecraft/util/Identifier.mapping
> +			COMMENT A string of the form <path>:<namespace>, for example minecraft:iron_ingot.
namespace:path not path:namespace :angry:

2020-01-17 09:28 UTC, Pyrofab commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT The namespace and path must only contain either [a-z] (a letter), [0-9] (a digit), or the characters '_', '.', and '-'. The path can also have a '/'.
```suggestion
	COMMENT The namespace and path must contain only lowercase letters ([a-z]), digits ([0-9]), or the characters '_', '.', and '-'. The path can also contain the standard path separator '/'.
```
I think this is preferable to a less verbose RegEx description for doc.

2020-01-17 10:17 UTC, natanfudge commented on mappings/net/minecraft/util/Identifier.mapping
> +			COMMENT A string of the form <path>:<namespace>, for example minecraft:iron_ingot.
```suggestion
			COMMENT A string of the form <namespace>:<path>, for example minecraft:iron_ingot.
```

2020-01-17 10:36 UTC, liach approved these changes

2020-01-17 14:09 UTC, Juuxel approved these changes

2020-01-17 16:38 UTC, Pyrofab approved these changes

2020-01-17 19:48 UTC, merged