Map some World fields / methods and more
asiekierka/MinecraftPOMF pull request #106
Opened 2016-10-09 16:38 UTC by copygirl

- Mapped `World.globalEntities` (used for lightning strikes)
- Mapped `ServerConfigurationManager.sendToAllPlayersInRange` (should this class be renamed?)
- Mapped `IntHashMap` (previously `DrawableRegistryThingy`
- Mapped / renamed fields using `IntHashMap`
- Mapped `ScheduledBlockTick` and related fields / methods in `World` (**Requesting feedback** :green_heart:)
- Mapped raining and thunder related fields / methods in `World`
- Mapped `Block.areEqual`

2016-10-09 16:39 UTC, liach commented on mappings/net/minecraft/server/ServerConfigurationManager.mapping
> +		ARG 0 except
`sender`?

2016-10-09 16:44 UTC, liach commented on mappings/net/minecraft/util/IntHashMap.mapping
> +	METHOD c getBucketForKey (I)Lnone/om$a;
`getBucket` or `getElement`?

2016-10-09 16:44 UTC, liach commented on mappings/net/minecraft/util/IntHashMap.mapping
> +	METHOD g getHashForKey (I)I
`getHash`

2016-10-09 16:51 UTC, copygirl commented on mappings/net/minecraft/server/ServerConfigurationManager.mapping
> +		ARG 0 except
It makes more sense to me since that's what it does. If `except` is non-null, it will not send it to that player.

2016-10-09 21:43 UTC, exaskye approved these changes

2016-10-09 22:07 UTC, Darkhax approved these changes

2016-10-11 22:19 UTC, asiekierka commented on mappings/net/minecraft/world/WorldServer.mapping
> +	METHOD b hasBlockTickScheduled (Lnone/cn;Lnone/aky;)Z
hasBlockTickScheduled or isBlockTickScheduled or hasScheduledBlockTick?

2016-10-11 22:20 UTC, asiekierka commented on mappings/net/minecraft/world/WorldServer.mapping
> +	METHOD b scheduleBlockTickGuaranteedDelay (Lnone/cn;Lnone/aky;II)V
How is the other one not Guaranteed?

2016-10-11 22:30 UTC, liach commented on mappings/net/minecraft/world/WorldServer.mapping
> +	METHOD b hasBlockTickScheduled (Lnone/cn;Lnone/aky;)Z
`hasScheduledBlockTick`?

2016-10-11 22:38 UTC, liach requested changes

2016-10-11 22:38 UTC, liach commented on mappings/net/minecraft/util/IntHashMap.mapping
> +	METHOD a reorderElements ([Lnone/om$a;)V
`reorder`

2016-10-11 22:38 UTC, liach commented on mappings/net/minecraft/util/IntHashMap.mapping
> +	METHOD a addInternal (IILjava/lang/Object;I)V
Now you can just name it `add`, or rename it to `putInternal`.

2016-10-11 22:38 UTC, liach commented on mappings/net/minecraft/world/ScheduledBlockTick.mapping
> +	FIELD d ID_COUNTER J
This seems dislike a constant field.

2016-10-12 01:35 UTC, copygirl commented on mappings/net/minecraft/world/WorldServer.mapping
> +	METHOD b hasBlockTickScheduled (Lnone/cn;Lnone/aky;)Z
This method takes a BlockPos and Block / IBlockState, so to me it reads best as "does this BlockPos/Block pair have a block tick scheduled?".

2016-10-12 01:37 UTC, copygirl commented on mappings/net/minecraft/world/WorldServer.mapping
> +	METHOD b scheduleBlockTickGuaranteedDelay (Lnone/cn;Lnone/aky;II)V
I wasn't sure about the naming. The other one has the possibility for being executed instantly, which, I think, happens during world generation? (for example for water/lava springs)

2016-10-12 02:43 UTC, darkhax commented on mappings/net/minecraft/world/WorldServer.mapping
> +	METHOD b hasBlockTickScheduled (Lnone/cn;Lnone/aky;)Z
I like the way `hasScheduledBlockTick` sounds. It flows much better.

2016-10-12 11:25 UTC, copygirl commented on mappings/net/minecraft/util/IntHashMap.mapping
> +	METHOD a addInternal (IILjava/lang/Object;I)V
Actually, I named it `addInternal` because it's in charge of adding a **new** element, `put` also replaces existing elements.

2016-10-12 11:31 UTC, merged