Map the 1.15.2 changes
asiekierka/MinecraftPOMF pull request #1063
Opened 2020-01-17 19:47 UTC by modmuss50

Im no expert on rendering, so please check over this.

2020-01-17 20:25 UTC, Juuxel requested changes

2020-01-17 20:25 UTC, Juuxel commented on mappings/net/minecraft/client/render/model/BakedModel.mapping
> +		COMMENT False, the model will be lit from the font, like an item.
Typo here:
```suggestion
		COMMENT False, the model will be lit from the front, like an item.
```

2020-01-17 20:27 UTC, Juuxel approved these changes

2020-01-18 02:15 UTC, grondag commented
This looks right, except `hasDepth` is the opposite of what it should be. Suggest `isFlat` instead.

I think I know what happened here.  Previously, there was only one boolean parameter (for JSON models) that was set based on which models were generated item models.  This parameter did control depth lighting in GUI so the prior name was appropriate.

In 1.15.2, Mojang decided to control depth lighting via a JSON attribute but also kept the flag that indicates a generated item model.  The prior flag now controls geometric transformation for item entity rendering, but was still mapped to `depthInGui`.

The name `depthInGui` would be an adequate name for the *new* field/method, but it's better to change both names so that mods can explicitly determine what to return in each case vs having `depthInGui` now point to an entirely different field/method. 

See attached diagram for analysis.
![image](https://user-images.githubusercontent.com/6106235/72657128-458b9380-3955-11ea-911d-1d4e72d1ab65.png)

2020-01-18 09:24 UTC, modmuss50 commented
Thanks for looking at it, I’ll make the changes later on

2020-01-18 11:44 UTC, grondag approved these changes

2020-01-18 17:25 UTC, merged

2020-01-18 19:42 UTC, liach commented
wanted to take a look but sure, problems can be fixed later

2020-01-18 19:43 UTC, modmuss50 commented
Ah, my mistake. Had 2 reviews, and it was quite important as it clears some things up.