A few 1.16 mappings
asiekierka/MinecraftPOMF pull request #1091
Opened 2020-02-05 21:46 UTC by Shnupbups

Mapped new blocks and stuff

2020-02-05 22:07 UTC, liach commented
@Shnupbups mind update to fix merge conflicts (on github)?

2020-02-05 22:14 UTC, liach approved these changes

2020-02-05 22:24 UTC, Shnupbups commented
Mapped biome classes, added Shulker mapping from #1090

2020-02-05 22:51 UTC, Earthcomputer commented
> Mapped biome classes

Careful not to overlap with other PRs ;)

2020-02-05 23:55 UTC, liach commented on mappings/net/minecraft/block/enums/WallType.mapping
> +CLASS net/minecraft/class_4778 net/minecraft/block/enums/WallType
More like wall shape/connection

2020-02-06 04:42 UTC, Prospector approved these changes

2020-02-06 18:00 UTC, liach approved these changes

2020-02-06 18:25 UTC, Juuxel requested changes

2020-02-06 18:25 UTC, Juuxel commented on mappings/net/minecraft/entity/ItemEntity.mapping
> +		ARG 0 tergetEntity
```suggestion
		ARG 0 targetEntity
```

2020-02-06 18:27 UTC, liach commented
I hope this is merged quickly. Current yarn mappings doesn't allow game bootstrap to run successfully as some Fungi block's constructor is protected and called by `Blocks`.

2020-02-06 18:27 UTC, Juuxel commented
This should be ready once that typo is fixed.

2020-02-06 19:45 UTC, Juuxel approved these changes

2020-02-06 20:02 UTC, merged