Map / move DispenserBehavior
asiekierka/MinecraftPOMF pull request #111
Opened 2016-10-13 20:42 UTC by copygirl

2016-10-14 10:02 UTC, asiekierka requested changes

2016-10-14 10:02 UTC, asiekierka commented on mappings/net/minecraft/block/BlockDispenser.mapping
> +	METHOD a getDispenseOffset (Lnone/co;)Lnone/de;
getDispensionOffset? getDispensingOffset? Maybe...

2016-10-14 11:31 UTC, copygirl commented on mappings/net/minecraft/block/BlockDispenser.mapping
> +	METHOD a getDispenseOffset (Lnone/co;)Lnone/de;
Both sound weirder than `Dispense` to me.

2016-10-14 15:08 UTC, maxpowa commented on mappings/net/minecraft/block/BlockDispenser.mapping
> +	METHOD a getDispenseOffset (Lnone/co;)Lnone/de;
If I'm reading this correctly, isn't this more the position where dispensed items will initially spawn? This appears to return a full `Position` with the world x,y,z coords, not an offset `Position`.

2016-10-14 15:13 UTC, maxpowa commented on mappings/net/minecraft/block/dispenser/DispenserBehaviorProjectile.mapping
> +	METHOD b dispenseInternal (Lnone/co;Lnone/aes;)Lnone/aes;
Is this really the best name for this? Seems like it could definitely be better. Maybe something like `doDispense` or just `dispenseProjectile`. Looks like it's extending from `DispenserBehaviorItem` though so generic `performDispense` might be be better?

2016-10-14 21:39 UTC, copygirl commented on mappings/net/minecraft/block/BlockDispenser.mapping
> +	METHOD a getDispenseOffset (Lnone/co;)Lnone/de;
`getDispenseLocation` then? `getDispenseSpawnPosition` is something else that comes to mind.

2016-10-15 09:16 UTC, asiekierka commented on mappings/net/minecraft/block/BlockDispenser.mapping
> +	METHOD a getDispenseOffset (Lnone/co;)Lnone/de;
getDispenseLocation.

2016-10-15 12:32 UTC, merged