Map some various things
asiekierka/MinecraftPOMF pull request #112
Opened 2016-10-13 21:49 UTC by copygirl

2016-10-13 22:59 UTC, liach commented on mappings/net/minecraft/block/BlockFire.mapping
> +	METHOD e registerFlammables ()V
What is the difference between this and `init`?

2016-10-13 23:09 UTC, liach requested changes
I have some questions in mappings:

2016-10-13 23:09 UTC, liach commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
`killedByPlayer`?

2016-10-13 23:09 UTC, liach commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
`killedByPlayer`?

2016-10-13 23:09 UTC, liach commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
`killedByPlayer`?

2016-10-13 23:09 UTC, liach commented on mappings/net/minecraft/entity/EquipmentSlot.mapping
> +		ARG 3 name
Does this constructor have 6 args? It seems that only 4 are mapped.

2016-10-13 23:09 UTC, liach commented on mappings/net/minecraft/entity/mob/EntityMob.mapping
> +	CLASS none/sq$a
Wasn't this mapped?

2016-10-14 00:29 UTC, copygirl commented on mappings/net/minecraft/block/BlockFire.mapping
> +	METHOD e registerFlammables ()V
This just calls `registerFlammable` a bunch and is called on startup..? More descriptive than `init`.

2016-10-14 00:32 UTC, copygirl commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
This is `true` if `playerHitTimer > 0`, which is set to some value when hit by a player and counts down every update. Though it might be verbose, it's the most correct, I'd say.

2016-10-14 00:33 UTC, copygirl commented on mappings/net/minecraft/entity/mob/EntityMob.mapping
> +	CLASS none/sq$a
Added by Enigma when I attempted to rename it but I reverted it back to default.

2016-10-14 00:45 UTC, liach approved these changes

2016-10-14 04:35 UTC, unascribed commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
`lastAttacker`? It's implied to be a player by the argument type.

2016-10-14 04:35 UTC, unascribed commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
`lastAttacker`?

2016-10-14 04:35 UTC, unascribed commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
`lastAttacker`? (see above)

2016-10-14 04:35 UTC, unascribed commented on mappings/net/minecraft/entity/EquipmentSlot.mapping
> +		ARG 2 armorStandId
What is `armorStandId`, exactly?

2016-10-14 04:53 UTC, liach commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
That is a boolean.

2016-10-14 04:53 UTC, liach commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
That is a boolean. `Z`

2016-10-14 09:13 UTC, unascribed commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 recentlyHitByPlayer
Oh. I keep forgetting the signature is actually in the Enigma file, as it's hard to miss the binary signature when there's no classes in it.

I figured it was an EntityPlayer argument :L

2016-10-14 09:16 UTC, exaskye approved these changes

2016-10-14 10:07 UTC, asiekierka commented on mappings/net/minecraft/block/BlockFire.mapping
> +	METHOD e registerFlammables ()V
initFlammables

2016-10-14 10:07 UTC, asiekierka commented on mappings/net/minecraft/block/BlockFire.mapping
> +	METHOD e registerFlammables ()V
Or registerDefaultFlammables, or registerBuiltinFlammables

2016-10-14 11:44 UTC, copygirl commented
`Bootstrap.init` seems to basically call all default registration stuff (now `registerDefaults` instead of `init`), so maybe it should be renamed as well?

2016-10-15 09:17 UTC, merged