Fix swapped min and max method names
asiekierka/MinecraftPOMF pull request #1121
Opened 2020-02-20 15:10 UTC by falseresync

2020-02-20 15:41 UTC, Juuxel commented
These are overridden in `CavesChunkGeneratorConfig` to return 0 for min Y and 127 for max Y 🤔

2020-02-20 17:14 UTC, falseresync commented
Lol wut

2020-02-20 17:16 UTC, falseresync commented
Hmm `getMaxY = 0` in `OverworldChunkGeneratorConfig` too. That is super weird

2020-02-20 17:18 UTC, falseresync commented
But my way seems correct. In `SurfaceChunkGenerator.buildBedrock` they're used as in my variant

2020-03-04 23:45 UTC, Juuxel commented
Could you update the base branch to 20w10a?

2020-03-05 01:55 UTC, Runemoro commented
@falseresync I don't see the problem, they're not swapped...

2020-03-05 03:27 UTC, liach commented
So this one actually relates to #1123 and are both troubled by this min/max y thing

2020-03-06 19:35 UTC, falseresync commented
They're probably not `min`/`max` but rather some sort of `limit`, which can be either. But there're 2 of them. Maybe one should be `limitY` (or `yLimit`?) and the other one is `min` or `max`?

2020-03-06 19:45 UTC, liach commented
How are these 2 fields used, just curious?

2020-03-06 19:51 UTC, falseresync commented
They’re used as min and max respectively, but they switch their roles in 2(?) cases

2020-03-06 19:52 UTC, liach commented
> They’re used as min and max respectively, but they switch their roles in 2(?) cases

Like how? in a loop? Show the actual usage in enigma/decompiled code

2020-03-06 19:52 UTC, falseresync commented
I think they’re used in 1 place only, and switch their roles in children classes, aka not on the access side, but on the declaration side

2020-03-06 19:53 UTC, falseresync commented
Cannot check rn! Will update when I can, anyone else does that

2020-03-06 20:00 UTC, liach requested changes

2020-03-06 20:00 UTC, liach commented on mappings/net/minecraft/world/gen/chunk/ChunkGeneratorConfig.mapping
> +	METHOD method_16401 getMaxY ()I
```suggestion
	METHOD method_16400 getTopBedrockY ()I
	METHOD method_16401 getBottomBedrockY ()I
```

2020-03-06 21:20 UTC, liach approved these changes

2020-03-06 21:21 UTC, Runemoro commented
So what are the values of these for the overworld, where there is no top bedrock, and end, where there is no bedrock at all?

2020-03-06 21:23 UTC, liach commented
0 top bedrock or 256 bottom bedrock would skip bottom/top bedrock generation.

2020-03-06 21:23 UTC, jaskarth approved these changes

2020-03-06 21:33 UTC, falseresync commented
See #1157

2020-03-06 21:33 UTC, closed without merging