Map 20w09a blocks and items
asiekierka/MinecraftPOMF pull request #1137
Opened 2020-02-26 18:34 UTC by Earthcomputer

2020-02-26 21:28 UTC, jaskarth approved these changes

2020-02-27 02:34 UTC, liach requested changes

2020-02-27 02:34 UTC, liach commented on mappings/net/minecraft/advancement/criterion/TargetHitCriterion.mapping
> +		METHOD method_24865 crate (Lnet/minecraft/class_2096$class_2100;)Lnet/minecraft/class_4851$class_4852;
```suggestion
		METHOD method_24865 create (Lnet/minecraft/class_2096$class_2100;)Lnet/minecraft/class_4851$class_4852;
```

2020-02-27 02:34 UTC, liach commented on mappings/net/minecraft/item/Items.mapping
> +	FIELD field_22420 TARGET Lnet/minecraft/class_1792;
Is the item id just `minecraft:target`?

2020-02-27 12:25 UTC, Shnupbups commented on mappings/net/minecraft/item/Items.mapping
> +	FIELD field_22420 TARGET Lnet/minecraft/class_1792;
Yes, it is

2020-02-27 12:26 UTC, Shnupbups requested changes
Looks good, beside the typo liach pointed out in `TargetHitCriterion`

2020-02-27 13:49 UTC, liach approved these changes

2020-02-28 04:20 UTC, Runemoro approved these changes

2020-02-28 04:38 UTC, Shnupbups approved these changes

2020-02-28 16:05 UTC, merged