Map block/fluid state properties Minecraft provides
asiekierka/MinecraftPOMF pull request #1214
Opened 2020-03-21 22:42 UTC by i509VCB

2020-03-21 22:44 UTC, liach requested changes
Please move all `@param` to comments on individual parameters than as part of the method comment.

2020-03-21 22:45 UTC, i509VCB commented
> 
> 
> Please move all `@param` to comments on individual parameters than as part of the method comment.

Okay so thats why cloak didn't complete them properly

2020-03-21 22:59 UTC, i509VCB commented
Fixed the param comments

2020-03-22 00:42 UTC, liach approved these changes

2020-03-22 00:42 UTC, liach commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT  A property that specifies if a block is waterlogged.
```suggestion
		COMMENT A property that specifies if a block is waterlogged.
```

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This property only allows a block to face in one of the cardinal directions (north, south, east and west).
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This lowers the fence gate by 3 pixels to attach more cleanly to a wall.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT A property that specifies what type of piston.
```suggestion
		COMMENT A property that specifies the type of a piston.
```

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT A property that specifies if a tripwire is attached to tripwire hook.
```suggestion
		COMMENT A property that specifies if a tripwire is attached to a tripwire hook.
```

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT A property that specifies if a daylight sensor's output is inverted,.
```suggestion
		COMMENT A property that specifies if a daylight sensor's output is inverted.
```

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT A property that specifies the amount eggs in a turtle egg block.
```suggestion
		COMMENT A property that specifies the amount of eggs in a turtle egg block.
```

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>In vanilla, this is used to specify whether leaves should disappear when the logs are removed.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This property only allows a block to be oriented to the X and Z axes.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>Each rotation is 22.5 degrees.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT A property that specifies whether a double height block is the upper or lower half..
```suggestion
		COMMENT A property that specifies whether a double height block is the upper or lower half.
```

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This property is normally used for doors, trapdoors and fence gates but is also used by barrels.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT  <p>In vanilla, if TNT is unstable, it will ignite when broken.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This property does not allow for a rail to turn.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This property does not allow the hopper's output to face upwards.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT A property that specifies the overhang distance of a cauldron.
```suggestion
		COMMENT A property that specifies the overhang distance of a scaffolding.
```

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This occurs when a hay bale is placed under the campfire.
Closing tag

2020-03-22 01:34 UTC, Yanis48 commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT A property that specifies how the level of a composter.
```suggestion
		COMMENT A property that specifies the level of a composter.
```

2020-03-22 01:37 UTC, liach commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This property only allows a block to face in one of the cardinal directions (north, south, east and west).
Nah, javadoc generator will auto add closing tags

2020-03-22 01:37 UTC, liach commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>This lowers the fence gate by 3 pixels to attach more cleanly to a wall.
No need

2020-03-22 01:37 UTC, liach commented on mappings/net/minecraft/state/property/Properties.mapping
> +		COMMENT <p>In vanilla, this is used to specify whether leaves should disappear when the logs are removed.
No need

2020-03-22 11:20 UTC, YanisBft approved these changes

2020-03-22 23:31 UTC, merged