Some block mappings
asiekierka/MinecraftPOMF pull request #1223
Opened 2020-03-24 18:43 UTC by Yanis48

Some block mappings, including most of the new methods in `Blocks`.

2020-03-24 21:05 UTC, Juuxel approved these changes

2020-03-24 22:43 UTC, liach requested changes
Besides these, you should name `method_26113` and `method_26122` as well, which means like "always pass/return true" and "always fail/return false" as they are used as method reference for where `AbstractBlock.ContextPredicate` is needed

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +		ARG 0 level
Maybe 
```suggestion
		ARG 0 litLevel
```
as the result function only returns this level when the block state has "lit" property's value equal to "true"

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +	METHOD method_26119 getPistonSettings (Z)Lnet/minecraft/class_2665;
`createPiston(Block)`, as this returns a ready-to-go `PistonBlock` than just a `Block/AbstractBlock.Settings`

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +	METHOD method_26117 getLogSettings (Lnet/minecraft/class_3620;Lnet/minecraft/class_3620;)Lnet/minecraft/class_2465;
Also `createLog(Block)`, same reasoning as piston, returns a ready-to-go `PillarBlock`

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +	METHOD method_26115 getStemSettings (Lnet/minecraft/class_3620;)Lnet/minecraft/class_2248;
Same, `create(Nether)Stem(Block)` (the sound group refers to "nether stem")

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +	METHOD method_26107 getLightLevelFromBlockState (I)Ljava/util/function/ToIntFunction;
```suggestion
	METHOD method_26107 createLitBasedLightLevelGetter (I)Ljava/util/function/ToIntFunction;
```
Maybe need a more elegant name for this, as this does
```java
      return (state) -> {
         return state.get(Properties.LIT) ? parameter : 0;
      };
```

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +	METHOD method_26106 getLeavesSettings ()Lnet/minecraft/class_2397;
Same as piston, `createLeaves(Block)`

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +	METHOD method_26109 getBedSettings (Lnet/minecraft/class_1767;)Lnet/minecraft/class_2244;
`createBed(Block)`, same as piston

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +	METHOD method_26110 getShulkerBoxSettings (Lnet/minecraft/class_1767;Lnet/minecraft/class_4970$class_2251;)Lnet/minecraft/class_2480;
`createShulkerBox(Block)`, same as piston

2020-03-24 22:43 UTC, liach commented on mappings/net/minecraft/block/Blocks.mapping
> +	METHOD method_26120 getStainedGlassSettings (Lnet/minecraft/class_1767;)Lnet/minecraft/class_2506;
Same `createStainedGlass(Block)` as piston

2020-03-25 14:15 UTC, liach approved these changes
Nice!

2020-03-25 21:49 UTC, modmuss50 approved these changes

2020-03-25 21:49 UTC, merged