IWorld -> GenerationView
asiekierka/MinecraftPOMF pull request #1317
Opened 2020-05-01 02:17 UTC by i509VCB

This resolves the years old conflict of what `IWorld` should become.

Why `GenerationView`?

Commonly used in world gen

Implemented by `ChunkRegion`, which is used in world gen

Could represent a view of a world that is thread safe within the confines of world gen

2020-05-01 02:24 UTC, liach commented
Are you sure there is no other obsolete reference of `IWorld` in the mappings?

2020-05-01 02:29 UTC, i509VCB commented
Nothing I see with parameters still being named `IWorld` atleast

2020-05-01 02:54 UTC, jaskarth approved these changes
iapprove

2020-05-01 08:11 UTC, liach approved these changes
Should be good, assuming there is no other trash leftover (most likely not)

2020-05-01 08:50 UTC, YanisBft approved these changes

2020-05-01 10:10 UTC, Earthcomputer commented
`GenerationView` sounds like it's something that's supposed to be used for world generation, but it's used in a lot of places elsewhere.

2020-05-01 18:33 UTC, liach commented
It is not specific for generation, but like something something generation compatible

2020-05-01 22:19 UTC, Runemoro commented
> It is not specific for generation, but like something something generation compatible
That would be the same as calling `World` `NetherWorld` even though it's not specific for the nether, because it's nether compatible.

2020-05-01 22:20 UTC, Runemoro requested changes
As Earthcomputer said, this is used for things that have nothing to do with worldgen.

2020-05-01 22:44 UTC, i509VCB commented
`WorldAccess` was brought up in the yarn channel on discord. Thoughts on that instead?

2020-05-13 17:48 UTC, i509VCB commented
Susperseeded by https://github.com/FabricMC/yarn/pull/1350

2020-05-13 17:48 UTC, closed without merging