Tonights Work for review.
asiekierka/MinecraftPOMF pull request #135
Opened 2016-10-17 15:34 UTC by ryantheleach

2016-10-17 22:22 UTC, asiekierka requested changes

2016-10-17 22:22 UTC, asiekierka commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +		ARG 0 entity
Please do not map argument names for unnamed methods.

2016-10-17 22:22 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/EntityHusk.mapping
> +	METHOD dg getSkull ()Lnone/aes;
Just Skull?　Sure?

2016-10-17 22:22 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/EntityShulker.mapping
> +		ARG 0 localDifficulty
Please do not map argnames for unmapped methods.

2016-10-17 22:22 UTC, asiekierka commented on mappings/none/bmg.mapping
> +	METHOD b isGameModeSurvivalLike ()Z
Are you sure this method is used in this manner? Same for all the other ones...

2016-10-18 04:45 UTC, ryantheleach commented on mappings/net/minecraft/entity/mob/EntityHusk.mapping
> +	METHOD dg getSkull ()Lnone/aes;
The only place this method is used, is to give differing results between the husk, zombie, pigman and villager inside an if statement to check if it's being killed by a charged creeper.

It's not even used for Skeleton / Stray, as they don't inherit onDeath from SkeletonBase.

Sure this could change, but then it would end up being chargedCreeperDrop , and considering it's only returning a single itemstack, I doubt it.

If the method changed, If it returned more then 1 item, If it was inherited higher then EntityZombie I would agree that getSkull would be a bad name.

2016-10-18 12:32 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/EntityHusk.mapping
> +	METHOD dg getSkull ()Lnone/aes;
It might very well be the drop! Doesn't have to be a list... I think getChargedCreeperDrop, or getDroppedSkull, might work better.

2016-10-18 12:39 UTC, asiekierka requested changes

2016-10-18 12:39 UTC, asiekierka commented on mappings/net/minecraft/entity/thrown/EntityThrownPotion.mapping
> +	METHOD a waterHurts (Lnone/sp;)Z
doesWaterHurt

2016-10-18 12:39 UTC, asiekierka commented on mappings/net/minecraft/entity/player/InventoryPlayer.mapping
> +	METHOD e validHotbarIndex (I)Z
isValidHotbarIndex.

(as a future note, please try to use is/does/can/has for boolean methods and *NOT* use it for boolean fields)

2016-10-18 13:05 UTC, merged