Add mappings for ItemRender, Containers and Villagers
asiekierka/MinecraftPOMF pull request #137
Opened 2016-10-17 22:17 UTC by Nedelosk

2016-10-17 22:26 UTC, asiekierka commented
I think you accidentally included https://github.com/FabricMC/pomf/pull/136 here.

2016-10-17 22:31 UTC, asiekierka requested changes

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/villager/Villager.mapping
> +CLASS none/aaf net/minecraft/villager/Villager
Just Villager? Are you sure?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/gui/CreativeTab.mapping
> +	METHOD k notUseScrollBar ()Lnone/ads;
What?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/entity/player/EntityPlayer.mapping
> +	METHOD cV getXpSeed ()I
What?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/entity/passive/EntityVillager.mapping
> +	METHOD s_ getPlayer ()Lnone/aam;
Player...? Just Player?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/entity/passive/EntityVillager.mapping
> +	METHOD a setRecipeLIst (Lnone/aij;)V
setRecipeList

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/entity/passive/EntityVillager.mapping
> +	FIELD bE recipeLIst Lnone/aij;
recipeList

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/container/ContainerVillager.mapping
> +		ARG 0 inventoy
inventory, or inv

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/container/Container.mapping
> +	METHOD b calculateComparatorInput (Lnone/qv;)I
Input or Output? I think it's output to a comparator

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/container/Container.mapping
> +	FIELD i playersWithNPermission Ljava/util/Set;
NPermission?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/container/Container.mapping
> +		ARG 1 allowPlayerToUse
That's a bad argument name.

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/container/Container.mapping
> +	METHOD a givePlayerPermission (Lnone/aam;Z)V
Is this what the method does? Not adding listeners or anything?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/client/render/item/ItemRenderer.mapping
> +	METHOD a renderModelWithColor (Lnone/bzm;I)V
Why not renderModelColored? Or renderColoredModel?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/client/render/item/ItemRenderer.mapping
> +	METHOD a renderItemAmountAndDamageInGUIWithoutText (Lnone/bef;Lnone/aes;II)V
Those names are a bit long. Can we make them shorter?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/client/gui/ingame/GuiCreativeInventory.mapping
> +		METHOD a onContentChanged (Lnone/aes;Lnone/aes;)V
onStackChanged?

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/client/gui/ingame/GuiCreativeInventory.mapping
> +		METHOD a canTakeItem (Lnone/aam;)Z
canTakeItems? Does not seem to point to a specific item...

2016-10-17 22:31 UTC, asiekierka commented on mappings/net/minecraft/block/Block.mapping
> +	METHOD c getComparatorInput (Lnone/asm;Lnone/aiw;Lnone/cn;)I
Not getComparatorOutput, as in output to a comparator?

2016-10-17 22:44 UTC, Nedelosk commented on mappings/net/minecraft/entity/player/EntityPlayer.mapping
> +	METHOD cV getXpSeed ()I
The name of the variable is xpSeed.

2016-10-17 22:45 UTC, asiekierka commented on mappings/net/minecraft/entity/player/EntityPlayer.mapping
> +	METHOD cV getXpSeed ()I
Okay. Someone else should probably verify if the variable name is correct.

2016-10-18 00:32 UTC, mezz commented on mappings/net/minecraft/entity/player/EntityPlayer.mapping
> +	METHOD cV getXpSeed ()I
Confirmed, EntityPlayer serializes this field to nbt as "XpSeed".

2016-10-18 00:34 UTC, mezz commented on mappings/net/minecraft/entity/player/EntityPlayer.mapping
> +	METHOD cV getXpSeed ()I
It's used to seed the rng that decides what enchantments are available at the enchantment table.

2016-10-18 07:13 UTC, asiekierka commented on mappings/net/minecraft/entity/player/EntityPlayer.mapping
> +	METHOD cV getXpSeed ()I
getEnchantmentTableSeed would fit MUCH better.

2016-10-18 12:30 UTC, asiekierka requested changes

2016-10-18 12:30 UTC, asiekierka commented on mappings/net/minecraft/client/render/item/ItemRenderer.mapping
> +		ARG 2 isThreeDimensinalInGui
I don't like that. Perhaps hasDepthInGui? @copygirl

2016-10-18 12:30 UTC, asiekierka commented on mappings/net/minecraft/client/render/item/ItemRenderer.mapping
> +		ARG 3 holdInLeftHand
Maybe leftHanded, to all of these? @copygirl

2016-10-18 12:30 UTC, asiekierka commented on mappings/net/minecraft/container/ContainerChest.mapping
> +CLASS none/acd net/minecraft/container/ContainerChest
Are you sure about that?

2016-10-18 14:10 UTC, asiekierka commented on mappings/net/minecraft/client/render/FirstPersonRenderer.mapping
> +		ARG 3 holdInLeftHand
leftHanded here too? Not sure, you might've missed it or it might've been on purpose.

2016-10-18 14:49 UTC, darkhax commented on mappings/net/minecraft/client/render/item/ItemRenderer.mapping
> +		ARG 2 isThreeDimensinalInGui
I really like `hasDepthInGui`.

2016-10-18 15:00 UTC, merged