20w21a brain
asiekierka/MinecraftPOMF pull request #1387
Opened 2020-05-20 22:37 UTC by liach

Signed-off-by: liach <liach@users.noreply.github.com>

2020-05-20 22:40 UTC, Juuxel requested changes

2020-05-20 22:40 UTC, Juuxel commented on mappings/net/minecraft/entity/ai/brain/Brain.mapping
> +	METHOD method_28315 steramMemories ()Ljava/util/stream/Stream;
```suggestion
	METHOD method_28315 streamMemories ()Ljava/util/stream/Stream;
```

2020-05-20 22:58 UTC, Juuxel approved these changes

2020-05-21 10:08 UTC, Yanis48 commented on mappings/net/minecraft/entity/ai/brain/Brain.mapping
> +		ARG 1 activitiy
```suggestion
		ARG 1 activity
```

2020-05-22 00:58 UTC, YanisBft approved these changes

2020-05-22 11:40 UTC, modmuss50 approved these changes

2020-05-22 11:40 UTC, merged