StatusEffect and similiar renames as per #1036
asiekierka/MinecraftPOMF pull request #1402
Opened 2020-05-29 03:20 UTC by dexman545

StatusEffectType -> StatusEffectCategory (#1036)
StatusEffect -> StatusEffectType
StatusEfectInstance -> StatusEffect
(and related names)

2020-06-01 21:31 UTC, Juuxel requested changes

2020-06-01 21:31 UTC, Juuxel commented on mappings/net/minecraft/util/registry/Registry.mapping
> +	FIELD field_11159 STATUS_EFFECT_TYPE Lnet/minecraft/class_2378;
```suggestion
	FIELD field_11159 STATUS_EFFECT Lnet/minecraft/class_2378;
```
I think this is fine without the type suffix; its ID is `mob_effect` and we have other `*Type` registries without the suffix (`SCREEN_HANDLER`, `RULE_TEST` iirc).

2020-06-02 12:46 UTC, liach approved these changes
Content looks good, though I don't agree with the rename

2020-06-11 00:19 UTC, liach commented
Mind fix the merge conflicts?

2020-06-11 07:26 UTC, Juuxel commented on mappings/net/minecraft/util/registry/Registry.mapping
> +	FIELD field_11159 STATUS_EFFECT_TYPE Lnet/minecraft/class_2378;
Huh? I thought you changed it back to `STATUS_EFFECT` in 2924a85...

2020-07-23 22:29 UTC, Runemoro approved these changes

2020-07-24 14:40 UTC, YanisBft requested changes
Please no, registry name is `status_effect`, not `status_effect_type`

2020-07-24 15:11 UTC, Juuxel commented
There are other `Type`s registered in registries without a `_type` suffix:
- Rule test types in `rule_test`
- Pos rule test types in `pos_rule_test`
- Menu types in `menu`

2021-03-28 20:46 UTC, closed without merging