Couple of AbstractBlockState Mappings
asiekierka/MinecraftPOMF pull request #1410
Opened 2020-05-30 01:57 UTC by dexman545

AbstractBlock:
method_29291 -> doesRequireTool
field_25184 -> requiresTool

2020-05-30 02:09 UTC, Prospector commented
I'd name the method requiresTool as well, the `does` prefix is quite odd imo.

2020-05-30 02:51 UTC, dexman545 commented
then the name would be the same as the setting's method that sets the block requiring a tool

2020-05-30 03:14 UTC, kashike commented
`toolRequired`

2020-05-30 05:47 UTC, liach requested changes

2020-05-30 05:47 UTC, liach commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		FIELD field_25185 requiresTool Z
```suggestion
		FIELD field_25185 toolRequired Z
```

2020-05-30 05:47 UTC, liach commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		METHOD method_29292 requiresTool ()V
```suggestion
		METHOD method_29292 toolRequired ()V
```

2020-05-30 05:47 UTC, liach commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		FIELD field_25184 requiresTool Z
```suggestion
		FIELD field_25184 toolRequired Z
```

2020-05-30 05:47 UTC, liach commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		METHOD method_29291 toolRequired ()Z
```suggestion
		METHOD method_29291 isToolRequired ()Z
```

2020-05-30 05:53 UTC, shedaniel commented
I would prefer the old builder like names

2020-05-30 05:58 UTC, liach commented
Usually we don't use third person singular tense in method names, so imo `requiresTool` isn't a good method name, especially for a setter. `requireTool` may be better, like we would declare `eat` than `eats` in a sheep class.

Also `toolRequired` is an adjective phrase, which is usually a better choice for names of boolean fields/variables.

2020-05-30 06:01 UTC, shedaniel commented
then I would not use requireTool as the method then, I can deal with toolRequired but please be consistent

2020-05-30 06:03 UTC, liach commented
Sure, good point, updated my suggestion

2020-05-30 06:14 UTC, dexman545 commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		METHOD method_29292 requiresTool ()V
This change breaks with the other methods in setting's naming convention (being able to read the block settings in semi-natural English, ie. dropsNothing)

2020-05-30 06:29 UTC, liach requested changes

2020-05-30 06:29 UTC, liach commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		FIELD field_25184 requiresTool Z
```suggestion
		FIELD field_25184 toolRequired Z
```
This is **not** something in the builder. You argue for following the style in the builder, but this is not builder and you should use the regular naming convention.

2020-05-30 06:29 UTC, liach commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		METHOD method_29292 requiresTool ()V
Mark this as resolved please.

2020-05-30 09:24 UTC, Yanis48 commented
It's a bit confusing the AbstractBlock.Settings field/method are different from the AbstractBlock.AbstractBlockState ones

2020-05-30 09:50 UTC, dexman545 commented
Woops, git messed up and had tried to push to the wrong place.
Field names should match now

2020-06-01 09:40 UTC, YanisBft approved these changes

2020-06-01 09:44 UTC, dexman545 commented
To help clarify:
(requiresTool)
```
public AbstractBlock.Settings method_29292() {
         this.field_25185 = true;
         return this;
}
```

is in the block settings, setting the value to true as part of a build-like creator, while (toolRequired)
```
public boolean method_29291() {
         return this.field_25184;
}
```
Gets the value

2020-06-01 16:51 UTC, liach approved these changes

2020-06-01 21:20 UTC, modmuss50 approved these changes

2020-06-01 21:33 UTC, Juuxel approved these changes

2020-06-01 21:36 UTC, merged