Map graphics modes
asiekierka/MinecraftPOMF pull request #1418
Opened 2020-06-04 19:32 UTC by haykam821

This pull request maps graphics modes, which are 'fast', 'fancy', and 'fabulous'.

2020-06-04 19:38 UTC, liach approved these changes

2020-06-04 19:38 UTC, liach commented on mappings/net/minecraft/client/options/GraphicsMode.mapping
> +	FIELD field_25432 languageKey Ljava/lang/String;
```suggestion
	FIELD field_25432 translationKey Ljava/lang/String;
```

2020-06-04 19:38 UTC, liach commented on mappings/net/minecraft/client/options/GraphicsMode.mapping
> +		ARG 4 languageKey
```suggestion
		ARG 4 translationKey
```

2020-06-04 19:38 UTC, liach commented on mappings/net/minecraft/client/options/GraphicsMode.mapping
> +	METHOD method_29593 getLanguageKey ()Ljava/lang/String;
```suggestion
	METHOD method_29593 getTranslationKey ()Ljava/lang/String;
```

2020-06-04 19:38 UTC, liach commented on mappings/net/minecraft/client/options/GraphicsMode.mapping
> +	METHOD method_29595 getNextMode ()Lnet/minecraft/class_5365;
```suggestion
	METHOD method_29595 next ()Lnet/minecraft/class_5365;
```

2020-06-04 19:38 UTC, liach commented on mappings/net/minecraft/client/options/GraphicsMode.mapping
> +	METHOD method_29596 getPreviousMode ()Lnet/minecraft/class_5365;
```suggestion
	METHOD method_29596 previous ()Lnet/minecraft/class_5365;
```

2020-06-04 19:38 UTC, liach commented on mappings/net/minecraft/client/options/GraphicsMode.mapping
> +	METHOD method_29592 getModeById (I)Lnet/minecraft/class_5365;
```suggestion
	METHOD method_29592 byId (I)Lnet/minecraft/class_5365;
```

2020-06-05 10:14 UTC, Juuxel requested changes
Should be good to merge with liach's requests.

2020-06-05 12:47 UTC, liach commented
Mind change branch to merge into to 1.16-pre2?

2020-06-06 00:43 UTC, liach approved these changes

2020-06-06 11:50 UTC, YanisBft approved these changes

2020-06-06 15:04 UTC, Juuxel approved these changes

2020-06-07 14:21 UTC, merged