Map some entity model fields
asiekierka/MinecraftPOMF pull request #1449
Opened 2020-06-08 22:39 UTC by modmuss50

Wrote a mod to help figure these out.

2020-06-09 01:07 UTC, liach commented on mappings/net/minecraft/client/render/entity/model/HorseEntityModel.mapping
> +	FIELD field_20930 leftBackLegBaby Lnet/minecraft/class_630;
maybe `babyXxLeg` than `xxLegBaby`?

2020-06-09 01:07 UTC, liach commented on mappings/net/minecraft/client/render/entity/model/LargePufferfishEntityModel.mapping
> +		COMMENT
```suggestion
```

2020-06-09 01:07 UTC, liach commented on mappings/net/minecraft/client/render/entity/model/LargePufferfishEntityModel.mapping
> +	FIELD field_3498 rearRightSpikes Lnet/minecraft/class_630;
i'd prefer order like left/right front/rear like you did in horse/hoglin model fields

2020-06-09 11:34 UTC, Yanis48 commented on mappings/net/minecraft/client/render/entity/model/HoglinEntityModel.mapping
> +	FIELD field_22231 rightFontLeg Lnet/minecraft/class_630;
```suggestion
	FIELD field_22231 rightFrontLeg Lnet/minecraft/class_630;
```

2020-06-09 11:34 UTC, Yanis48 commented on mappings/net/minecraft/client/render/entity/model/HorseEntityModel.mapping
> +	FIELD field_20930 leftBackLegBaby Lnet/minecraft/class_630;
or `xxBabyLeg`?

2020-06-09 11:34 UTC, Yanis48 commented on mappings/net/minecraft/client/render/entity/model/HorseEntityModel.mapping
> +	FIELD field_20933 rightFontLegBaby Lnet/minecraft/class_630;
```suggestion
	FIELD field_20933 rightFrontLegBaby Lnet/minecraft/class_630;
```

2020-06-09 11:34 UTC, Yanis48 commented on mappings/net/minecraft/client/render/entity/model/LargePufferfishEntityModel.mapping
> +	FIELD field_3489 rightFontSpikes Lnet/minecraft/class_630;
```suggestion
	FIELD field_3489 rightFrontSpikes Lnet/minecraft/class_630;
```

2020-06-09 11:34 UTC, Yanis48 commented on mappings/net/minecraft/client/render/entity/model/LargePufferfishEntityModel.mapping
> +	FIELD field_3491 bottomFontSpikes Lnet/minecraft/class_630;
```suggestion
	FIELD field_3491 bottomFrontSpikes Lnet/minecraft/class_630;
```

2020-06-09 11:34 UTC, Yanis48 commented on mappings/net/minecraft/client/render/entity/model/MediumPufferfishEntityModel.mapping
> +	FIELD field_3511 rearFontSpikes Lnet/minecraft/class_630;
```suggestion
	FIELD field_3511 rearFrontSpikes Lnet/minecraft/class_630;
```

2020-06-09 11:34 UTC, Yanis48 commented on mappings/net/minecraft/client/render/entity/model/MediumPufferfishEntityModel.mapping
> +	FIELD field_3513 topFontSpikes Lnet/minecraft/class_630;
```suggestion
	FIELD field_3513 topFrontSpikes Lnet/minecraft/class_630;
```

2020-06-09 11:34 UTC, Yanis48 commented on mappings/net/minecraft/client/render/entity/model/MediumPufferfishEntityModel.mapping
> +	FIELD field_3519 rightFontSpikes Lnet/minecraft/class_630;
```suggestion
	FIELD field_3519 rightFrontSpikes Lnet/minecraft/class_630;
```

2020-06-10 15:37 UTC, Prospector requested changes
Just some consistency things with rear vs. back (I like back better), and some things others have pointed out. Overall good though

2020-06-10 15:37 UTC, Prospector commented on mappings/net/minecraft/client/render/entity/model/LargePufferfishEntityModel.mapping
> +	FIELD field_3498 rearRightSpikes Lnet/minecraft/class_630;
Back is used elsewhere instead of rear, so imo this should be back as well

2020-06-24 21:27 UTC, modmuss50 commented
Closing this as im not happy with it and will re-create it from sratch. I realised I got my left and rights messed up as well lol.

2020-06-24 21:27 UTC, closed without merging