More Village and Entity mappings
asiekierka/MinecraftPOMF pull request #147
Opened 2016-10-22 07:52 UTC by mezz

2016-10-23 22:53 UTC, unascribed commented on mappings/net/minecraft/entity/Entity.mapping
> +		ARG 0 player
Parameters to an unmapped method shouldn't be mapped

2016-10-23 22:53 UTC, unascribed commented on mappings/net/minecraft/entity/player/InventoryPlayer.mapping
> +	METHOD a getCurrentMiningStrength (Lasm;)F
`getMiningStrength`? Is there a reason "Current" is added on here?

2016-10-23 22:54 UTC, mezz commented on mappings/net/minecraft/entity/player/InventoryPlayer.mapping
> +	METHOD a getCurrentMiningStrength (Lasm;)F
It varies depending on what you're holding

2016-10-23 22:55 UTC, unascribed commented on mappings/net/minecraft/entity/player/InventoryPlayer.mapping
> +	METHOD a getCurrentMiningStrength (Lasm;)F
I suppose that makes sense, as `getMiningStrength` could imply it would only change on a call to a setter.

2016-10-23 23:44 UTC, exaskye approved these changes

2016-10-24 00:17 UTC, copygirl commented on mappings/net/minecraft/entity/player/InventoryPlayer.mapping
> +	METHOD a getCurrentMiningStrength (Lasm;)F
Avoid "mining/digging/harvesting". Use `breaking`.

2016-10-24 00:22 UTC, copygirl requested changes

2016-10-24 00:22 UTC, copygirl commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +	FIELD by lastAttackedTimestamp I
`time` instead of `timestamp` would be enough.

2016-10-24 00:22 UTC, copygirl commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +	FIELD az hurtTime I
What is "hurt time"?

2016-10-24 00:22 UTC, copygirl commented on mappings/net/minecraft/villager/VillageDoor.mapping
> +	FIELD f entityInsideTicks I
In my opinion, `tick` doesn't make sense in this case. Use `time`?

2016-10-24 00:22 UTC, copygirl commented on mappings/net/minecraft/world/chunk/Chunk.mapping
> +	METHOD c isSkyVisible (Lcn;)Z
`isSkyUnobstructed` ?

2016-10-24 01:08 UTC, mezz commented on mappings/net/minecraft/villager/VillageDoor.mapping
> +	FIELD f entityInsideTicks I
This one is difficult to name. Each entity "inside" the door will tick it, so if there are two villagers inside the door they will tick that door at twice the rate of one villager.

2016-10-24 01:11 UTC, mezz commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +	FIELD by lastAttackedTimestamp I
Sounds good

2016-10-24 01:15 UTC, mezz commented on mappings/net/minecraft/entity/EntityLiving.mapping
> +	FIELD az hurtTime I
I got this name from the EntityLiving serialize/deserialize tags. I will remove the mapping since I don't understand it.

2016-10-24 01:16 UTC, copygirl commented on mappings/net/minecraft/villager/VillageDoor.mapping
> +	FIELD f entityInsideTicks I
What about `lastTickSeenByVillager` ?

2016-10-27 23:33 UTC, mezz commented on mappings/net/minecraft/world/chunk/Chunk.mapping
> +	METHOD c isSkyVisible (Lcn;)Z
That's a better name, I agree.

2016-10-27 23:34 UTC, mezz commented on mappings/net/minecraft/villager/VillageDoor.mapping
> +	FIELD f entityInsideTicks I
I can change that one, yes.

2016-10-27 23:41 UTC, mezz commented on mappings/net/minecraft/entity/player/InventoryPlayer.mapping
> +	METHOD a getCurrentMiningStrength (Lasm;)F
This is based on another mapping that uses "mining", so I will update them all to use "blockBreaking" instead.

2016-10-28 11:49 UTC, copygirl approved these changes

2016-10-28 13:27 UTC, merged