Lots of new mappings
asiekierka/MinecraftPOMF pull request #1504
Opened 2020-06-24 11:55 UTC by RDIL

Cool stuff

2020-06-25 17:48 UTC, liach requested changes

2020-06-25 17:48 UTC, liach commented on mappings/net/minecraft/client/render/entity/feature/VillagerResourceMetadata.mapping
> +		METHOD values values ()[Lnet/minecraft/class_3888$class_3889;
```suggestion
```

2020-06-25 17:48 UTC, liach commented on mappings/net/minecraft/container/BeaconContainer.mapping
> +	CLASS class_1705 SlotPayment
probably rename this to `PaymentSlot`
```suggestion
	CLASS class_1705 PaymentSlot
```

2020-06-25 17:48 UTC, liach commented on mappings/net/minecraft/container/Container.mapping
> +		COMMENT A list of item stacks that is used for tracking changes in {@link
```suggestion
		COMMENT A list of item stacks that is used for tracking changes in {@link #sendContentUpdates()}.
```
Think this is a bug with old enigma.

2020-06-25 17:48 UTC, liach commented on mappings/net/minecraft/container/ContainerFactory.mapping
> +	METHOD createMenu createMenu (ILnet/minecraft/class_1661;Lnet/minecraft/class_1657;)Lnet/minecraft/class_1703;
```suggestion
	METHOD createMenu (ILnet/minecraft/class_1661;Lnet/minecraft/class_1657;)Lnet/minecraft/class_1703;
```
Unfortunatley please don't mark things as deobfuscated. you know, old enigma sucks sometimes.

2020-06-25 17:48 UTC, liach commented on mappings/net/minecraft/container/PlayerContainer.mapping
> +	METHOD method_7641 emptyArmorSlotIDs ()[Ljava/lang/String;
```suggestion
	METHOD method_7641 getEmptyArmorSlotIds ()[Ljava/lang/String;
```

2020-06-26 02:08 UTC, RDIL commented
Thanks @liach for the review!

2020-06-28 12:27 UTC, modmuss50 commented
Are these backported from newer versions? or are they new to 1.14?

2020-06-29 01:20 UTC, RDIL commented
New.  I would make these against master but my mod targets these versions.  I'm fine with others forward-porting these.

2020-06-29 03:34 UTC, liach approved these changes

2020-07-21 03:34 UTC, Runemoro approved these changes

2020-08-20 02:31 UTC, RDIL commented
@modmuss50 can we get this merged?

2020-10-08 15:02 UTC, RDIL commented
Just a ding to remind people to review/merge :)

2020-12-17 20:03 UTC, modmuss50 approved these changes
Ill merge this in, but like with the other 1.14.4 PR this wont get released as we dont have this setup to release from github actions.

Thanks.

2020-12-17 20:03 UTC, merged