Map OptionFix
asiekierka/MinecraftPOMF pull request #1523
Opened 2020-06-27 22:02 UTC by i509VCB

2020-06-28 02:49 UTC, liach requested changes

2020-06-28 02:49 UTC, liach commented on mappings/net/minecraft/datafixer/fix/OptionFix.mapping
> +		ARG 1 parentSchema
```suggestion
		ARG 1 outputSchema
```

2020-07-01 20:52 UTC, liach approved these changes

2020-07-01 21:03 UTC, YanisBft approved these changes

2020-07-02 10:52 UTC, merged