Map new tag logic.
asiekierka/MinecraftPOMF pull request #1539
Opened 2020-07-01 20:38 UTC by i509VCB

Much of the logic seems to have been seperated away from the `TagContainer` into a sort of `TagManager` now.

2020-07-01 21:13 UTC, liach requested changes
I really can't agree with this... what matcher retained as `TagContainer` is really the tag loader. What you mapped as `TagManager` is the actual tag container for each type of tag.

Also `GlobalTagAccessor` has some change that is big enough for a reevaluation as well. I'd suggest re-look into tags than basing off on previous works and matcher's matches.

2020-07-01 21:13 UTC, liach commented on mappings/net/minecraft/tag/GlobalTagAccessor.mapping
> +	METHOD method_29224 getTagDifferences (Lnet/minecraft/class_5415;)Ljava/util/Set;
This is really only reporting the elements that the required accessors has and the registry tag manager doesn't have. so this is like `getMissingTags`

2020-07-02 07:49 UTC, Earthcomputer requested changes
Several problems with this PR.
- You have named a class `RegistryTagManager` which contains multiple `TagManager`s. This is extremely confusing, the previous naming of `RegistryTagManager` containing `TagContainer`s was better than this, although I'm open to suggestions for better names.
- Does not rename most of the fields and methods in reference to the `TagContainer` -> `TagManager` rename.
- Leaves a class called `TagContainer` which now only has to do with tag deserializing.
- Does not rename anything in `SetTag`.

In addition, some other minor comments:

2020-07-02 07:49 UTC, Earthcomputer commented on mappings/net/minecraft/tag/GlobalTagAccessorRegistry.mapping
> +	METHOD method_30203 getDifferences (Lnet/minecraft/class_5415;)Lcom/google/common/collect/Multimap;
Same as liach's comment here. It's `getMissingTags`. That's especially obvious if you look at the call hierarchy of this method.

2020-07-02 07:49 UTC, Earthcomputer commented on mappings/net/minecraft/tag/RegistryTagManager.mapping
> +	FIELD field_25744 EMPTY_TAG_MANAGER Lnet/minecraft/class_5415;
```suggestion
	FIELD field_25744 EMPTY Lnet/minecraft/class_5415;
```

2020-07-03 21:57 UTC, Earthcomputer commented
Superseded by #1543

2020-07-03 21:57 UTC, closed without merging