TypeConsumer is actually a visitor
asiekierka/MinecraftPOMF pull request #1566
Opened 2020-07-09 02:05 UTC by i509VCB

Per discussion with Player about the game rule api, he noticed that TypeConsumer is actually a visitor. So here is a PR.

And map that one bootstrap method that uses the visitor

2020-07-09 02:11 UTC, liach approved these changes
Simple and clean change. :+1:

2020-07-09 02:36 UTC, Player3324 requested changes

2020-07-09 02:36 UTC, sfPlayer1 commented on mappings/net/minecraft/world/GameRules.mapping
> +	METHOD method_20744 visit (Lnet/minecraft/class_1928$class_4311;)V
I would name this `accept` or `acceptAll`, elements typically use accept(visitor) to call visitor.visitXY(element).

2020-07-09 02:36 UTC, sfPlayer1 commented on mappings/net/minecraft/world/GameRules.mapping
> +		COMMENT Visits all registered game rules using the supplied visitor.
This needs to be passive form, the visitor is visiting, not GameRules. Something like `Make the visitor visit all game rules.\n\n<p>The visitation involves calling both accept() and acceptX() for every game rule, where X is the current rule's concrete type such as Boolean.`

2020-07-09 02:43 UTC, liach commented
Since player points out, guess we can make `acceptBoolean` `visitBoolean` etc

2020-07-09 04:28 UTC, liach approved these changes

2020-07-09 05:14 UTC, Player3324 approved these changes

2020-07-09 09:50 UTC, YanisBft approved these changes

2020-07-09 22:47 UTC, shartte commented on mappings/net/minecraft/world/GameRules.mapping
> +			COMMENT <p>Note {@link #accept(GameRules.Key, GameRules.Type)} will be called before this method is visited.
```suggestion
			COMMENT <p>Note {@link #accept(GameRules.Key, GameRules.Type)} will be called before this method.
```

2020-07-09 22:47 UTC, shartte commented on mappings/net/minecraft/world/GameRules.mapping
> +			COMMENT <p>Note {@link #accept(GameRules.Key, GameRules.Type)} will be called before this method is visited.
```suggestion
			COMMENT <p>Note {@link #accept(GameRules.Key, GameRules.Type)} will be called before this method.
```

2020-07-09 22:48 UTC, shartte approved these changes
Only had minor suggestions.

2020-07-10 11:59 UTC, modmuss50 approved these changes

2020-07-10 11:59 UTC, merged