Moved tree decorators into their own package
asiekierka/MinecraftPOMF pull request #1579
Opened 2020-07-13 15:46 UTC by Yanis48

Fixes #1320 . This PR moves tree decorators into a `world/gen/tree` package, so they can't be confused with regular decorators

2020-07-13 15:52 UTC, shartte approved these changes

2020-07-13 17:52 UTC, Runemoro approved these changes

2020-07-14 02:49 UTC, liach commented on mappings/net/minecraft/world/biome/Biome.mapping
> +		COMMENT @return the lists of features configured for each {@link net.minecraft.world.gen.GenerationStep.Feature feature generation step}, up to the highest step that has a configured feature.
```suggestion
		COMMENT Returns the lists of features configured for each {@link net.minecraft.world.gen.GenerationStep.Feature feature generation step}, up to the highest step that has a configured feature.
```

2020-07-14 02:49 UTC, liach commented on mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
> +		COMMENT @return null if no structure could be found within the given search radius
```suggestion
		COMMENT @return {@code null} if no structure could be found within the given search radius
```

2020-07-14 02:49 UTC, liach commented on mappings/net/minecraft/world/gen/chunk/ChunkGenerator.mapping
>  			COMMENT This is ignored for strongholds.
```suggestion
			COMMENT whether only structures that are not referenced by generated chunks (chunks past the STRUCTURE_STARTS stage) are returned, excluding strongholds
```

2020-07-14 02:49 UTC, liach commented on mappings/net/minecraft/world/gen/feature/StructureFeature.mapping
> +		COMMENT @return null if no structure could be found within the given search radius
```suggestion
		COMMENT @return {@code null} if no structure could be found within the given search radius
```

2020-07-17 14:19 UTC, modmuss50 approved these changes

2020-07-17 19:03 UTC, liach approved these changes

2020-07-17 20:17 UTC, Juuxel requested changes

2020-07-17 20:17 UTC, Juuxel commented on mappings/net/minecraft/world/gen/tree/TreeDecoratorType.mapping
> +		ARG 0 name
```suggestion
		ARG 0 id
```

2020-07-19 13:58 UTC, jaskarth approved these changes

2020-07-19 14:06 UTC, merged