Did some mappings in RedstoneWireBlock
asiekierka/MinecraftPOMF pull request #1606
Opened 2020-07-24 22:29 UTC by Spaceman

2020-07-24 22:38 UTC, YanisBft approved these changes

2020-07-24 22:52 UTC, Spaceman commented
I feel like a better name could be used here but getReceivedPower makes the most sense, perhaps a change should be made to the method im world to be more clear about its purpose which is to find the highest power on all horizontal directions

2020-07-25 00:43 UTC, haykam821 requested changes

2020-07-25 00:43 UTC, haykam821 commented on mappings/net/minecraft/block/RedstoneWireBlock.mapping
> +	METHOD method_27842 geReceivedRedstonePower (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;)I
```suggestion
	METHOD method_27842 getReceivedRedstonePower (Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;)I
```

2020-07-25 02:58 UTC, liach approved these changes

2020-07-25 03:01 UTC, haykam821 approved these changes
The rest of the methods can be fully mapped later.

2020-07-25 03:03 UTC, liach commented
Hmm, I doubt the rest of these methods may just be lambdas. Anyways look great, ready to go

2020-07-25 09:57 UTC, merged