rayTrace -> rayCast
asiekierka/MinecraftPOMF pull request #1700
Opened 2020-08-17 15:11 UTC by Scotsguy

Quoting from wikipedia,
> In 3D computer graphics, ray tracing is a rendering technique for generating an image by tracing the path of light as pixels in an image plane and simulating the effects of its encounters with virtual objects.

https://en.wikipedia.org/wiki/Ray_tracing_(graphics)
> Ray casting can refer to [...] a non-recursive ray tracing rendering algorithm that only casts primary rays

https://en.wikipedia.org/wiki/Ray_casting

For example, ProjectileUtil#rayCast is used by GameRenderer#updateTargetedEntity to get the first entity within reach distance. The ray is never bounced off walls.

Another example, Item#rayCast is used by LilyPadItem to find the water source to place the lilypad on.

There aren't any rayTraces left, because there's nothing that actually follows a ray bouncing on a surface.

2020-08-17 15:19 UTC, Pyrofab approved these changes

2020-08-17 15:42 UTC, BoogieMonster1O1 approved these changes

2020-08-17 15:52 UTC, Earthcomputer approved these changes

2020-08-17 15:53 UTC, i509VCB approved these changes
After this is merged, some javadoc would be nice for RayCastContext and other misc stuff

2020-08-17 16:02 UTC, haykam821 approved these changes

2020-08-17 16:14 UTC, shartte approved these changes

2020-08-17 16:16 UTC, YanisBft approved these changes

2020-08-17 16:22 UTC, modmuss50 approved these changes

2020-08-17 17:20 UTC, liach approved these changes
I wonder if we can call these "hit" if they call it "hit result"

2020-08-17 18:01 UTC, dblsaiko approved these changes

2020-08-17 20:55 UTC, ramidzkh approved these changes

2020-08-18 13:32 UTC, LambdAurora approved these changes

2020-08-18 13:44 UTC, Mysterious-Dev approved these changes

2020-08-18 14:12 UTC, Player3324 approved these changes

2020-08-19 05:24 UTC, Runemoro approved these changes

2020-08-19 05:31 UTC, Runemoro commented
I agree, but I think it should be `castRay` rather than `rayCast`.

Look at the Wikipedia page, for example, which uses "cast ray" rather than "ray cast" as the verb:
> **cast**s primary **ray**s

2020-08-19 06:15 UTC, liach requested changes
Agreed with rune. Most "ray cast" should be replaced with "cast ray" except `getRayCastShape` `RayCastContext`

2020-08-19 08:26 UTC, Earthcomputer commented
Disagree. `castRay` doesn't sound as natural in English as `rayCast`. The Wikipedia page only makes sense because the "rays" is plural. Otherwise it needs an article, otherwise `rayCast` makes more sense.

2020-08-19 08:43 UTC, Scotsguy commented
I agree with Earth, additionally rayCast is simply used more often, based on my GitHub search of "castRay" returning 60k results vs "rayCast" returning 6 million

2020-08-19 09:17 UTC, Runemoro commented
> `castRay` doesn't sound as natural in English as `rayCast`

Compare:
 1. I am going to cast a ray.
 2. I am going to raycast.
 3. I am going to ray cast.

The first two work. The third looks wrong and is a grammar error.

> rayCast is simply used more often, based on my GitHub search of "castRay" returning 60k results vs "rayCast" returning 6 million

GitHub ignores capitalization, but if you look at the first 10 pages of results for "rayCast", you won't find a single instance of `rayCast`. They're all `raycast`.

2020-08-19 09:19 UTC, liach commented
Yeah `raycast` works better. So `getRaycastShape` `RaycastContext` etc

2020-08-19 09:27 UTC, Earthcomputer commented
:+1: for changing to lowercase raycast

2020-08-19 09:31 UTC, Scotsguy commented
You didnt actually say that the capitalization was the issue, I agree
I'll change it to lowercase when I'm back at a pc

2020-08-20 18:08 UTC, Runemoro approved these changes

2020-08-20 19:24 UTC, liach requested changes

2020-08-20 19:24 UTC, liach commented on mappings/net/minecraft/world/RayCastContext.mapping
> +CLASS net/minecraft/class_3959 net/minecraft/world/RayCastContext
Capitalization here too

2020-08-20 19:43 UTC, liach approved these changes

2020-08-23 21:03 UTC, modmuss50 approved these changes
Lets go with this, seems very well recieved.

2020-08-23 21:04 UTC, merged