Clean up javadoc on Identifier(String) constructor
asiekierka/MinecraftPOMF pull request #1723
Opened 2020-08-25 09:14 UTC by Leo40Git

This was done without Enigma! Since this is, quite literally, changing 2 COMMENT lines.

2020-08-25 09:32 UTC, YanisBft approved these changes

2020-08-25 16:30 UTC, liach requested changes
Should really move this to method docs

2020-08-25 17:37 UTC, liach commented
would be nice to note that this throws `InvalidIdentifierException` while `tryParse` returns null for invalid strings.

2020-08-25 17:54 UTC, liach approved these changes

2020-08-26 14:43 UTC, gegy1000 approved these changes

2020-08-27 08:20 UTC, merged