class_5423 -> LevelAccessor
asiekierka/MinecraftPOMF pull request #1724
Opened 2020-08-25 19:27 UTC by Mysterious-Dev

This PR complete class_5423 mappings.

2020-08-25 20:43 UTC, liach requested changes
The heck, this should really be registry accessible world. why does this have this anything to do with level
![concern](https://cdn.discordapp.com/emojis/707016186281590855.png?v=1)

2020-08-25 20:50 UTC, liach commented
uh no worries, you don't have to close... like you can wait for people to get a better name. Also see #1688

2020-08-25 20:54 UTC, liach commented
So for my concerns I will describe in detail:
1. There is nothing specific about level here. In yarn we only use level to refer to `level.dat` or related level properties content, unlike mojang who use it to refer to worlds
2. this class mainly offers access to dynamic registries, which is not conveyed in `LevelAccessor` name at all

2020-08-29 20:05 UTC, shartte commented on mappings/net/minecraft/world/level/LevelAccessor.mapping
> +	METHOD method_31081 getBiomeName (Lnet/minecraft/class_2338;)Ljava/util/Optional;
```suggestion
	METHOD method_31081 getBiomeKey (Lnet/minecraft/class_2338;)Ljava/util/Optional;
```

2020-09-07 08:01 UTC, modmuss50 commented on mappings/net/minecraft/world/level/LevelAccessor.mapping
> +CLASS net/minecraft/class_5423 net/minecraft/world/level/LevelAccessor
Yeah, this is just wrong, and sadly rasies my suspicions as to where you got this name from. For the sake of the yarn project I dont think I feel comfortable accepting this PR.

Thanks for understanding.

2020-09-07 08:01 UTC, closed without merging