[DRAFT] Backporting yarn 1.16.2 to 1.16.1
asiekierka/MinecraftPOMF pull request #1726
Opened 2020-08-27 14:00 UTC by LambdAurora

The backporting PRs are back.

This is highly WIP for now.

2020-08-27 15:24 UTC, NinjaPhenix commented on mappings/net/minecraft/client/realms/gui/screen/RealmsResetWorldScreen.mapping
> -		ARG 1 matrices
This should probably be re-added as this is a MatrixStack.

2020-08-27 15:31 UTC, NinjaPhenix commented on mappings/net/minecraft/client/render/SkyProperties.mapping
> -	FIELD field_24609 BY_DIMENSION_TYPE Lit/unimi/dsi/fastutil/objects/Object2ObjectMap;
This old name was correct at the time.

2020-08-27 15:35 UTC, LambdAurora commented on mappings/net/minecraft/client/render/SkyProperties.mapping
> -	FIELD field_24609 BY_DIMENSION_TYPE Lit/unimi/dsi/fastutil/objects/Object2ObjectMap;
Fixed

2020-08-27 18:10 UTC, NinjaPhenix commented
Looks good other than the few comments.

2020-08-29 08:59 UTC, YanisBft approved these changes

2020-08-29 10:00 UTC, NinjaPhenix approved these changes

2020-08-29 23:58 UTC, liach commented
Should be good. I just recall vanilla has mechanism change for tags or maybe some dimension/biome loading stuff; maybe some names there for 1.16.2 doesn't fit in 1.16.1.

2020-08-30 00:01 UTC, LambdAurora commented
Yes, that's why it's a draft for now, I still have to figure out what should not be backported.

2020-09-09 12:37 UTC, haykam821 requested changes

2020-09-09 12:37 UTC, haykam821 commented on mappings/net/minecraft/block/ChainBlock.mapping
> +	FIELD field_23986 Y_SHAPE Lnet/minecraft/class_265;
This is not applicable as chains only have one direction (on the Y axis) in 1.16.1.

2020-10-01 22:35 UTC, modmuss50 commented
Is this still WIP/Draft?

2020-10-01 22:37 UTC, haykam821 commented
Definitely do not merge this yet since the `field_23986` issue is unresolved.

2020-11-10 21:15 UTC, YanisBft commented
@LambdAurora do you still want to maintain this?

2020-11-11 17:00 UTC, closed without merging