JD for METAL material
asiekierka/MinecraftPOMF pull request #1749
Opened 2020-09-05 07:29 UTC by dexman545

METAL includes non-obvious things such a lapis and emerald blocks.

2020-09-05 08:47 UTC, YanisBft approved these changes

2020-09-05 08:47 UTC, YanisBft commented on mappings/net/minecraft/block/Material.mapping
> +		COMMENT Material for blocks metalic in nature, such as bells, iron (trap)doors, and cauldrons, as well as brewing stands and compressed ore blocks such as diamond, redstone, and lapis blocks.
```suggestion
		COMMENT Material for blocks metallic in nature, such as bells, iron (trap)doors, and cauldrons, as well as brewing stands and compressed ore blocks such as diamond, redstone, and lapis blocks.
```

2020-09-12 07:44 UTC, LambdAurora approved these changes

2020-09-12 12:08 UTC, NinjaPhenix approved these changes

2020-09-12 18:20 UTC, haykam821 requested changes

2020-09-12 18:20 UTC, haykam821 commented on mappings/net/minecraft/block/Material.mapping
> +		COMMENT Material for blocks metallic in nature, such as bells, iron (trap)doors, and cauldrons, as well as brewing stands and compressed ore blocks such as diamond, redstone, and lapis blocks.
```suggestion
		COMMENT Material for blocks metallic in nature, such as cauldrons, bells, iron doors, and iron trapdoors. It also includes non-obvious blocks such as brewing stands and compressed ore blocks, including diamond, redstone, and lapis blocks.
```

2020-09-13 14:41 UTC, haykam821 approved these changes

2020-09-13 16:23 UTC, merged