Some fixes
asiekierka/MinecraftPOMF pull request #1757
Opened 2020-09-12 05:58 UTC by YanisBft

Closes #1654 
Closes #1740 
Closes #1744 
Closes #1745 
Closes #1746

2020-09-12 12:01 UTC, NinjaPhenix approved these changes

2020-09-12 15:12 UTC, LambdAurora requested changes
I really disagree with the `luminance` rename, I think that `AbstractBlock$Settings#lightLevel` should be renamed to `luminance` instead.

`luminance` just describes the setting better when you look at the definition: "the intensity of light emitted from a surface per unit area in a given direction." in this case it's implicitly in "all direction". The definition just fits the variable very well and I prefer to use a word than to try to name a variable with multiple words.

I can understand people not being comfortable with `luminance` as it's a bit more uncommon than `lightLevel` but I think we should not lower the level of language used in yarn.

2020-09-12 15:25 UTC, LambdAurora approved these changes

2020-09-12 16:18 UTC, Juuxel approved these changes

2020-09-13 09:28 UTC, Prospector approved these changes

2020-09-13 16:19 UTC, shartte approved these changes

2020-09-17 21:54 UTC, franiscoder approved these changes

2020-09-18 03:58 UTC, BoogieMonster1O1 approved these changes

2020-09-18 12:02 UTC, modmuss50 approved these changes

2020-09-18 12:02 UTC, merged