Finish Option mapping
asiekierka/MinecraftPOMF pull request #1783
Opened 2020-10-08 08:30 UTC by enbrain

Finishes mapping `Option` class and a related class `Arm`.

2020-10-08 18:52 UTC, YanisBft approved these changes

2020-10-10 09:45 UTC, Juuxel requested changes

2020-10-10 09:45 UTC, Juuxel commented on mappings/net/minecraft/client/options/Option.mapping
> +		ARG 0 gameOption
```suggestion
		ARG 0 gameOptions
```

2020-10-12 17:44 UTC, Juuxel approved these changes

2020-10-13 07:57 UTC, modmuss50 approved these changes

2020-10-13 07:57 UTC, merged