Renamed BlockColors#getColor and some comments for ChunkSection
asiekierka/MinecraftPOMF pull request #1796
Opened 2020-10-12 16:20 UTC by biom4st3r

BlockColors#getColor(3 args) only gets the default or material color for the blockstate you supply which is misleading as it needs a world and blockpos.

BlockColors#getColor(4args) actually gets the proper colors for the blockstate depending on the location and world

2020-10-12 18:51 UTC, viktor40 approved these changes

2020-11-03 15:58 UTC, SuperCoder7979 requested changes

2020-11-03 15:58 UTC, SuperCoder7979 commented on mappings/net/minecraft/world/chunk/ChunkSection.mapping
> +	COMMENT a 16x16x16 subchunk
This doc should have more details imo, and should be capitalized.

2020-11-03 15:58 UTC, SuperCoder7979 commented on mappings/net/minecraft/world/chunk/WorldChunk.mapping
> +		COMMENT a ChunkSection[16] with 0 being Y0-Y15. If a ChunkSection is Empty it will be {@code null}
```suggestion
		COMMENT A ChunkSection[16]. If a ChunkSection is empty it will be {@code null}.
```

2021-01-09 18:40 UTC, YanisBft commented
This PR hasn't been updated for a while and is outdated. Please open a new one targetting the latest snapshot if still interested

2021-01-09 18:40 UTC, closed without merging