yarrn mappings
asiekierka/MinecraftPOMF pull request #1835
Opened 2020-11-05 00:32 UTC by TehcJS

arr

2020-11-05 07:10 UTC, i509VCB requested changes
Tehc you did put in effort but I believe that in future PRs you need to ask what is being done and pick something specific you can cover without stepping over others

2020-11-05 07:10 UTC, i509VCB commented on mappings/net/minecraft/block/Block.mapping
> +		ARG 1 state
This has been covered by atleast 3 other PRs. I would probably leave these params.

2020-11-05 07:10 UTC, i509VCB commented on mappings/net/minecraft/class_5493.mapping
> +CLASS net/minecraft/class_5493
A name would be nice for this.

2020-11-05 07:10 UTC, i509VCB commented on mappings/net/minecraft/class_5562.mapping
> +CLASS net/minecraft/class_5562
A name would be nice for this.

2020-11-05 07:10 UTC, i509VCB commented on mappings/net/minecraft/class_5584.mapping
> +CLASS net/minecraft/class_5584
A name would be nice for this.

2020-11-05 07:10 UTC, i509VCB commented on mappings/net/minecraft/class_5624.mapping
> +CLASS net/minecraft/class_5624
A name would be nice for this.

2020-11-05 07:10 UTC, i509VCB commented on mappings/net/minecraft/client/render/block/entity/BlockEntityRendererFactories.mapping
> +CLASS net/minecraft/class_5616 net/minecraft/client/render/block/entity/BlockEntityRendererFactories
Already covered in another PR?

2020-11-05 07:10 UTC, i509VCB commented on mappings/net/minecraft/entity/Entity.mapping
> +	CLASS class_5529 RemovalReason
Another thing that another pr has covered.

2020-11-08 06:18 UTC, TehcJS commented
lmao i deleted all of the stuff

2020-11-08 10:38 UTC, YanisBft commented
Your PR doesn't make any sense

2020-11-08 10:38 UTC, closed without merging