Fix javadoc warnings
asiekierka/MinecraftPOMF pull request #1884
Opened 2020-11-18 14:57 UTC by YanisBft

2020-11-18 19:32 UTC, Juuxel requested changes

2020-11-18 19:32 UTC, Juuxel commented on mappings/net/minecraft/util/Identifier.mapping
> +		COMMENT Prefer using the {@linkplain net.minecraft.util.Identifier#Identifier(java.lang.String, java.lang.String) Identifier(java.lang.String, java.lang.String)} constructor that takes the namespac
I think `link` would be better here than `linkplain` since the link text is code.

2020-11-19 01:18 UTC, SuperCoder7979 approved these changes

2020-11-20 15:22 UTC, Juuxel approved these changes

2020-11-20 17:30 UTC, modmuss50 approved these changes

2020-11-20 17:31 UTC, merged