ResourceManager documentation
asiekierka/MinecraftPOMF pull request #1898
Opened 2020-11-27 08:31 UTC by Sollace

Documented the behaviour of all the methods, as well as some of the gotchas.

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +		COMMENT to contain the requested entry, will throw a FileNotFoundException.
```suggestion
		COMMENT Starts by scanning each resource pack from highest priority to lowest. If no resource packs were found
		COMMENT to contain the requested entry, will throw a {@code FileNotFoundException}.
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +			COMMENT The resource identifier to search for
```suggestion
			COMMENT the resource identifier to search for
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +		COMMENT Gets a set of all namespaces offered by the resourcepacks loaded by this manager.
```suggestion
		COMMENT Gets a set of all namespaces offered by the resource packs loaded by this manager.
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +		COMMENT Scanning begins in {@linkplain startingPath} and each candidate file present under that directory
```suggestion
		COMMENT Scanning begins in {@code startingPath} and each candidate file present under that directory
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +		COMMENT @return The list matching identifiers
```suggestion
		COMMENT @return the list matching identifiers
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +			COMMENT The starting path to begin scanning from.
```suggestion
			COMMENT the starting path to begin scanning from
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +			COMMENT A predicate to determine whether a path should be included or not.
```suggestion
			COMMENT a predicate to determine whether a path should be included or not
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +		COMMENT list is what would be returned normally by {@link getResource}
```suggestion
		COMMENT list is what would be returned normally by {@link #getResource}
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +			COMMENT The resource identifier to search for
```suggestion
			COMMENT the resource identifier to search for
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +		COMMENT Starts by querying the resourcepack with the highest priority to lowest until it finds one that
```suggestion
		COMMENT Checks whether any of the currently-loaded resource packs contain an entry for the given id.
		COMMENT <br>
		COMMENT Starts by querying the resource pack with the highest priority to lowest until it finds one that
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +			COMMENT The resource identifier to search for
```suggestion
			COMMENT the resource identifier to search for
```

2020-11-27 10:54 UTC, YanisBft commented on mappings/net/minecraft/resource/ResourceManager.mapping
> +		COMMENT Gets a stream of loaded resourcepacks in increasing order of priority.
```suggestion
		COMMENT Gets a stream of loaded resource packs in increasing order of priority.
```

2020-11-27 20:06 UTC, YanisBft approved these changes

2020-11-28 17:25 UTC, Gegy approved these changes

2020-11-29 19:54 UTC, Juuxel requested changes
`<p>` should be used instead of `<br>`. (Contents themselves look fine)

2020-12-02 14:37 UTC, merged