Some command block gui and others mappings
asiekierka/MinecraftPOMF pull request #190
Opened 2018-11-07 21:30 UTC by marcin212

2018-11-07 22:24 UTC, asiekierka requested changes

2018-11-07 22:24 UTC, asiekierka commented on mappings/coi.mapping
> +	FIELD a minecraftGame Lclx;
Why not just "game"?

2018-11-07 22:24 UTC, asiekierka commented on mappings/net/minecraft/block/entity/BlockEntityEnderChest.mapping
> +	METHOD a animationProgress (F)F
getAnimationProgress if anything

2018-11-08 10:24 UTC, asiekierka commented on mappings/net/minecraft/client/gui/CommandBlockGui.mapping
> +	FIELD E isConditional Z
conditional/alwaysActive for fields; isConditional/isAlwaysActive for methods. Unless there's a reason not to do it this way.

2018-11-08 10:25 UTC, asiekierka commented on mappings/net/minecraft/client/gui/SimpleCommandBlockGui.mapping
> +	FIELD a consoleCommandTextField Lcmy;
Do we need the TextField/Button suffixes everywhere? It's a Gui class, most of the fields will be Gui elements... Something to think about, not necessarily correct.

2018-11-13 23:49 UTC, jamierocks approved these changes
Looks good :+1:

2018-11-14 22:19 UTC, merged