Some structure generation and random stuff
asiekierka/MinecraftPOMF pull request #191
Opened 2018-11-07 21:51 UTC by Matrix89

I don't think this should get merged now, I still need to deobf some names.

2018-11-07 22:26 UTC, asiekierka requested changes

2018-11-07 22:26 UTC, asiekierka commented on mappings/byy.mapping
> +	FIELD a x0 I
minX/maxX/... is the convention

2018-11-07 22:26 UTC, asiekierka commented on mappings/bzn.mapping
> +	METHOD b registerStructure (Ljava/lang/Class;Ljava/lang/String;)V
Structure or Feature? (I'm not sure)

2018-11-07 22:26 UTC, asiekierka commented on mappings/net/minecraft/sortme/structures/DesertTemple.mapping
> +CLASS bza net/minecraft/sortme/structures/DesertTemple
DesertTempleStructure or StructureDesertTemple (again, no clear standard yet). not DesertTemple alone

2018-11-08 07:54 UTC, Matrix89 commented on mappings/bzn.mapping
> +	METHOD b registerStructure (Ljava/lang/Class;Ljava/lang/String;)V
These classes don't inherit form Feature only generate it, so more like FeatureGenerator

2018-11-08 08:03 UTC, Matrix89 commented on mappings/net/minecraft/sortme/structures/DesertTemple.mapping
> +CLASS bza net/minecraft/sortme/structures/DesertTemple
Yep, named it only to keep track of it

2018-11-08 10:25 UTC, asiekierka commented on mappings/bzn.mapping
> +	METHOD b registerStructure (Ljava/lang/Class;Ljava/lang/String;)V
FeatureFactory?

2018-11-08 10:25 UTC, asiekierka commented on mappings/net/minecraft/sortme/structures/DesertTemple.mapping
> +CLASS bza net/minecraft/sortme/structures/DesertTemple
OK

2018-11-12 23:40 UTC, jamierocks requested changes

2018-11-12 23:40 UTC, jamierocks commented on mappings/bzn.mapping
> +	FIELD a logger Lorg/apache/logging/log4j/Logger;
These fields are static, they should be upper-case.

```java
    private static final Logger a = LogManager.getLogger();
    private static final Map<String, Class<? extends bzr>> b = Maps.newHashMap();
    private static final Map<Class<? extends bzr>, String> c = Maps.newHashMap();
    private static final Map<String, Class<? extends bzq>> d = Maps.newHashMap();
    private static final Map<Class<? extends bzq>, String> e = Maps.newHashMap();
```

2018-11-15 14:45 UTC, modmuss50 commented
Looks good, just need to fix that logger name.

I have a feeling this has a bit of overlap with #194

2018-11-15 17:07 UTC, asiekierka commented
-> 18w46a

2018-11-15 17:07 UTC, closed without merging