Mapped parts of ScreenHandler
asiekierka/MinecraftPOMF pull request #1910
Opened 2020-12-08 15:13 UTC by yitzy299

I have mapped a couple of methods in ScreenHandler and added names for a few variables. It's my first time contributing so would like to know if there is anything I should change.
method_30010 -> removeStack
Renamed a few auto-generated names in the methods in ScreenHandler
Mapped getStack()
Mapped totalSlots()

2020-12-08 19:16 UTC, SuperCoder7979 requested changes

2020-12-08 19:16 UTC, SuperCoder7979 commented on mappings/net/minecraft/screen/ScreenHandler.mapping
> +		ARG 1 slotNum
what does `Num` mean here? Is it the slot id or the slot count?

2020-12-08 19:16 UTC, SuperCoder7979 commented on mappings/net/minecraft/screen/ScreenHandler.mapping
> +		ARG 1 stackNum
ditto

2020-12-08 20:14 UTC, Juuxel requested changes

2020-12-08 20:14 UTC, Juuxel commented on mappings/net/minecraft/util/collection/DefaultedList.mapping
> +	METHOD get getStack (I)Ljava/lang/Object;
No. This is an override of a `List` method, and the name should **not** be touched. (There's also nothing about this class that's specific to slots.)

2020-12-08 20:14 UTC, Juuxel commented on mappings/net/minecraft/util/collection/DefaultedList.mapping
> +	METHOD set setSlots (ILjava/lang/Object;)Ljava/lang/Object;
Same here, this is from `List`.

2020-12-08 20:14 UTC, Juuxel commented on mappings/net/minecraft/util/collection/DefaultedList.mapping
> +	METHOD size totalSlots ()I
And this one is from `Collection`.

2020-12-08 21:07 UTC, yitzy299 commented
Let me know if there's anything else you would like me to clear up/fix. Thanks for your feedback :)

2020-12-09 09:08 UTC, Juuxel commented on mappings/net/minecraft/screen/ScreenHandler.mapping
> +		ARG 1 slotid
Hmm, is this the slot ID (`Slot.id`) or its index in `ScreenHandler.slots`?

2020-12-09 12:57 UTC, Gegy approved these changes

2020-12-09 13:00 UTC, Juuxel approved these changes

2020-12-09 13:18 UTC, YanisBft approved these changes

2020-12-09 13:21 UTC, merged