Some client javadoc
asiekierka/MinecraftPOMF pull request #1916
Opened 2020-12-15 09:10 UTC by i509VCB

This adds some javadoc which may be useful for beginners trying to understand what the MinecraftClient does, some javadoc related to screens and some javadoc related to the client connections on MinecraftClient and in ConnectScreen.

Also includes like 3 names, one of which clarifies what the client connection field in MinecraftClient is for.

2020-12-15 09:58 UTC, Juuxel requested changes

2020-12-15 09:58 UTC, Juuxel commented on mappings/net/minecraft/client/MinecraftClient.mapping
> +		COMMENT Opens a new screen. changing the current screen if needed.
```suggestion
		COMMENT Opens a new screen, changing the current screen if needed.
```

2020-12-15 09:58 UTC, Juuxel commented on mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
> +		COMMENT @see net.minecraft.client.MinecraftClient.integratedServerConnection
```suggestion
		COMMENT @see net.minecraft.client.MinecraftClient#integratedServerConnection
```

2020-12-15 10:06 UTC, Juuxel approved these changes

2020-12-16 04:19 UTC, SuperCoder7979 approved these changes

2020-12-16 20:25 UTC, YanisBft commented on mappings/net/minecraft/client/MinecraftClient.mapping
> +		COMMENT This field should only be used to getting the current screen.
```suggestion
		COMMENT This field should only be used to get the current screen.
```

2020-12-16 20:25 UTC, YanisBft commented on mappings/net/minecraft/client/gui/screen/ConnectScreen.mapping
> +	COMMENT The connection screen is used initiate a connection to a remote server.
```suggestion
	COMMENT The connection screen is used to initiate a connection to a remote server.
```

2020-12-16 20:25 UTC, YanisBft commented on mappings/net/minecraft/client/MinecraftClient.mapping
> +		COMMENT @see MinecraftClient.openScreen(Screen)
```suggestion
		COMMENT @see MinecraftClient#openScreen(Screen)
```

2020-12-16 20:26 UTC, YanisBft approved these changes

2020-12-17 09:07 UTC, merged