Rename FenceBlock.isFence -> isCompatibleFence
asiekierka/MinecraftPOMF pull request #1932
Opened 2020-12-23 07:12 UTC by alex5nader

This method is used for determining whether a fence can connect to another fence, and can return false even if the argument is a fence.

Please also backport this change to at least 1.16.4.

2020-12-23 07:28 UTC, haykam821 requested changes

2020-12-23 07:28 UTC, haykam821 commented on mappings/net/minecraft/block/FenceBlock.mapping
> +	METHOD method_26375 isCompatibleFence (Lnet/minecraft/class_2680;)Z
I'm not a fan of `isCompatibleFence` in particular, but it is more correct than `isFence`, just vague. Perhaps:

```suggestion
	METHOD method_26375 canConnectToFence (Lnet/minecraft/class_2680;)Z
```

2020-12-23 16:32 UTC, liach commented
You can click the apply changes button under [the suggestion](https://github.com/FabricMC/yarn/pull/1932#discussion_r547751800) if you agree with it.

2020-12-24 04:33 UTC, haykam821 approved these changes

2020-12-24 04:50 UTC, liach approved these changes

2020-12-24 11:09 UTC, YanisBft approved these changes

2020-12-24 12:05 UTC, modmuss50 approved these changes

2020-12-24 12:05 UTC, merged