21w03a stuff
asiekierka/MinecraftPOMF pull request #1964
Opened 2021-01-20 20:11 UTC by YanisBft

Mainly the obvious new classes, and also bring back a couple of params that were lost for some reasons

2021-01-20 20:20 UTC, liach approved these changes

2021-01-21 13:40 UTC, haykam821 requested changes

2021-01-21 13:40 UTC, haykam821 commented on mappings/net/minecraft/client/render/entity/ItemFrameEntityRenderer.mapping
> +	FIELD field_28463 GLOW_MAP_FRAME Lnet/minecraft/class_1091;
```suggestion
	FIELD field_28462 GLOW_FRAME Lnet/minecraft/class_1091;
	FIELD field_28463 MAP_GLOW_FRAME Lnet/minecraft/class_1091;
```

2021-01-22 12:25 UTC, SuperCoder7979 approved these changes

2021-01-22 12:43 UTC, haykam821 approved these changes

2021-01-22 13:36 UTC, merged