Glow Lichen mappings
asiekierka/MinecraftPOMF pull request #1970
Opened 2021-01-21 22:50 UTC by SuperCoder7979

This PR maps Glow Lichen as well as some new methods in DripstoneHelper.

2021-01-21 23:28 UTC, liach approved these changes

2021-01-22 08:12 UTC, Juuxel requested changes

2021-01-22 08:12 UTC, Juuxel commented on mappings/net/minecraft/world/gen/feature/GlowLichenFeature.mapping
> +	METHOD method_33393 exludeDirection (Lnet/minecraft/class_5780;Ljava/util/Random;Lnet/minecraft/class_2350;)Ljava/util/List;
```suggestion
	METHOD method_33393 excludeDirection (Lnet/minecraft/class_5780;Ljava/util/Random;Lnet/minecraft/class_2350;)Ljava/util/List;
```

2021-01-22 16:01 UTC, Gegy approved these changes

2021-01-22 17:39 UTC, merged