Two methods used on client player respawn
asiekierka/MinecraftPOMF pull request #2148
Opened 2021-03-15 09:29 UTC by DreenDex

2021-03-15 14:07 UTC, liach requested changes

2021-03-15 14:07 UTC, liach commented on mappings/net/minecraft/client/network/ClientPlayerEntity.mapping
> +	METHOD method_33689 onRespawnOrDimensionChange ()V
This is more like `init` or `setup` as it sets up the position, velcity, and pose of the player. Also it initializes health and sets deathTime to 0 which I think prevents the player from rendering as "dying".
```suggestion
	METHOD method_33689 init ()V
```

2021-03-15 14:31 UTC, liach approved these changes

2021-03-16 07:49 UTC, enbrain approved these changes

2021-03-16 20:33 UTC, modmuss50 approved these changes

2021-03-16 20:33 UTC, merged