Map a lot of util methods and stuff
asiekierka/MinecraftPOMF pull request #2172
Opened 2021-03-20 07:39 UTC by apple502j

Mapped many methods, fields, etc of util package.

2021-03-20 11:03 UTC, YanisBft approved these changes
Nice work!

2021-03-20 11:06 UTC, Juuxel requested changes

2021-03-20 11:06 UTC, Juuxel commented on mappings/net/minecraft/util/ChatUtil.mapping
> +	FIELD field_29204 LINEBREAK Ljava/util/regex/Pattern;
```suggestion
	FIELD field_29204 LINE_BREAK Ljava/util/regex/Pattern;
```

2021-03-20 23:22 UTC, SuperCoder7979 approved these changes

2021-03-21 06:47 UTC, liach approved these changes

2021-03-21 06:47 UTC, liach commented on mappings/net/minecraft/util/math/Direction.mapping
> +	FIELD field_29502 CODEC Lcom/mojang/serialization/Codec;
thanks a lot

2021-03-21 13:13 UTC, merged