Add package javadoc support
asiekierka/MinecraftPOMF pull request #2205
Opened 2021-03-29 13:51 UTC by liach

Closes #2035

This is surprisingly easy given modmuss's work on constants. So here we go!

For now, the package info files aren't compiled; they are purely used to generate javadoc. In addition, these javadocs aren't exported to mappings in any way.

(in fact, the compilePackageDocsJava task is totally unused, but you can run it; I guess I added it to explicitly state it is java 11 as opposed to java 8 for constants)

I added comments on their treatments if there is plan in the future to build binary for these package-infos (possible if we want annotations).

To demonstrate the new package docs, I added package info for `net.minecraft` and `net.minecraft.resource` packages. Imo this description of resource package tells you what you should check out, doesn't it?
![image](https://user-images.githubusercontent.com/7806504/112846714-f4eceb80-906b-11eb-82fc-0db35ddbd855.png)

Another tiny change is to make `checkMappings` depend on `mapIntermediaryJar`, since mapping check requires the intermediary jar to be present.

2021-03-29 13:52 UTC, liach commented
CC @LambdAurora for a review

2021-03-29 14:11 UTC, LambdAurora approved these changes

2021-03-29 14:28 UTC, Earthcomputer commented on src/packageDocs/java/net/minecraft/package-info.java
> + * <p>Unmapped classes goes into this package by default. This package additionally contains
```suggestion
 * <p>Unmapped classes go into this package by default. This package additionally contains

```

2021-03-29 14:56 UTC, Juuxel requested changes

2021-03-29 14:56 UTC, Juuxel commented on src/packageDocs/java/net/minecraft/resource/package-info.java
> + *     <td>Provides resource given an {@link net.minecraft.util.Identifier}.</td>
```suggestion
 *     <td>Provides a resource given an {@link net.minecraft.util.Identifier}.</td>

```

2021-03-30 21:39 UTC, modmuss50 approved these changes

2021-03-30 21:39 UTC, merged