World generation mappings for 21w13a
asiekierka/MinecraftPOMF pull request #2227
Opened 2021-03-31 20:44 UTC by mschae23

Some mappings for the world generation changes in 21w13a.

2021-04-01 04:21 UTC, liach commented
Conflicts with #2221

2021-04-02 17:59 UTC, SuperCoder7979 approved these changes

2021-04-02 22:58 UTC, liach commented
@mschae23 Mind resolve the merge conflicts?

2021-04-04 17:47 UTC, mschae23 commented
I resolved the merge conflict. Hopefully I did that correctly.

2021-04-04 18:09 UTC, liach approved these changes
imo valueprovider package can be renamed gen, as they generate numbers

2021-04-04 22:42 UTC, enbrain reviewed
Can you resolve conflicts between `net/minecraft/util/math/intprovider` and `net/minecraft/util/math/valueprovider`? This is something Git can't detect.

2021-04-04 22:52 UTC, YanisBft requested changes

2021-04-04 22:52 UTC, YanisBft commented on mappings/net/minecraft/util/math/valueprovider/IntProviderType.mapping
> +CLASS net/minecraft/class_6018 net/minecraft/util/math/valueprovider/IntProviderType
Same for this one

2021-04-04 22:52 UTC, YanisBft commented on mappings/net/minecraft/util/math/valueprovider/IntProvider.mapping
> +CLASS net/minecraft/class_6017 net/minecraft/util/math/valueprovider/IntProvider
Same for this one

2021-04-04 22:52 UTC, YanisBft commented on mappings/net/minecraft/util/math/valueprovider/UniformIntProvider.mapping
> +CLASS net/minecraft/class_6019 net/minecraft/util/math/valueprovider/UniformIntProvider
Same for this one

2021-04-04 22:52 UTC, YanisBft commented on mappings/net/minecraft/util/math/valueprovider/ConstantIntProvider.mapping
> +CLASS net/minecraft/class_6016 net/minecraft/util/math/valueprovider/ConstantIntProvider
This class was already mapped, in a different package tho

2021-04-04 22:52 UTC, YanisBft commented on mappings/net/minecraft/util/math/weight/WeightedList.mapping
> +CLASS net/minecraft/class_6012 net/minecraft/util/math/weight/WeightedList
There is already a class named WeightedList in nm/util/collection. What's the difference(s)?

2021-04-09 07:12 UTC, liach commented
Height provider and CarverConfig superseded by #2292; weighting covered by #2281, so sorry!

2021-04-09 07:12 UTC, closed without merging