Map GameTest methods
asiekierka/MinecraftPOMF pull request #2260
Opened 2021-04-02 19:54 UTC by apple502j

Mapped GameTest methods. Not so confident with the names, but think it's sort of good.

2021-04-02 20:03 UTC, liach commented on mappings/net/minecraft/test/GameTest.mapping
> +	METHOD method_36063 getElapsedMilliseconds ()J
Just fyi, we usually call milliseconds like "time" and ticks "ticks", so you can use `getElapsedTime` if you feel `getElapsedMilliseconds` is too long. No need to change though

2021-04-02 20:03 UTC, liach commented on mappings/net/minecraft/test/XMLReportingTestCompletionListener.mapping
> +CLASS net/minecraft/class_6307 net/minecraft/test/XMLReportingTestCompletionListener
Use `XmlReporting...` than `XMLReporting`.

2021-04-03 07:09 UTC, Juuxel commented on mappings/net/minecraft/test/TimedTaskRunner.mapping
> +	METHOD method_36079 createAndAddDurationless (Ljava/lang/Runnable;)Lnet/minecraft/class_4693;
Does this need `Durationless`? It looks like the duration variant just takes it as an extra parameter so they shouldn't conflict.

2021-04-03 07:11 UTC, Juuxel requested changes

2021-04-03 07:11 UTC, Juuxel commented on mappings/net/minecraft/test/TimedTask.mapping
> +		ARG 0 task
Same here about `Durationless`

2021-04-03 07:11 UTC, Juuxel commented on mappings/net/minecraft/test/TestServer.mapping
> +		ARG 2 ession
```suggestion
		ARG 2 session
```

2021-04-03 07:11 UTC, Juuxel commented on mappings/net/minecraft/test/TestFunctions.mapping
> +		ARG 1 class_
```suggestion
		ARG 1 clazz
```

2021-04-03 10:54 UTC, liach approved these changes

2021-04-03 11:27 UTC, Juuxel approved these changes

2021-04-03 12:28 UTC, YanisBft approved these changes

2021-04-03 12:30 UTC, merged