Remove unnecessary paragraph end tags from documentation
asiekierka/MinecraftPOMF pull request #2295
Opened 2021-04-07 22:08 UTC by haykam821

2021-04-08 00:26 UTC, liach approved these changes

2021-04-08 02:14 UTC, enbrain requested changes

2021-04-08 02:14 UTC, enbrain commented on mappings/net/minecraft/item/Item.mapping
> +		COMMENT
```suggestion
```

2021-04-11 10:42 UTC, YanisBft approved these changes

2021-04-11 11:06 UTC, enbrain approved these changes
Approving because the above comment doesn't affect the final output. I can make a follow-up PR if you want me to do so.

2021-04-11 12:08 UTC, merged