Partially map a weird long set
asiekierka/MinecraftPOMF pull request #2320
Opened 2021-04-11 00:43 UTC by liach

Names open to improvement

Signed-off-by: liach <liach@users.noreply.github.com>

2021-04-11 00:47 UTC, haykam821 requested changes

2021-04-11 00:47 UTC, haykam821 commented on mappings/net/minecraft/util/collection/HashBasedLongSet.mapping
> +		FIELD field_31721 FIRST_CHARACTERISITCS_OFFSET I
```suggestion
		FIELD field_31721 FIRST_CHARACTERISTICS_OFFSET I
```

2021-04-11 10:29 UTC, YanisBft commented on mappings/net/minecraft/util/collection/HashBasedLongSet.mapping
> +		ARG 2 f
```suggestion
		ARG 2 loadFactor
```

2021-04-11 10:29 UTC, YanisBft commented on mappings/net/minecraft/util/collection/HashBasedLongSet.mapping
> +			ARG 2 f
```suggestion
			ARG 2 loadFactor
```

2021-04-11 20:09 UTC, Sollace commented
I may have unintentionally mapped this class already. Heh. Feel free to use either one or pick the names you like to improve this PR. #2323

2021-04-11 20:52 UTC, Earthcomputer commented
At first glance, this class looks like it's supposed to contain values from `BlockPos.toLong()`. The `MathHelper.log2(60000000)` is very suspicious.

2021-04-11 21:20 UTC, Sollace commented
@Earthcomputer I believe it's related to LevelPropagator, as that's the only place I can find which uses this type's parent class.

```
            this.pendingIdUpdatesByLevel[l] = new LongLinkedOpenHashSet(expectedLevelSize, 0.5f){
                @Override
                protected void rehash(int newN) {
                    if (newN > j) {
                        super.rehash(newN);
                    }
                }
            };
```
Likely implemented for use here, but left out for some unknown reason.

2021-04-12 12:40 UTC, liach commented
Closing in favor of #2323

2021-04-12 12:40 UTC, closed without merging