Client resource reload stuff
asiekierka/MinecraftPOMF pull request #2381
Opened 2021-05-05 18:31 UTC by apple502j

todo: better naming and packages?

2021-05-06 09:03 UTC, enbrain requested changes

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +			ARG 3 reason
```suggestion
		FIELD field_33705 name Ljava/lang/String;
		METHOD <init> (Ljava/lang/String;ILjava/lang/String;)V
			ARG 3 name
```
It's confusing to have code like `reloadReason.reason`.

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +	FIELD field_33700 reloadNumber I
```suggestion
	FIELD field_33700 reloadCount I
```
`number` is too abstract imo.

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +		ARG 1 reloadReason
```suggestion
	METHOD method_36563 reload (Lnet/minecraft/class_6360$class_6362;Ljava/util/List;)V
		ARG 1 reason
```

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +		FIELD field_33707 reloadReason Lnet/minecraft/class_6360$class_6362;
```suggestion
		FIELD field_33707 reason Lnet/minecraft/class_6360$class_6362;
```

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +			ARG 1 reloadReason
```suggestion
			ARG 1 reason
```

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +	METHOD method_36562 setFinished ()V
```suggestion
	METHOD method_36562 finish ()V
```

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +	CLASS class_6363 ReloadEntry
What about `ReloadState`? `finished` field suggests it's a sort of state.
```suggestion
	CLASS class_6363 ReloadState
```

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +	FIELD field_33699 reload Lnet/minecraft/class_6360$class_6363;
```suggestion
	FIELD field_33699 reloadState Lnet/minecraft/class_6360$class_6363;
```

2021-05-06 09:03 UTC, enbrain commented on mappings/net/minecraft/client/ReloadLogger.mapping
> +CLASS net/minecraft/class_6360 net/minecraft/client/ReloadLogger
Since this is specifically for resource pack, what about `ResourceReloadLogger`?

2021-05-07 12:09 UTC, enbrain approved these changes

2021-05-12 12:58 UTC, sfPlayer1 approved these changes

2021-05-12 12:58 UTC, merged