Map util stuff
asiekierka/MinecraftPOMF pull request #2386
Opened 2021-05-07 11:42 UTC by apple502j

Question: does renaming `BooleanBiFunction.SAME` to `XNOR` make sense?

2021-05-07 12:04 UTC, liach commented
> 
> 
> Question: does renaming `BooleanBiFunction.SAME` to `XNOR` make sense?

See https://github.com/FabricMC/yarn/issues/1565#issuecomment-655853243. This `BooleanBiFunction` class is like a rule for combination for voxel shapes.

2021-05-07 12:09 UTC, sfPlayer1 commented
IMO XNOR etc are too abstract and don't really make sense for boolean operands (not bit vectors)

2021-05-07 12:10 UTC, liach requested changes

2021-05-07 12:10 UTC, liach commented on mappings/net/minecraft/util/UserCache.mapping
> +	METHOD method_30165 serialize (Lnet/minecraft/class_3312$class_3313;Ljava/text/DateFormat;)Lcom/google/gson/JsonElement;
We use toJson/fromJson for such static methods; see https://github.com/FabricMC/yarn/blob/21w18a/CONVENTIONS.md#serialization

2021-05-07 12:10 UTC, liach commented on mappings/net/minecraft/util/snooper/Snooper.mapping
> +	METHOD method_35032 addJVMFlags ()V
```suggestion
	METHOD method_35032 addJvmFlags ()V
```

2021-05-07 12:27 UTC, Player3324 commented
BooleanBiFunction btw has a few potential improvements (probably better for a separate PR/issue?):
- AND -> BOTH
- OR -> ANY
- NOT_OR -> NEITHER
- NOT_AND -> NOT_BOTH
- NOT_SAME -> DIFFERENT
- CAUSES -> NOT_ONLY_FIRST
- CAUSED_BY -> NOT_ONLY_SECOND

The first/second field names kind of conflict with a/b param naming in this PR

2021-05-07 13:21 UTC, apple502j commented on mappings/net/minecraft/util/UserCache.mapping
> +	METHOD method_30165 serialize (Lnet/minecraft/class_3312$class_3313;Ljava/text/DateFormat;)Lcom/google/gson/JsonElement;
It doesn't "create an object of the method owner's type" though; it takes/returns `UserCache.Entry`, not UserCache

2021-05-07 14:44 UTC, enbrain commented on mappings/net/minecraft/util/snooper/Snooper.mapping
> +	FIELD field_29959 SNOOPER_VERSION I
```suggestion
	FIELD field_29957 BASE_URL Ljava/lang/String;
	FIELD field_29959 VERSION I
```
I think `SNOOPER` is redundant as it's obvious from the enclosing class name.

2021-05-07 14:49 UTC, liach commented on mappings/net/minecraft/util/UserCache.mapping
> +	METHOD method_30165 serialize (Lnet/minecraft/class_3312$class_3313;Ljava/text/DateFormat;)Lcom/google/gson/JsonElement;
Then `entryToJson` `entryFromJson` are still more specific and concise than `deserialize` `serialize`

2021-05-08 02:52 UTC, enbrain approved these changes

2021-05-08 03:38 UTC, liach approved these changes

2021-05-08 03:39 UTC, merged