Map button lambda parameters
asiekierka/MinecraftPOMF pull request #2416
Opened 2021-05-19 21:49 UTC by enbrain

2021-05-19 21:53 UTC, haykam821 requested changes
Hopefully something similar is done for record codec `instance` parameters.

2021-05-19 21:53 UTC, haykam821 commented on mappings/net/minecraft/client/realms/gui/screen/RealmsSlotOptionsScreen.mapping
> +		ARG 2 spawnNPCs
```suggestion
		ARG 2 spawnNpcs
```

This is currently inconsistent between `ServerPropertiesHandler` (`spawnNpcs`) and `RealmsSlotOptionsScreen` (`spawnNPCs`), so a change should be made later to fix that.

2021-05-19 22:02 UTC, haykam821 approved these changes

2021-05-20 01:13 UTC, liach approved these changes

2021-05-20 10:06 UTC, YanisBft approved these changes

2021-05-20 14:21 UTC, merged

2021-05-21 03:00 UTC, haykam821 commented on mappings/net/minecraft/client/realms/gui/screen/RealmsSlotOptionsScreen.mapping
> +		ARG 2 spawnNPCs
The other instances of this issue have been fixed in pull request #2423.