Map some shared constants
asiekierka/MinecraftPOMF pull request #2447
Opened 2021-05-29 22:02 UTC by ByMartrixx

Once 1.17 is out I'll be able to check if `field_29709` is whether the version is a development one, and if `field_29735` is the target release protocol version

2021-05-30 02:23 UTC, liach approved these changes

2021-05-31 14:30 UTC, Juuxel approved these changes

2021-05-31 14:44 UTC, haykam821 requested changes

2021-05-31 14:44 UTC, haykam821 commented on mappings/net/minecraft/SharedConstants.mapping
> +	FIELD field_29704 TICKS_PER_INGAME_DAY I
```suggestion
	FIELD field_29704 TICKS_PER_IN_GAME_DAY I
```

2021-05-31 16:18 UTC, merged