Map TradeOffers constants
asiekierka/MinecraftPOMF pull request #2449
Opened 2021-05-29 22:07 UTC by ByMartrixx

I got some of the names using data from the Minecraft wiki [Trading page](https://minecraft.fandom.com/wiki/Trading)

2021-05-30 02:22 UTC, liach requested changes

2021-05-30 02:22 UTC, liach commented on mappings/net/minecraft/village/TradeOffers.mapping
> +	FIELD field_30628 PRICE_MULTIPLIER_HIGH F
```suggestion
	FIELD field_30616 COMMON_MAX_USES I
	FIELD field_30617 RARE_MAX_USES I
	FIELD field_30618 NOVICE_SELL_XP I
	FIELD field_30619 NOVICE_BUY_XP I
	FIELD field_30620 APPRENTICE_SELL_XP I
	FIELD field_30621 APPRENTICE_BUY_XP I
	FIELD field_30622 JOURNEYMAN_SELL_XP I
	FIELD field_30623 JOURNEYMAN_BUY_XP I
	FIELD field_30624 EXPERT_SELL_XP I
	FIELD field_30625 EXPERT_BUY_XP I
	FIELD field_30626 MASTER_TRADE_XP I
	FIELD field_30627 LOW_PRICE_MULTIPLIER F
	FIELD field_30628 HIGH_PRICE_MULTIPLIER F
```
Use the word order as in written or spoken language, like "master's trade xp" becomes `MASTER_TRADE_XP` than `XP_MASTER_TRADE`

2021-05-30 04:21 UTC, liach approved these changes

2021-05-31 16:19 UTC, modmuss50 approved these changes

2021-05-31 16:19 UTC, merged