Map InGameHud and its inner class
asiekierka/MinecraftPOMF pull request #2450
Opened 2021-05-30 05:41 UTC by enbrain

2021-05-30 06:47 UTC, liach approved these changes

2021-05-30 06:47 UTC, liach commented on mappings/net/minecraft/client/gui/hud/InGameHud.mapping
> +	COMMENT MinecraftClient.getInstance().inGameHud}.
```suggestion
	COMMENT <p>The current instance used by the client can be obtained by {@linkplain
	COMMENT MinecraftClient#inGameHud MinecraftClient.getInstance().inGameHud}.
```
Makes this a link that goes to the actual field.

2021-05-31 14:48 UTC, haykam821 requested changes

2021-05-31 14:48 UTC, haykam821 commented on mappings/net/minecraft/client/gui/hud/InGameHud.mapping
> +		COMMENT Renders the armor, health, hunger and oxygen bars.
```suggestion
		COMMENT Renders the armor, health, air, and hunger bars.
```

2021-05-31 14:48 UTC, haykam821 commented on mappings/net/minecraft/client/gui/hud/InGameHud.mapping
> +		ARG 11 blinking
Some documentation for these arguments would be better.

2021-05-31 14:48 UTC, haykam821 commented on mappings/net/minecraft/client/gui/hud/InGameHud.mapping
> +		ARG 7 halfHeart
Some documentation for these arguments would be better.

2021-06-01 15:43 UTC, modmuss50 approved these changes

2021-06-01 15:43 UTC, merged