Fixes some bad names and add new docs.
asiekierka/MinecraftPOMF pull request #2465
Opened 2021-06-03 22:45 UTC by LambdAurora

Fixed the badly named `GoToOwnerAndPurrGoal` which is doing something else entirely in reality.
Renamed sleeping with owner methods in `CatEntity` as an owner is not always present and is just putting the cat into a sleeping pose.
And added some javadocs too.

2021-06-03 23:28 UTC, ByMartrixx approved these changes

2021-06-04 00:48 UTC, liach commented on mappings/net/minecraft/entity/passive/CatEntity.mapping
> +		COMMENT @return {@code true} if this cat is in a sleeping pose, otherwise {@code false}
```suggestion
		COMMENT {@return whether this cat is in a sleeping pose}
```

2021-06-04 04:10 UTC, haykam821 requested changes
Other than the missing inline return tag previously noted, this pull request looks good.

2021-06-04 04:11 UTC, haykam821 commented on mappings/net/minecraft/entity/passive/CatEntity.mapping
> +		COMMENT @return {@code true} if this cat is in a sleeping pose, otherwise {@code false}
Relates to #2454

2021-06-04 07:13 UTC, YanisBft approved these changes

2021-06-04 09:03 UTC, liach approved these changes

2021-06-04 10:52 UTC, Juuxel requested changes

2021-06-04 10:52 UTC, Juuxel commented on mappings/net/minecraft/entity/passive/CatEntity.mapping
> +		COMMENT The british shorthair cat type, whose value is {@value}.
```suggestion
		COMMENT The British shorthair cat type, whose value is {@value}.
```

2021-06-04 10:52 UTC, Juuxel commented on mappings/net/minecraft/entity/passive/CatEntity.mapping
> +		COMMENT The persian cat type, whose value is {@value}.
```suggestion
		COMMENT The Persian cat type, whose value is {@value}.
```

2021-06-04 10:52 UTC, Juuxel commented on mappings/net/minecraft/entity/passive/CatEntity.mapping
> +		COMMENT The siamese cat type, whose value is {@value}.
```suggestion
		COMMENT The Siamese cat type, whose value is {@value}.
```

2021-06-04 10:55 UTC, Juuxel approved these changes

2021-06-04 10:57 UTC, merged