FollowTargetGoal -> TrackClosestTargetGoal
asiekierka/MinecraftPOMF pull request #2561
Opened 2021-07-05 01:47 UTC by frqnny

Closes #2560, see what draylar put there

2021-07-05 01:58 UTC, liach commented
Imo nearest isn't the principal feature of this goal. The distinguishing feature is this is that the goal finds targets by an entity class.

2021-07-05 02:04 UTC, liach requested changes
You didn't check the subclasses. Definitely need to rename `DisableableFollowTargetGoal` and `FollowTargetIfTamedGoal` if this is rename is done.

Now I think `ActiveTargetGoal` (find target actively) may be better, as this is what hostile mobs use to target players

2021-07-05 02:20 UTC, frqnny commented
I went ahead and renamed some sub classes. For entity-specific ones like Spider, I just wrote it "TargetGoal" since it would be "SpiderEntity.TargetGoal"

2021-07-05 02:24 UTC, liach commented on mappings/net/minecraft/entity/ai/goal/EnableableActiveTargetGoal.mapping
> +CLASS net/minecraft/class_3760 net/minecraft/entity/ai/goal/EnableableActiveTargetGoal
How about `Toggleable` if "enableable" and "disableable" appear too cursed

2021-07-05 02:24 UTC, liach commented on mappings/net/minecraft/entity/ai/goal/TameableTargetGoal.mapping
> +CLASS net/minecraft/class_1404 net/minecraft/entity/ai/goal/TameableTargetGoal
![image](https://user-images.githubusercontent.com/7806504/124409435-e880ca80-dd0d-11eb-9d2e-9cc0b3ded9b8.png)
Should be `UntamedActiveTargetGoal`

2021-07-05 02:24 UTC, liach commented on mappings/net/minecraft/entity/passive/PolarBearEntity.mapping
> +	CLASS class_1457 PlayerTargetGoal
This one is like targeting to protect baby (when there is baby close around) while the other one is general "anger at" target goal

2021-07-05 02:33 UTC, liach approved these changes
Thank you for these names :heart:

2021-08-31 22:43 UTC, liach commented
@modmuss50 How feasible is this bug-fixing one? Though this may affect mods using the old ai system (assuming they aren't using brains), these renames do accuracy describe the actual roles of these goals.

2021-09-01 11:23 UTC, modmuss50 commented
I dont think these classes are used that widely, so changing them in 1.17 seems fine to me. Does anyone have any objections to this?

2021-09-12 22:03 UTC, modmuss50 approved these changes

2021-09-13 00:30 UTC, YanisBft approved these changes

2021-09-14 20:22 UTC, merged