Added several strings related to chat handling.
asiekierka/MinecraftPOMF pull request #271
Opened 2018-12-12 04:27 UTC by MasterEric

Look at my teeny little pull request and tremble in terror.

Since I was working on these lines in order to use a Mixin here, I decided to go ahead and map the lines myself, to make development a bit easier.

2018-12-12 05:25 UTC, kashike requested changes

2018-12-12 05:25 UTC, kashike commented on mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
> +	METHOD b disconnectWithReason (Ljb;)V
`WithReason` is not necessary in the name.

2018-12-12 14:51 UTC, asiekierka commented
As it's tiny and has not been resolved in time, we'll take care of it manually post-update.

2018-12-13 01:09 UTC, MasterEric commented
Redid these changse for the new update in #282.

2018-12-13 01:09 UTC, closed without merging