21w41a brand
asiekierka/MinecraftPOMF pull request #2748
Opened 2021-10-13 17:39 UTC by apple502j

2021-10-13 18:02 UTC, Juuxel requested changes

2021-10-13 18:02 UTC, Juuxel commented on mappings/net/minecraft/util/GameBrand.mapping
> +		ARG 3 class_
```suggestion
		ARG 3 clazz
```

2021-10-13 18:35 UTC, modmuss50 approved these changes

2021-10-13 18:37 UTC, enbrain commented on mappings/net/minecraft/client/MinecraftClient.mapping
> +		COMMENT <p>The brand checker checks the brand and whether the class is signed or not.
This should be documented in `class_6683` imo.

2021-10-13 18:37 UTC, enbrain commented on mappings/net/minecraft/util/GameBrand.mapping
> +CLASS net/minecraft/class_6683 net/minecraft/util/GameBrand
Maybe `ModStatus`? I think the word `brand` is used to refer to things like "vanilla" or "fabric". This class is more of modded or not.

2021-10-13 18:37 UTC, enbrain commented on mappings/net/minecraft/util/GameBrand.mapping
> +	CLASS class_6684 ModConfidence
Just `Confidence` if we choose `ModStatus`.

2021-10-13 18:37 UTC, enbrain commented on mappings/net/minecraft/util/GameBrand.mapping
> +	METHOD method_39031 create (Ljava/lang/String;Ljava/util/function/Supplier;Ljava/lang/String;Ljava/lang/Class;)Lnet/minecraft/class_6683;
Maybe `check` since the checking logic is done in this method.
```suggestion
	METHOD method_39031 check (Ljava/lang/String;Ljava/util/function/Supplier;Ljava/lang/String;Ljava/lang/Class;)Lnet/minecraft/class_6683;
```

2021-10-13 20:24 UTC, enbrain commented on mappings/net/minecraft/util/ModStatus.mapping
> +	COMMENT <p>This checks the brand and whether the class is signed or not.
```suggestion
		COMMENT {@return the modification status determined by the brand and whether the
		COMMENT class is signed or not}
```
This also fixes the build error.

2021-10-13 20:24 UTC, enbrain commented on mappings/net/minecraft/util/ModStatus.mapping
> +	METHOD method_39032 getDescription ()Ljava/lang/String;
```suggestion
	METHOD method_39032 getFullDescription ()Ljava/lang/String;
```
To avoid confusion with the record's `description` method.

2021-10-13 20:24 UTC, enbrain commented on mappings/net/minecraft/util/ModStatus.mapping
> +		COMMENT {@return the result of comparing this brand and {@code brand} by their confidence}
Maybe `combine` since this method concatenates the two descriptions.
```suggestion
	METHOD method_39030 combine (Lnet/minecraft/class_6683;)Lnet/minecraft/class_6683;
		COMMENT {@return the combined modification status with the higher confidence}
```

2021-10-13 22:08 UTC, liach commented on mappings/net/minecraft/util/ModStatus.mapping
> +	METHOD method_39032 getDescription ()Ljava/lang/String;
```suggestion
	METHOD method_39032 getMessage ()Ljava/lang/String;
```

2021-10-14 04:11 UTC, enbrain approved these changes

2021-10-14 04:34 UTC, liach approved these changes

2021-10-15 15:22 UTC, merged