21w41a server world
asiekierka/MinecraftPOMF pull request #2756
Opened 2021-10-14 14:57 UTC by apple502j

Resolves #2755

2021-10-15 16:57 UTC, enbrain requested changes

2021-10-15 16:57 UTC, enbrain commented on mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
> +  	METHOD method_31413 addEntitiesFromNbt (Lnet/minecraft/class_3218;Ljava/util/List;)V
```suggestion
	METHOD method_31413 addEntitiesFromNbt (Lnet/minecraft/class_3218;Ljava/util/List;)V
```

2021-10-15 22:49 UTC, Juuxel requested changes

2021-10-15 22:49 UTC, Juuxel commented on mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
> +	FIELD field_29671 PROTOCHUNK B
```suggestion
	FIELD field_29671 PROTO_CHUNK B
```

2021-10-15 22:49 UTC, Juuxel commented on mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
> +	FIELD field_29673 LEVELCHUNK B
```suggestion
	FIELD field_29673 LEVEL_CHUNK B
```

2021-10-16 13:24 UTC, Juuxel approved these changes

2021-10-16 21:07 UTC, enbrain commented on mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
> +	METHOD method_37905 isInDistanceEdge (IIIII)Z
Is this whether the position is on a circle’s circumference? If so,
```suggestion
	METHOD method_37905 isOnDistanceEdge (IIIII)Z
```

I'd probably name it `isOnBorder` but `distanceEdge` is already used I guess.

2021-10-16 21:07 UTC, enbrain commented on mappings/net/minecraft/server/world/ThreadedAnvilChunkStorage.mapping
> +	METHOD method_37906 isInDistanceEdge (Lnet/minecraft/class_1923;Lnet/minecraft/class_3222;ZI)Z
```suggestion
	METHOD method_37906 isOnDistanceEdge (Lnet/minecraft/class_1923;Lnet/minecraft/class_3222;ZI)Z
```

2021-10-17 09:07 UTC, enbrain approved these changes

2021-10-17 13:49 UTC, merged