21w41a monster XP fields
asiekierka/MinecraftPOMF pull request #2757
Opened 2021-10-15 15:24 UTC by apple502j

Not entirely sure about the meaning, but I don't think there are that much constants with value 0, 3, 5, 10, 20 and 50.

2021-10-15 15:44 UTC, liach commented
I recall monsters have xp bonus for extra armors. Also seems baby monsters drop 11 xp, which appears not in this list.

2021-10-17 04:22 UTC, enbrain approved these changes

2021-10-17 04:22 UTC, enbrain commented on mappings/net/minecraft/entity/mob/Monster.mapping
> +	FIELD field_30469 WITHER_XP I
Maybe document that these values are used for `MobEntity#experiencePoints`. A link to this class might be useful as well.

2021-10-17 20:54 UTC, enbrain requested changes

2021-10-17 20:54 UTC, enbrain commented on mappings/net/minecraft/entity/mob/Monster.mapping
> +	COMMENT {@linkplain net.minecraft.entity.boss.WitherEntity withers}.
```suggestion
	FIELD field_30464 ZERO_XP I
		COMMENT @apiNote This is used for mobs that do not drop experience.
	FIELD field_30465 SMALL_MONSTER_XP I
		COMMENT @apiNote This is used for monsters such as
		COMMENT {@linkplain EndermiteEntity endermites} and
		COMMENT {@linkplain VexEntity vexes}.
	FIELD field_30466 NORMAL_MONSTER_XP I
		COMMENT @apiNote This is used for most of the monsters, such as
		COMMENT {@linkplain ZombieEntity zombies} and
		COMMENT {@linkplain SkeletonEntity skeletons}.
	FIELD field_30467 STRONG_MONSTER_XP I
		COMMENT @apiNote This is used for monsters such as
		COMMENT {@linkplain BlazeEntity blazes} and
		COMMENT {@linkplain GuardianEntity guardians}.
	FIELD field_30468 STRONGER_MONSTER_XP I
		COMMENT @apiNote This is used for {@linkplain PiglinBruteEntity piglin brutes}
		COMMENT and {@linkplain RavagerEntity ravagers}.
	FIELD field_30469 WITHER_XP I
		COMMENT @apiNote This is used for
		COMMENT {@linkplain net.minecraft.entity.boss.WitherEntity withers}.
```

2021-10-17 20:59 UTC, liach commented on mappings/net/minecraft/entity/mob/Monster.mapping
> +	COMMENT This interface contains constants to be used for
I recall the interface is mainly a marker for hostile mobs (monsters) than just a constant holder.

2021-10-18 02:49 UTC, enbrain commented on mappings/net/minecraft/entity/mob/Monster.mapping
> +	COMMENT This interface contains constants to be used for
Yes. That's why I didn't suggest a rename to `MonsterConstants`. Additional documentation wouldn't hurt though.

2021-10-18 02:49 UTC, enbrain approved these changes

2021-10-18 03:09 UTC, liach commented on mappings/net/minecraft/entity/mob/Monster.mapping
> +	COMMENT This interface contains constants to be used for
```suggestion
	COMMENT This interface marks that an entity class belongs to monsters, including
	COMMENT hostile mobs like zombies. It also contains constants to be used for
```

2021-10-18 03:09 UTC, liach commented on mappings/net/minecraft/entity/mob/Monster.mapping
> +	COMMENT setting {@link MobEntity#experiencePoints}.
```suggestion
	COMMENT setting {@link MobEntity#experiencePoints}.
	COMMENT
	COMMENT @see net.minecraft.entity.SpawnGroup#MONSTER
```

2021-10-18 19:56 UTC, liach approved these changes

2021-10-18 20:16 UTC, Juuxel approved these changes

2021-10-19 16:16 UTC, YanisBft approved these changes

2021-10-19 16:17 UTC, merged