Map GUI stuff
asiekierka/MinecraftPOMF pull request #2762
Opened 2021-10-15 17:35 UTC by enbrain

2021-10-15 19:04 UTC, Juuxel requested changes

2021-10-15 19:04 UTC, Juuxel commented on mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
> +		COMMENT The index of the most-left character that is rendered on a screen.
```suggestion
		COMMENT The index of the leftmost character that is rendered on a screen.
```
Sounds a bit more natural imo

2021-10-15 19:04 UTC, Juuxel commented on mappings/net/minecraft/client/gui/widget/TextFieldWidget.mapping
> +	FIELD field_32199 HORIZONTAL_CURSOR_CHARACTER Ljava/lang/String;
```suggestion
	FIELD field_32199 HORIZONTAL_CURSOR Ljava/lang/String;
```

2021-10-15 19:11 UTC, Juuxel approved these changes

2021-10-16 13:01 UTC, modmuss50 approved these changes

2021-10-16 13:01 UTC, merged