Add mapping for new spawn selection algorithm
asiekierka/MinecraftPOMF pull request #2778
Opened 2021-10-21 00:17 UTC by sarunint

2021-10-21 00:33 UTC, enbrain requested changes

2021-10-21 00:33 UTC, enbrain commented on mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
> +		METHOD sample sample (III)Lnet/minecraft/class_6544$class_6553;
```suggestion
		METHOD sample (III)Lnet/minecraft/class_6544$class_6553;
```
We don't map non-obfuscated methods.

2021-10-21 00:33 UTC, enbrain commented on mappings/net/minecraft/world/biome/source/util/MultiNoiseUtil.mapping
> +			ARG 3 posZ
```suggestion
			ARG 2 x
			ARG 3 z
```

2021-10-21 01:21 UTC, sarunint commented
Suggested fixes applied

2021-10-21 01:23 UTC, enbrain approved these changes

2021-10-21 18:55 UTC, YanisBft approved these changes

2021-10-22 10:30 UTC, modmuss50 approved these changes

2021-10-22 10:30 UTC, merged