Add docs for FuzzyTargetting and NoPenaltyTargetting
asiekierka/MinecraftPOMF pull request #2783
Opened 2021-10-23 10:26 UTC by Sollace

What's this? A _pull request_!?

Mainly adding documentation and changed two method names to better describe what they do.

`NoPenaltyTargetting#find` -> `NoPenaltyTargetting#findTo`
`NoPenaltyTargetting#find` -> `NoPenaltyTargetting#findFrom`

These both find positions leading to and away from a given start/end position.

`findFrom` for instance is used in (and only in) `FleeEntityGoal` (circa 1.17):

```
Vec3d vec3d = NoPenaltyTargeting.findFrom(this.mob, 16, 7, this.targetEntity.getPos());
```

2021-10-23 18:40 UTC, Juuxel requested changes
There are still some names not matching the conventions.

Also, avoiding Filament's check for parameter formatting and still having multiple sentences in them is sketchy. I'd format those in some other way (for example: `the ... range (how far the point...)`).

2021-10-23 18:40 UTC, Juuxel commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +		COMMENT Paths to a random reachable position with positive path-finding favourability.
```suggestion
		COMMENT Paths to a random reachable position with positive path-finding favorability.
```
Yarn uses simplified English :pensive:

2021-10-23 18:40 UTC, Juuxel commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +	COMMENT if applicable, and will be suitably randomised within that contraint.
```suggestion
	COMMENT if applicable, and will be suitably randomized within that contraint.
```
Same here.

2021-10-23 18:40 UTC, Juuxel commented on mappings/net/minecraft/entity/ai/NoPenaltyTargeting.mapping
> +		COMMENT @return The chosen end position or null if no valid positions could be found.
```suggestion
		COMMENT @return the chosen end position or null if no valid positions could be found
```
The same style rules apply to `@return` and `@param` (although not checked by Filament for returns)

2021-10-23 18:40 UTC, Juuxel commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +	COMMENT Positions are chosen to stay within range of the entity's chosen {@link net.minecraft.entity.mob.MobEntity#getPositionTarget() position target}
```suggestion
	COMMENT Positions are chosen to stay within range of the entity's chosen {@linkplain net.minecraft.entity.mob.MobEntity#getPositionTarget() position target}
```

2021-10-23 18:40 UTC, Juuxel commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +		COMMENT @return The chosen position or null if none could be found.
```suggestion
		COMMENT @return the chosen position or null if none could be found
```

2021-10-23 18:40 UTC, Juuxel commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +		COMMENT @return The chosen position or null if none could be found.
```suggestion
		COMMENT @return the chosen position or null if none could be found
```

2021-10-23 18:59 UTC, Sollace commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +		COMMENT Paths to a random reachable position with positive path-finding favourability.
Oof. I remembered for "armor" but my default is correct English. Sorry.

2021-10-24 01:07 UTC, enbrain requested changes

2021-10-24 01:07 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +	COMMENT if applicable, and will be suitably randomized within that contraint.
```suggestion
	COMMENT if applicable, and will be suitably randomized within that constraint.
```

2021-10-24 01:07 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +		COMMENT Paths to a random reachable position with positive path-finding favourability computed by a given function.
```suggestion
		COMMENT Paths to a random reachable position with positive path-finding favorability computed by a given function.
```

2021-10-24 01:07 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT tunction to compute the path-finding favourability of a candidate position
```suggestion
			COMMENT function to compute the path-finding favorability of a candidate position
```

2021-10-27 10:27 UTC, enbrain approved these changes
Looks good besides Juuxel's point. (you can batch apply suggestions from the "Files changed" tab.)

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the horizontal pathing range. This is how far the point can be from the entity's starting position on the X or Z range
```suggestion
			COMMENT the horizontal pathing range (how far the point can be from the entity's starting position on the X or Z range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the vertical pathing range. This is how far the point can be from the entity's starting position on the Y range
```suggestion
			COMMENT the vertical pathing range (how far the point can be from the entity's starting position on the Y range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the horizontal pathing range. This is how far the point can be from the entity's starting position on the X or Z range
```suggestion
			COMMENT the horizontal pathing range (how far the point can be from the entity's starting position on the X or Z range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the vertical pathing range. This is how far the point can be from the entity's starting position on the Y range
```suggestion
			COMMENT the vertical pathing range (how far the point can be from the entity's starting position on the Y range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the horizontal pathing range. This is how far the point can be from the entity's starting position on the X or Z range
```suggestion
			COMMENT the horizontal pathing range (how far the point can be from the entity's starting position on the X or Z range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the vertical pathing range. This is how far the point can be from the entity's starting position on the Y range
```suggestion
			COMMENT the vertical pathing range (how far the point can be from the entity's starting position on the Y range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the horizontal pathing range. This is how far the point can be from the entity's starting position on the X or Z range
```suggestion
			COMMENT the horizontal pathing range (how far the point can be from the entity's starting position on the X or Z range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the horizontal pathing range. This is how far the point can be from the entity's starting position on the X or Z range
```suggestion
			COMMENT the horizontal pathing range (how far the point can be from the entity's starting position on the X or Z range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/FuzzyTargeting.mapping
> +			COMMENT the vertical pathing range. This is how far the point can be from the entity's starting position on the Y range
```suggestion
			COMMENT the vertical pathing range (how far the point can be from the entity's starting position on the Y range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/NoPenaltyTargeting.mapping
> +			COMMENT the horizontal pathing range. This is how far the point can be from the entity's starting position on the X or Z range
```suggestion
			COMMENT the horizontal pathing range (how far the point can be from the entity's starting position on the X or Z range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/NoPenaltyTargeting.mapping
> +			COMMENT the vertical pathing range. This is how far the point can be from the entity's starting position on the Y range
```suggestion
			COMMENT the vertical pathing range (how far the point can be from the entity's starting position on the Y range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/NoPenaltyTargeting.mapping
> +			COMMENT the horizontal pathing range. This is how far the point can be from the entity's starting position on the X or Z range
```suggestion
			COMMENT the horizontal pathing range (how far the point can be from the entity's starting position on the X or Z range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/NoPenaltyTargeting.mapping
> +			COMMENT the vertical pathing range. This is how far the point can be from the entity's starting position on the Y range
```suggestion
			COMMENT the vertical pathing range (how far the point can be from the entity's starting position on the Y range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/NoPenaltyTargeting.mapping
> +			COMMENT the horizontal pathing range. This is how far the point can be from the entity's starting position on the X or Z range
```suggestion
			COMMENT the horizontal pathing range (how far the point can be from the entity's starting position on the X or Z range)
```

2021-10-27 10:27 UTC, enbrain commented on mappings/net/minecraft/entity/ai/NoPenaltyTargeting.mapping
> +			COMMENT the vertical pathing range. This is how far the point can be from the entity's starting position on the Y range
```suggestion
			COMMENT the vertical pathing range (how far the point can be from the entity's starting position on the Y range)
```

2021-11-03 13:00 UTC, Sollace commented
Alrighty, thanks @enbrain ! I've committed all suggestions.

2021-11-03 13:10 UTC, enbrain approved these changes

2021-11-03 14:12 UTC, modmuss50 approved these changes

2021-11-03 14:12 UTC, merged