primeTnt method, and UNSTABLE field.
asiekierka/MinecraftPOMF pull request #281
Opened 2018-12-13 00:40 UTC by MasterEric

2018-12-13 01:34 UTC, shadowfacts requested changes

2018-12-13 01:34 UTC, shadowfacts commented on mappings/net/minecraft/block/TntBlock.mapping
> +		ARG 2 blockPos
`pos`, like the rest of the block methods

2018-12-14 23:58 UTC, MasterEric commented
@shadowfacts The requested change has been implemented and the commit rebased.

2018-12-15 00:16 UTC, shadowfacts approved these changes

2018-12-15 00:42 UTC, jamierocks approved these changes
:+1:

2018-12-15 08:52 UTC, merged