Updated some entity fields and class mappings
asiekierka/MinecraftPOMF pull request #288
Opened 2018-12-13 12:54 UTC by strikerrocker

2018-12-13 13:17 UTC, asiekierka requested changes

2018-12-13 13:17 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/IllagerEntity.mapping
> +	CLASS apb$a IllagerState
It's an inner class; why not State?

2018-12-13 13:17 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/SlimeEntity.mapping
> +	FIELD bE wasOnGround Z
When is this true?

2018-12-13 13:20 UTC, strikerrocker commented on mappings/net/minecraft/entity/mob/SlimeEntity.mapping
> +	FIELD bE wasOnGround Z
What do ya mean?

2018-12-13 13:23 UTC, strikerrocker commented on mappings/net/minecraft/entity/mob/SlimeEntity.mapping
> +	FIELD bE wasOnGround Z
Anwyays this is true when onGround was true.

2018-12-13 13:24 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/SlimeEntity.mapping
> +	FIELD bE wasOnGround Z
And it's never set to false, ever?

2018-12-14 04:30 UTC, strikerrocker commented
Did the requested changes

2018-12-14 07:16 UTC, asiekierka approved these changes

2018-12-14 08:16 UTC, SquidDev approved these changes
I'm slightly worried by the `isJohnny` field, but who am I to question Mojang?

2018-12-14 13:37 UTC, shadowfacts approved these changes

2018-12-14 13:37 UTC, merged