Rename flag from 'scared' to 'sitting'
asiekierka/MinecraftPOMF pull request #2965
Opened 2022-01-17 22:30 UTC by Machine-Maker

When you send the entity metadata packet with the appropriate update to the client
the panda's behavior can be better described as sitting up rather than being scared

2022-01-22 04:03 UTC, Machine-Maker commented
@haykam821 Why do you think this shouldn't be changed?

2022-02-15 14:06 UTC, apple502j commented
Current name seems like a bug. 
![image](https://user-images.githubusercontent.com/33279053/154077669-f290928b-60e0-40d2-bc3e-26af89b710d1.png)

2022-02-15 14:07 UTC, apple502j requested changes

2022-02-15 14:07 UTC, apple502j commented on mappings/net/minecraft/entity/passive/PandaEntity.mapping
>  	METHOD method_6534 getScaredAnimationProgress (F)F
I believe this method (plus a few that mention "scared", except `isScaredByThunderstorm`) also needs a change.

2022-02-18 17:21 UTC, Machine-Maker commented
Ok, updated other methods and fields with the `sitting` moniker instead of `scared` (except for isScaredByThunderstorm)

2022-02-22 15:30 UTC, apple502j commented on mappings/net/minecraft/entity/passive/PandaEntity.mapping
>  	METHOD method_6534 getScaredAnimationProgress (F)F
This is still not fixed?

2022-02-22 16:27 UTC, Machine-Maker commented on mappings/net/minecraft/entity/passive/PandaEntity.mapping
>  	METHOD method_6534 getScaredAnimationProgress (F)F
yeah... not sure how I missed that.

2022-02-22 16:31 UTC, apple502j commented
@Machine-Maker Also, can you fix unpick-definitions/entity_flags.unpick‎ to reflect the rename? Should be easy, just change to SITTING

2022-02-22 16:40 UTC, Machine-Maker commented
Done @apple502j.

2022-02-22 16:58 UTC, apple502j approved these changes

2022-02-22 16:59 UTC, modmuss50 approved these changes

2022-02-22 16:59 UTC, merged