Rename net.minecraft.world.gen.decorator package to placementmodifier
asiekierka/MinecraftPOMF pull request #2986
Opened 2022-01-24 10:49 UTC by NoahvdAa

Resolves #2862.

2022-01-26 12:57 UTC, enbrain reviewed
Some of the placement modifier classes (such as `AbstractCountPlacementModifier`) are still in the decorator package.

2022-01-26 12:57 UTC, enbrain commented on mappings/net/minecraft/world/gen/placementmodifier/RangeDecoratorConfig.mapping
> +CLASS net/minecraft/class_2997 net/minecraft/world/gen/placementmodifier/RangeDecoratorConfig
This is actually a `FeatureConfig` (a config used to make `ConfiguredFeature` from `Feature`). Should probably be `net.minecraft.world.gen.RangeFeatureConfig`.

2022-01-26 13:18 UTC, NoahvdAa commented
Thanks, don't know how I missed that.

2022-01-26 13:28 UTC, enbrain reviewed
`DecoratorContext` should be renamed too. It's a context passed to `PlacementModifier#getPositions`. Maybe `net.minecraft.world.gen.placementmodifier.PlacementModifierContext`? (Is this a little bit too long?)

2022-01-26 13:33 UTC, Juuxel commented
Or `FeaturePlacementContext` could work too (a plain `PlacementContext` won't work since it can be confused with `ItemPlacementContext`)

2022-01-26 13:38 UTC, NoahvdAa commented
> Or `FeaturePlacementContext` could work too (a plain `PlacementContext` won't work since it can be confused with `ItemPlacementContext`)

:+1: Changed to FeaturePlacementContext since it's not only used in placement modifiers.

2022-01-26 13:40 UTC, enbrain approved these changes

2022-01-26 13:44 UTC, Juuxel requested changes

2022-01-26 13:44 UTC, Juuxel commented on mappings/net/minecraft/world/gen/RangeFeatureConfig.mapping
> +CLASS net/minecraft/class_2997 net/minecraft/world/gen/RangeFeatureConfig
This should be in the feature package

2022-01-26 21:39 UTC, Juuxel approved these changes

2022-01-26 23:06 UTC, liach approved these changes
Good by naked eye

2022-01-27 06:19 UTC, Shnupbups approved these changes

2022-01-28 16:30 UTC, YanisBft approved these changes

2022-01-28 20:10 UTC, merged