Map some fields related to stats and structures
asiekierka/MinecraftPOMF pull request #3006
Opened 2022-02-11 10:40 UTC by NoahvdAa

2022-02-11 18:32 UTC, liach approved these changes

2022-02-11 18:32 UTC, liach commented on mappings/net/minecraft/stat/StatFormatter.mapping
> +	METHOD format format (I)Ljava/lang/String;
```suggestion
	METHOD format (I)Ljava/lang/String;
```

2022-02-12 08:00 UTC, enbrain requested changes

2022-02-12 08:00 UTC, enbrain commented on mappings/net/minecraft/structure/DesertTempleGenerator.mapping
> +	FIELD field_34725 HEIGHT I
This seems to be the 5th (in one-based) argument for `ShiftableStructurePiece(StructurePieceType type, int x, int y, int z, int width, int height, int depth, Direction orientation)`.
```suggestion
	FIELD field_34725 WIDTH I
```

2022-02-12 09:13 UTC, NoahvdAa commented on mappings/net/minecraft/structure/DesertTempleGenerator.mapping
> +	FIELD field_34725 HEIGHT I
Are you sure? It seems to be the fourth (or sixth, but that's already the depth)
```java
super(StructurePieceType.DESERT_TEMPLE, x, 64, z, 21, 15, 21, DesertTempleGenerator.getRandomHorizontalDirection(random));```

2022-02-12 09:58 UTC, enbrain commented on mappings/net/minecraft/structure/DesertTempleGenerator.mapping
> +	FIELD field_34725 HEIGHT I
Yes. it's fourth in zero-based, but the fourth is width. You named it `HEIGHT`.

2022-02-12 10:02 UTC, NoahvdAa commented on mappings/net/minecraft/structure/DesertTempleGenerator.mapping
> +	FIELD field_34725 HEIGHT I
My bad, I completely misread your comment 🤦.

2022-02-12 10:03 UTC, enbrain approved these changes

2022-02-12 17:04 UTC, modmuss50 approved these changes

2022-02-12 17:04 UTC, merged