Map VeinCreator (class_6955)
asiekierka/MinecraftPOMF pull request #3038
Opened 2022-02-25 18:02 UTC by NoahvdAa

This class *seems* to be related to the creation of ore veins. Not sure about the parameter names, but what I have right now seems to be what they're used for.

2022-02-27 22:23 UTC, enbrain commented on mappings/net/minecraft/world/gen/VeinCreator.mapping
> +CLASS net/minecraft/class_6955 net/minecraft/world/gen/VeinCreator
I suggest `class_6955` → `OreVeinSampler` and `method_40548` → `create`. This way, `class_6955.method_40548` can be read as a method that returns a sampler (and that sampler samples a block state in a ore vein for a given position).

2022-02-27 22:23 UTC, enbrain commented on mappings/net/minecraft/world/gen/VeinCreator.mapping
> +		FIELD field_33668 rawBlock Lnet/minecraft/class_2680;
I would be tempted to rename it `rawOreBlock` for clarity.

2022-02-28 07:56 UTC, enbrain requested changes

2022-02-28 07:56 UTC, enbrain commented on mappings/net/minecraft/world/gen/OreVeinSampler.mapping
> +	FIELD field_36627 RAW_BLOCK_CHANCE F
```suggestion
	FIELD field_36627 RAW_ORE_BLOCK_CHANCE F
```

2022-02-28 07:56 UTC, enbrain commented on mappings/net/minecraft/world/gen/OreVeinSampler.mapping
> +		FIELD field_33668 rawBlock Lnet/minecraft/class_2680;
```suggestion
		FIELD field_33668 rawOreBlock Lnet/minecraft/class_2680;
```

2022-02-28 07:56 UTC, enbrain commented on mappings/net/minecraft/world/gen/OreVeinSampler.mapping
> +		ARG 5 startPos
Ore veins don't have a start position as far as I know. Instead, the chunk generator calls this lambda for every position not covered by the aquifer sampler. Notice that it returns `null` to use the fallback state/the chunk generator's default block state. Just `pos` or `noisePos`?

2022-03-02 22:55 UTC, enbrain approved these changes

2022-03-05 14:37 UTC, modmuss50 approved these changes

2022-03-05 14:37 UTC, merged