Fix registry value being named key
asiekierka/MinecraftPOMF pull request #3039
Opened 2022-03-03 19:21 UTC by Machine-Maker

These represent a registry value, not the key

Needed `val` instead of `value` cause `value` is already defined in the scope (its in a computeIfAbsent call)

2022-03-03 19:46 UTC, haykam821 requested changes
Lambda parameters should be suffixed with `x` if they would otherwise conflict with other name.

2022-03-03 19:46 UTC, haykam821 commented on mappings/net/minecraft/util/registry/SimpleRegistry.mapping
> +		ARG 1 val
```suggestion
		ARG 1 valuex
```

2022-03-04 02:16 UTC, Machine-Maker commented on mappings/net/minecraft/util/registry/SimpleRegistry.mapping
> +		ARG 1 val
resolved

2022-03-04 02:35 UTC, haykam821 approved these changes

2022-06-01 05:26 UTC, apple502j approved these changes

2022-06-01 15:03 UTC, liach approved these changes

2022-06-01 15:06 UTC, merged