missing loggers / entity names / some more...
asiekierka/MinecraftPOMF pull request #3042
Opened 2022-03-11 10:35 UTC by Sertonix

2022-03-13 10:04 UTC, enbrain requested changes
I only checked a small portion of this PR. Renames made in this PR look somewhat controversial (mainly conciseness vs clarity).

2022-03-13 10:04 UTC, enbrain commented on mappings/net/minecraft/entity/Entity.mapping
> +	FIELD field_36331 onGround_ Z
How is this different to the existing `onGround` field?

2022-03-13 10:04 UTC, enbrain commented on mappings/net/minecraft/entity/EntityType.mapping
> +		METHOD create create (Lnet/minecraft/class_1299;Lnet/minecraft/class_1937;)Lnet/minecraft/class_1297;
We don't mark non-obfuscated methods as deobfuscated.
```suggestion
		METHOD create (Lnet/minecraft/class_1299;Lnet/minecraft/class_1937;)Lnet/minecraft/class_1297;
```

2022-03-13 10:04 UTC, enbrain commented on mappings/net/minecraft/entity/FallingBlockEntity.mapping
> +	FIELD field_36333 Logger Lorg/slf4j/Logger;
It's static final.
```suggestion
	FIELD field_36333 LOGGER Lorg/slf4j/Logger;
```

2022-03-13 10:04 UTC, enbrain commented on mappings/net/minecraft/entity/ai/brain/Schedule.mapping
> +		ARG 1 scheduleRuleEntry
This is not a `ScheduleRuleEntry`, but a `Map.Entry`.
```suggestion
		ARG 1 entry
```

2022-03-13 10:04 UTC, enbrain commented on mappings/net/minecraft/entity/mob/ZombifiedPiglinEntity.mapping
> +		ARG 1 zombifiedPiglinEntity
I believe #407 is talking about class names. `zombifiedPiglin` is fine for a lambda parameter imo.

2022-03-14 07:11 UTC, Sertonix commented on mappings/net/minecraft/entity/Entity.mapping
> +	FIELD field_36331 onGround_ Z
I renamed it to `lastMoveOnGround` because it is only set in the `Entity.move` function.

2022-03-14 07:14 UTC, Sertonix commented on mappings/net/minecraft/entity/ai/brain/Schedule.mapping
> +		ARG 1 scheduleRuleEntry
i removed that as it would be the same value as if I marked it as deobfuscated

2022-12-28 12:29 UTC, closed without merging