Rename the PotionEntity#damageEntitiesHurtByWater method to applyWater
asiekierka/MinecraftPOMF pull request #3097
Opened 2022-04-20 03:57 UTC by haykam821

Fixes #3087

2022-04-20 06:43 UTC, Shnupbups approved these changes

2022-04-20 08:43 UTC, apple502j requested changes
The name isn't really clear (`applyWaterEffectsToEntities` maybe? is that too long)

2022-04-20 11:01 UTC, haykam821 commented
@apple502j The name matches the `applySplashPotion` and `applyLingeringPotion` methods in the same class.

2022-04-20 11:57 UTC, apple502j commented
Hmm, then maybe it works. "apply water" does sound strange, and the method only affects entities (not fire blocks), though.

2022-04-27 12:13 UTC, enbrain approved these changes

2022-04-27 12:41 UTC, merged