1.19-pre4 stuff
asiekierka/MinecraftPOMF pull request #3199
Opened 2022-05-30 16:32 UTC by apple502j

Expired messages on the server no longer get discarded - javadoc updated to reflect this change. And mapped several trivial method names and one new field.

2022-05-31 13:30 UTC, liach commented on mappings/net/minecraft/client/gui/screen/ingame/HandledScreen.mapping
> +	METHOD method_44339 clearTouchDragStack ()V
Is this more like
```suggestion
	METHOD method_44339 endTouchDrag ()V
```

2022-05-31 13:30 UTC, liach commented on mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
> +	COMMENT are considered expired and log warnings on the server.. Messages will be
```suggestion
	COMMENT are considered expired and log warnings on the server. Messages will be
```

2022-05-31 13:30 UTC, liach commented on mappings/net/minecraft/network/packet/c2s/play/ChatMessageC2SPacket.mapping
> +	COMMENT discarded if the server receives them with improper order.
```suggestion
	COMMENT discarded if the server receives them in improper order.
```

2022-05-31 13:30 UTC, liach commented on mappings/net/minecraft/network/packet/c2s/play/CommandExecutionC2SPacket.mapping
> +	COMMENT discarded if the server receives them with improper order.
```suggestion
	COMMENT discarded if the server receives them in improper order.
```

2022-05-31 13:30 UTC, liach commented on mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
> +		COMMENT {@return whether the message sent at {@code timestamp} is received with proper order}
```suggestion
		COMMENT {@return whether the message sent at {@code timestamp} is received in proper order}
```

2022-05-31 14:13 UTC, liach approved these changes

2022-05-31 21:28 UTC, Juuxel requested changes

2022-05-31 21:28 UTC, Juuxel commented on mappings/net/minecraft/server/network/ServerPlayNetworkHandler.mapping
> +		COMMENT @implNote This returns {@code false} if the message is arrived with {@linkplain
```suggestion
		COMMENT @implNote This returns {@code false} if the message arrives with {@linkplain
```
The original phrasing sounds a bit odd

2022-06-14 17:18 UTC, modmuss50 approved these changes

2022-06-14 17:18 UTC, merged