Document AbstractBlock and Block
asiekierka/MinecraftPOMF pull request #3226
Opened 2022-06-26 16:57 UTC by apple502j

Spent more than 1 day and here it is. Documented most overridable methods in `AbstractBlock` and `Block`, and `AbstractBlock` now has a table describing the block placing/breaking flow.

I'll spend this week documenting more stuff, until 1.20 snapshots arrive.

2022-07-03 18:03 UTC, enbrain commented on mappings/net/minecraft/block/AbstractBlock.mapping
>  		COMMENT @deprecated Consider calling {@link AbstractBlockState#createScreenHandlerFactory} instead. See <a href="#deprecated-methods">the class javadoc</a>.
Should we reword this since the class javadoc got more contents?
```suggestion
		COMMENT @deprecated Consider calling {@link AbstractBlockState#createScreenHandlerFactory} instead. See <a href="#deprecated-methods">why these methods are deprecated</a>.
```

2022-07-03 18:03 UTC, enbrain commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +	COMMENT <h3 id=breaking>Breaking/ related methods</h3>
Missing a word after `Breaking/`?

2022-07-03 18:03 UTC, enbrain commented on mappings/net/minecraft/block/Block.mapping
> +		COMMENT the block's constructor to override the default default state.
While it's technically the default value of the `defaultState`, "default" twice in a row doesn't sound great. How about `the default state arbitrarily chosen by the state manager`?

2022-07-03 18:03 UTC, enbrain commented on mappings/net/minecraft/block/Block.mapping
> +		COMMENT not drop experience when mined with Silk Touch, consider using {@link
```suggestion
		COMMENT not drop experience when mined with Silk Touch, consider calling {@link
```

2022-07-03 18:03 UTC, enbrain commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +	COMMENT         <th>{@link WorldAccess#setBlockState(BlockPos, BlockState) setBlockState} / {@link net.minecraft.world.ModifiableWorld#removeBlock(BlockPos, boolean) removeBlock} call</th>
Did you mean `World#setBlockState(BlockPos, BlockState)`?

> ```
> /__w/yarn/yarn/.gradle/temp/fakeSource/net/minecraft/block/AbstractBlock.java:174: error: reference not found
>  *         <th>{@link WorldAccess#setBlockState(BlockPos, BlockState) setBlockState} / {@link net.minecraft.world.ModifiableWorld#removeBlock(BlockPos, boolean) removeBlock} call</th>
>                       ^
> ```

https://github.com/FabricMC/yarn/runs/7062815586?check_suite_focus=true#step:5:282

2022-07-06 16:54 UTC, enbrain reviewed
This PR can close #1702.

2022-07-06 16:54 UTC, enbrain commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +	COMMENT so take caution when using those method. The logical side can be checked using
```suggestion
	COMMENT so take caution when using those methods. The logical side can be checked using
```

2022-07-07 13:47 UTC, Juuxel requested changes

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT net.minecraft.screen.NamedScreenHandlerFactory}. For example, any block whose block entity
```suggestion
		COMMENT net.minecraft.screen.NamedScreenHandlerFactory}. For example, any {@link BlockWithEntity} whose block entity
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT net.minecraft.world.GameRules#RANDOM_TICK_SPEED} and can be disabled.
```suggestion
		COMMENT net.minecraft.world.GameRules#RANDOM_TICK_SPEED randomTickSpeed} and can be disabled.
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT weak and strong redstone power.
```suggestion
		COMMENT weak and strong redstone power depending on the direction.
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT <p>Waterloggable blocks must override this to return {@code Fluids.WATER.getStill(false)}
```suggestion
		COMMENT <p>{@linkplain Waterloggable Waterloggable blocks} must override this to return {@code Fluids.WATER.getStill(false)}
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/AbstractBlock.mapping
> +		COMMENT block requirement for blocks (if used along with {@link #canPlaceAt}.)
```suggestion
		COMMENT block requirement for blocks (if used along with {@link #canPlaceAt}).
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/Block.mapping
> +		COMMENT Appends properties to this block. To use this, override and call {@link
```suggestion
		COMMENT Appends block state properties to this block. To use this, override and call {@link
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/Block.mapping
> +		COMMENT net.minecraft.world.GameRules#RANDOM_TICK_SPEED} game rule, and {@link
```suggestion
		COMMENT net.minecraft.world.GameRules#RANDOM_TICK_SPEED randomTickSpeed} game rule, and {@link
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/Block.mapping
> +		COMMENT is enchanted with silk touch or if {@link net.minecraft.world.GameRules#DO_TILE_DROPS}
```suggestion
		COMMENT is enchanted with silk touch or if {@link net.minecraft.world.GameRules#DO_TILE_DROPS doTileDrops}
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/Block.mapping
> +		COMMENT net.minecraft.world.GameRules#DO_TILE_DROPS} is turned off. For blocks that do
```suggestion
		COMMENT net.minecraft.world.GameRules#DO_TILE_DROPS doTileDrops} is turned off. For blocks that do
```

2022-07-07 13:47 UTC, Juuxel commented on mappings/net/minecraft/block/Block.mapping
> +		COMMENT (like {@link TurtleEggBlock}.) {@link BeehiveBlock} uses this to anger the bees if
```suggestion
		COMMENT (like {@link TurtleEggBlock}). {@link BeehiveBlock} uses this to anger the bees if
```

2022-07-23 14:15 UTC, modmuss50 approved these changes

2022-07-25 19:17 UTC, merged