1.19.1-pre3 chat mappings
asiekierka/MinecraftPOMF pull request #3232
Opened 2022-07-06 16:55 UTC by mschae23

Mappings for some of the chat changes and the new packet in 1.19.1-pre3.

2022-07-06 17:47 UTC, apple502j approved these changes
LGTM. Note that I also mapped them and will intend to rename some of the names here, namely the plurality of the new packet's name.

2022-07-07 11:51 UTC, enbrain approved these changes

2022-07-07 13:57 UTC, Juuxel requested changes

2022-07-07 13:57 UTC, Juuxel commented on mappings/net/minecraft/text/Decoration.mapping
> +		COMMENT @implNote This decoration allows use of the sender and the content parameters. It is gray and italic.
```suggestion
		COMMENT @implNote This decoration allows using the sender and the content parameters. It is gray and italic.
```
I think "use of" without an article is ungrammatical? "Using" is more concise anyway

2022-07-07 13:57 UTC, Juuxel commented on mappings/net/minecraft/text/Decoration.mapping
> +		COMMENT @implNote This decoration allows use of the target and the content parameters. It is gray and italic.
```suggestion
		COMMENT @implNote This decoration allows using the target and the content parameters. It is gray and italic.
```

2022-07-07 14:00 UTC, mschae23 commented on mappings/net/minecraft/text/Decoration.mapping
> +		COMMENT @implNote This decoration allows use of the sender and the content parameters. It is gray and italic.
I just copied the documentation of the other message types for this. Should they be changed as well?

2022-07-07 14:16 UTC, apple502j commented on mappings/net/minecraft/text/Decoration.mapping
> +		COMMENT @implNote This decoration allows use of the sender and the content parameters. It is gray and italic.
I can fix it on my PR if you want, or you can fix it here :)

2022-07-07 15:54 UTC, mschae23 commented on mappings/net/minecraft/text/Decoration.mapping
> +		COMMENT @implNote This decoration allows use of the sender and the content parameters. It is gray and italic.
Okay, I fixed it.

2022-07-07 18:14 UTC, Juuxel approved these changes

2022-07-07 20:49 UTC, merged