Updates to BucketItem, the Waterloggable hierarchy and block materials
asiekierka/MinecraftPOMF pull request #327
Opened 2018-12-17 16:26 UTC by Juuxel

This PR maps the rest of `BucketItem` as well as the `Waterloggable` superinterfaces and their methods and some of the `net.minecraft.block.Material` properties.

(Also, I don't know why the merged BucketItem commit is there again /shrug)

2018-12-17 16:28 UTC, Juuxel commented on mappings/net/minecraft/block/FluidFillable.mapping
> +	METHOD a fillWithFluid (Lbbq;Let;Lbpm;Lcfd;)Z
`tryFillWithFluid` would also be acceptable as this can't always succeed.

2018-12-17 16:28 UTC, Juuxel commented on mappings/net/minecraft/block/Material.mapping
> -		METHOD f breakByHand ()Lcfh$a;
Not sure what was going on here.

2018-12-17 16:28 UTC, Juuxel commented on mappings/net/minecraft/block/Material.mapping
> -		METHOD f breakByHand ()Lcfh$a;
That method does not change the breakByHand property.

2018-12-17 18:06 UTC, shadowfacts requested changes

2018-12-17 18:06 UTC, shadowfacts commented on mappings/net/minecraft/block/FluidFillable.mapping
> +	METHOD a fillWithFluid (Lbbq;Let;Lbpm;Lcfd;)Z
Yes, the try name would be better.

2018-12-19 11:30 UTC, Juuxel commented on mappings/net/minecraft/block/BucketInteractable.mapping
> +	METHOD b getBucketFluid (Lbbq;Let;Lbpm;)Lcfc;
I think `interactWithBucket` might be a better name for this as it's not only a getter. Thoughts?

2018-12-19 21:33 UTC, asiekierka commented on mappings/net/minecraft/block/FluidFillable.mapping
> +	METHOD a fillWithFluid (Lbbq;Let;Lbpm;Lcfd;)Z
Yes.

2018-12-20 19:36 UTC, Juuxel commented on mappings/net/minecraft/block/FluidFillable.mapping
> +	METHOD a fillWithFluid (Lbbq;Let;Lbpm;Lcfd;)Z
Fixed.

2018-12-20 19:36 UTC, Juuxel commented
@shadowfacts Could you review again?

2018-12-20 19:51 UTC, asiekierka approved these changes

2018-12-20 20:37 UTC, Juuxel commented on mappings/net/minecraft/block/BucketInteractable.mapping
> +	METHOD b getBucketFluid (Lbbq;Let;Lbpm;)Lcfc;
Actually, it's not a complete impl of what I would consider a method called `interactWithBucket` (it's mostly a getter).

2018-12-20 21:07 UTC, Prospector approved these changes

2018-12-21 00:24 UTC, shadowfacts approved these changes

2018-12-21 00:24 UTC, merged