Document net.minecraft.util
asiekierka/MinecraftPOMF pull request #3297
Opened 2022-09-18 18:28 UTC by apple502j

Big class javadoc for `Identifier` (previously only 1 line), method documentation for `Util`, and several class javadocs. Also adds `package-info`.

2022-09-18 20:10 UTC, Juuxel requested changes

2022-09-18 20:10 UTC, Juuxel commented on src/packageDocs/java/net/minecraft/util/package-info.java
> +
```suggestion
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/StringIdentifiable.mapping
> +	COMMENT by codecs. An instance is identified using a string.
Hmm, isn't this also used for state properties?

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/StringIdentifiable.mapping
> +		COMMENT {@return the string representation of the enum, used for serialization}
```suggestion
		COMMENT {@return the unique string representation of the enum, used for serialization}
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/ActionResult.mapping
> +		COMMENT {@return whether action performance should increment an item's 'used'
```suggestion
		COMMENT {@return whether action performance should increment an item's "used"
```
I'd say double quotes are more common in javadoc in general

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/FixedBufferInputStream.mapping
> +	COMMENT A buffered input stream that uses fixed buffer array.
```suggestion
	COMMENT A buffered input stream that uses a fixed-size buffer array.
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/DyeColor.mapping
> +		COMMENT {@return the float array containing red, blue and green components of this dye color}
```suggestion
		COMMENT {@return the float array containing the red, green and blue components of this dye color}
```
They're in that order so this is clearer imo

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/TimeHelper.mapping
> +		COMMENT {@return an int provider that provides number of ticks, between {@code min * 20} and
```suggestion
		COMMENT {@return an int provider that provides a time in ticks, between {@code min * 20} and
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/TextifiedException.mapping
> +	COMMENT This should not be constructed directly, and instead be subclassed by the users.
Not sure about that, Mojang seems to subclass for catching purposes at least in the case of the other subclass

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/Util.mapping
> +		COMMENT     return map;
```suggestion
```
It's a consumer, not a function

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT <p><strong>Namespace</strong> of an identifier identifies the origin of the thing.
```suggestion
	COMMENT <p>The <strong>namespace</strong> of an identifier identifies the origin of the thing.
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT mistake is using a formatted string with {@code %d} or {@code %f} to construct an
Do people really use `%f` when constructing IDs? :concern:

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT <p>Namespace only determines the origin, and does not determine the type; so long as
```suggestion
	COMMENT <p>A namespace only determines the source of an identifier, and does not determine its purpose; so long as
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT the identifiers are used for different purposes, it can share the namespace and path.
```suggestion
	COMMENT two identifiers are used for different purposes, they can share the namespace and path.
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT DataFixerUpper,</li>
```suggestion
	COMMENT DataFixerUpper.</li>
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT identifier is represented as a file path with extension, such as {@code
```suggestion
	COMMENT an identifier is represented as a file path with an extension, such as {@code
```

2022-09-18 20:10 UTC, Juuxel commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT net.minecraft.util.registry.RegistryKey} should be used. A registry key is a combination
```suggestion
	COMMENT net.minecraft.util.registry.RegistryKey} can be used. A registry key is a combination
```

2022-09-19 04:25 UTC, apple502j commented on mappings/net/minecraft/util/StringIdentifiable.mapping
> +	COMMENT by codecs. An instance is identified using a string.
They are technically enums.

2022-09-19 04:26 UTC, apple502j commented on mappings/net/minecraft/util/TextifiedException.mapping
> +	COMMENT This should not be constructed directly, and instead be subclassed by the users.
```suggestion
```

2022-09-19 12:03 UTC, Juuxel commented on mappings/net/minecraft/util/StringIdentifiable.mapping
> +	COMMENT by codecs. An instance is identified using a string.
I was talking about the codec part. AFAIK properties, at least partially, do their own serialisation.

2022-09-19 13:16 UTC, enbrain commented on mappings/net/minecraft/util/DyeColor.mapping
> +		COMMENT @apiNote This returns {@code null} if and only if {@code defaultColor} is {@code null}.
```suggestion
		COMMENT @apiNote This returns {@code null} only if {@code defaultColor} is {@code null}.
```

`byName("white", null)` returns a non-null value even though `defaultColor` is `null`.

2022-09-19 13:16 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +		COMMENT {@return a future that completes exceptionally with {@code throwable}}
```suggestion
		COMMENT {@return a future that is already completed exceptionally with {@code throwable}}
```

2022-09-19 13:16 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +		COMMENT {@code prefix}}
```suggestion
		COMMENT {@return a consumer that first prepends {@code prefix} to its input
		COMMENT string and passes the result to {@code consumer}}
```

2022-09-19 13:16 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +		COMMENT <p>If {@code object} is not in {@code iterable}, this returns the last item of the iterable.
Might be worth mentioning how the equality is checked (`equals` or `==`).

2022-09-19 13:16 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +		COMMENT returns the first item of the iterable.
Same as above.

2022-09-19 13:16 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +		COMMENT An instance can be obtained via {@link Util#getOperatingSystem}.
```suggestion
		COMMENT The current one can be obtained via {@link Util#getOperatingSystem}.
```

2022-09-19 13:16 UTC, enbrain commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT is omitted, the namespace defaults to {@value #DEFAULT_NAMESPACE}.
```suggestion
	COMMENT are omitted, the namespace defaults to {@value #DEFAULT_NAMESPACE}.
```

2022-09-19 14:01 UTC, apple502j commented on mappings/net/minecraft/util/StringIdentifiable.mapping
> +	COMMENT by codecs. An instance is identified using a string.
Yeah; but I think this is acceptable.

2022-09-20 10:16 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +		COMMENT returns the first item of the iterable.
If `object` is not in `iterable`, the while loop never terminates.

![image](https://user-images.githubusercontent.com/69905075/191231003-49bcb97e-76a3-4067-b2fe-0ebe0d136cf1.png)

2022-09-20 16:42 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +		COMMENT @implNote If {@code object} is not in {@code iterable}, this enters into an infinite loop.
Unlike `next`, `previous` does not enter into an infinite loop.

I think these methods *expect* `object` to be in `iterable`. (If that's the case, these methods should throw `IllegalArgumentException` though.)

2022-09-20 16:42 UTC, enbrain commented on mappings/net/minecraft/util/Identifier.mapping
> +	COMMENT <p>Several namespaces are reserved for vanilla use. While those identifier can be used for
```suggestion
	COMMENT <p>Several namespaces are reserved for vanilla use. While those identifiers can be used for
```

2022-09-20 16:42 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +			COMMENT Opens {@code url}. If this points to a HTTP(S) URL, it is usually opened using
```suggestion
			COMMENT Opens {@code url}. If this points to an HTTP(S) URL, it is usually opened using
```

2022-09-20 16:42 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +			COMMENT Opens {@code uri}. If this points to a HTTP(S) URI, it is usually opened using
```suggestion
			COMMENT Opens {@code uri}. If this points to an HTTP(S) URI, it is usually opened using
```

2022-09-20 16:42 UTC, enbrain commented on mappings/net/minecraft/util/Util.mapping
> +			COMMENT Opens {@code uri}. If this points to a HTTP(S) URI, it is usually opened using
```suggestion
			COMMENT Opens {@code uri}. If this points to an HTTP(S) URI, it is usually opened using
```

2022-09-21 06:48 UTC, Juuxel approved these changes

2022-09-21 09:51 UTC, enbrain approved these changes

2022-09-21 17:29 UTC, modmuss50 approved these changes

2022-09-21 17:30 UTC, merged