Add Documentation for core Particle classes
asiekierka/MinecraftPOMF pull request #3321
Opened 2022-10-16 21:22 UTC by Draylar

Hi! I started a write-up of some Javadocs for the core Particle classes. I would appreciate any feedback on the documentation. I also haven't used Enigma in a while, so please let me know if you spot a syntax error or typo!

I also renamed `method_18140` from `setSprite` to `setRandomSprite`. IMO it's confusing as a caller _what_ method you're looking at (because the arguments are `Sprite` vs. `SpriteProvider`), and the implementation of this method makes it clear it is aimed at selecting a random sprite from the particle's texture atlas. I'm happy to remove this and wait if it needs to be in a separate PR or discussed more first.

2022-10-18 09:05 UTC, YanisBft commented on mappings/net/minecraft/client/particle/SpriteBillboardParticle.mapping
> +		COMMENT @return the upper U coordinate of the {@link Sprite} rendered by this particle
```suggestion
		COMMENT @return the upper V coordinate of the {@link Sprite} rendered by this particle
```

2022-10-18 12:31 UTC, apple502j requested changes
Please revert the rename. It is extremely impactful.

2022-10-18 15:40 UTC, enbrain commented
I added impactful/refactor labels to avoid accidental merge. Can be removed later.

2022-10-18 20:24 UTC, enbrain commented on mappings/net/minecraft/client/particle/BillboardParticle.mapping
> +			COMMENT the amount to multiply this particle's scale by
Did Enigma produce this? It looks like you documented a parameter, but the toolchain doesn't support it.

2022-10-18 20:24 UTC, enbrain commented on mappings/net/minecraft/client/particle/ParticleTextureSheet.mapping
> +			COMMENT textureManager texture loading context
```suggestion
		ARG 1 builder
			COMMENT the buffer particles will draw to in {@link net.minecraft.client.particle.Particle#buildGeometry(VertexConsumer, Camera, float)}
		ARG 2 textureManager
			COMMENT texture loading context
```

2022-10-19 06:50 UTC, Draylar commented on mappings/net/minecraft/client/particle/BillboardParticle.mapping
> +			COMMENT the amount to multiply this particle's scale by
Oops. Maybe because it's an `@Override`? Removed it in the last commit.

2022-10-19 08:46 UTC, apple502j commented on mappings/net/minecraft/client/particle/BillboardParticle.mapping
> +			COMMENT the amount to multiply this particle's scale by
Yeah, I don't think you can currently document an overridden impl .

2022-10-19 08:46 UTC, apple502j approved these changes

2022-10-19 08:53 UTC, modmuss50 approved these changes

2022-10-19 08:53 UTC, merged