Mapped a few goals
asiekierka/MinecraftPOMF pull request #333
Opened 2018-12-18 10:32 UTC by liach

2018-12-19 15:43 UTC, Prospector approved these changes

2018-12-19 21:26 UTC, SquidDev approved these changes

2018-12-19 21:29 UTC, asiekierka requested changes

2018-12-19 21:29 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/ZombieEntity.mapping
> +		METHOD a onDestory (Lbbp;Let;)V
onDestory?

2018-12-19 21:29 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/ZombieEntity.mapping
> +		METHOD i getDesiredSquareDistanceToTarget ()D
SquaredDistance

2018-12-19 21:29 UTC, asiekierka commented on mappings/net/minecraft/entity/passive/IronGolemEntity.mapping
> +	FIELD b findVillageDelay I
villageSearchTicks? Or what does this do?

2018-12-20 03:13 UTC, liach commented on mappings/net/minecraft/entity/passive/IronGolemEntity.mapping
> +	FIELD b findVillageDelay I
ticks to wait before searching for and joining a village

2018-12-20 03:13 UTC, liach commented on mappings/net/minecraft/entity/mob/ZombieEntity.mapping
> +		METHOD a onDestory (Lbbp;Let;)V
when the goal destroys a block

2018-12-20 03:49 UTC, liach commented on mappings/net/minecraft/entity/mob/ZombieEntity.mapping
> +		METHOD i getDesiredSquareDistanceToTarget ()D
Fixed.

2018-12-20 08:40 UTC, asiekierka commented on mappings/net/minecraft/entity/mob/ZombieEntity.mapping
> +		METHOD a onDestory (Lbbp;Let;)V
Typo!

2018-12-20 08:41 UTC, merged