Added Partial Math Mappings
asiekierka/MinecraftPOMF pull request #3372
Opened 2022-10-29 19:54 UTC by kevinthegreat1

Someone actually good at linear algebruh will have to finish MatrixUtil.
But there are some mappings in here.

2022-10-29 22:58 UTC, enbrain requested changes

2022-10-29 22:58 UTC, enbrain commented on mappings/net/minecraft/util/math/Division.mapping
> +	COMMENT The first returned integer always equals to {@code Math.floor(divident / divisor)}
Your explanation is a bit too focusing on implementation imo. How about this?

```suggestion
	COMMENT A class for dividing an integer into {@link #divisor} numbers of
	COMMENT integers such that the difference between any integers is less than or
	COMMENT equal to {@code 1}. For example, {@code new Division(13, 5)} will
	COMMENT produce {@code 2, 3, 2, 3, 3}.
```

2022-10-29 22:58 UTC, enbrain commented on mappings/net/minecraft/util/math/Division.mapping
> +	METHOD method_46402 asInterable (II)Ljava/lang/Iterable;
Typo? unless you mean ***int***erable is iterable of integer.

```suggestion
	METHOD method_46402 asIterable (II)Ljava/lang/Iterable;
```

2022-10-29 22:58 UTC, enbrain commented on mappings/net/minecraft/util/math/MatrixUtil.mapping
> +		ARG 0 matrix4f
```suggestion
		ARG 0 matrix
```

2022-10-29 22:58 UTC, enbrain commented on mappings/net/minecraft/util/math/MatrixUtil.mapping
> +		ARG 0 matrix4f
```suggestion
		ARG 0 matrix
```

2022-10-29 22:58 UTC, enbrain commented on mappings/net/minecraft/util/math/Division.mapping
> +	METHOD hasNext hasNext ()Z
We don't map non-obfuscated methods.

```suggestion
```

2022-10-29 22:58 UTC, enbrain commented on mappings/net/minecraft/util/math/Division.mapping
> +	METHOD nextInt nextInt ()I
```suggestion
```

2022-10-29 22:58 UTC, enbrain commented on mappings/net/minecraft/util/math/RotationAxis.mapping
> +		ARG 1 rad
```suggestion
	METHOD rotation (F)Lorg/joml/Quaternionf;
		ARG 1 rad
```

2022-10-29 22:58 UTC, enbrain commented on mappings/net/minecraft/util/math/RotationAxis.mapping
> +		ARG 1 deg
```suggestion
	METHOD rotationDegrees (F)Lorg/joml/Quaternionf;
		ARG 1 deg
```

2022-10-29 23:35 UTC, kevinthegreat1 commented
I updated the Javadoc to something similar. I also changed the name to divider as it literally divides an integer.

2022-10-30 05:49 UTC, enbrain approved these changes

2022-10-30 05:54 UTC, enbrain commented on mappings/net/minecraft/util/math/Divider.mapping
> +	COMMENT For example, {@code new Division(13, 5)} will produce {@code 2, 3, 2, 3, 3}.
```suggestion
	COMMENT For example, {@code new Divider(13, 5)} will produce {@code 2, 3, 2, 3, 3}.
```

2022-10-30 16:50 UTC, apple502j approved these changes

2022-11-01 01:11 UTC, merged