1.19.3-pre1 variant for predicates
asiekierka/MinecraftPOMF pull request #3420
Opened 2022-11-22 16:53 UTC by YanisBft

2022-11-22 17:05 UTC, Shnupbups approved these changes
Bit annoying to have a mix of `Variant` and `Type`, but I suppose it's best that we keep to the naming used in the entity's respective NBT formats as we currently do until (hopefully) Mojang moves other mobs to a similar registry-backed variant system like Frogs and Cats have.

2022-11-22 17:38 UTC, enbrain requested changes

2022-11-22 17:38 UTC, enbrain commented on mappings/net/minecraft/entity/passive/FoxEntity.mapping
> +		FIELD field_41548 TYPE_BY_ID Lnet/minecraft/class_3542$class_7292;
This is a codec. If anything, `field_17998` is the type-by-id array.
```suggestion
		FIELD field_41548 CODEC Lnet/minecraft/class_3542$class_7292;
```

2022-11-22 17:38 UTC, enbrain commented on mappings/net/minecraft/entity/passive/MooshroomEntity.mapping
> +		FIELD field_41549 TYPE_BY_ID Lnet/minecraft/class_3542$class_7292;
```suggestion
		FIELD field_41549 CODEC Lnet/minecraft/class_3542$class_7292;
```

2022-11-22 17:38 UTC, enbrain commented on mappings/net/minecraft/entity/vehicle/BoatEntity.mapping
> +		FIELD field_41599 TYPE_BY_ID Lnet/minecraft/class_3542$class_7292;
```suggestion
		FIELD field_41599 CODEC Lnet/minecraft/class_3542$class_7292;
```

2022-11-22 18:08 UTC, enbrain approved these changes

2022-11-23 01:10 UTC, apple502j requested changes

2022-11-23 01:10 UTC, apple502j commented on mappings/net/minecraft/entity/VariantHolder.mapping
> +	METHOD method_47826 getVariant (Ljava/lang/Object;)V
:concern:

2022-11-23 07:06 UTC, Shnupbups requested changes

2022-11-23 07:06 UTC, Shnupbups commented on mappings/net/minecraft/entity/VariantHolder.mapping
> +	METHOD method_47826 getVariant (Ljava/lang/Object;)V
```suggestion
	METHOD method_47826 setVariant (Ljava/lang/Object;)V
```

2022-11-23 07:06 UTC, Shnupbups approved these changes

2022-11-23 07:56 UTC, apple502j approved these changes

2022-11-23 07:56 UTC, merged

2022-11-23 13:21 UTC, AkashiiKun commented
AxolotlEntity's getVariant and setVariant is missing

method_47826 = setVariant
method_47827 = getVariant