A handful of Block mappings
asiekierka/MinecraftPOMF pull request #344
Opened 2018-12-20 01:55 UTC by gudenau

Probably made a mess of things, first try after all.

2018-12-20 08:47 UTC, asiekierka approved these changes

2018-12-20 13:28 UTC, shadowfacts requested changes
Local variables shouldn't be mapped until they're properly supported across all of Fabric's toolchain.

Other than that, looks good.

2018-12-20 13:28 UTC, shadowfacts commented on mappings/net/minecraft/block/Block.mapping
> +		ARG 6 itemStack
`stack` is used as the parameter name for `ItemStack` parameters in `Item` methods. Should be the same here for consistency.

2018-12-20 21:04 UTC, Prospector requested changes
Other than that one `itemStack` parameter, looks good 👍

2018-12-20 21:04 UTC, Prospector commented on mappings/net/minecraft/block/Block.mapping
> +		ARG 6 itemStack
agree on this

2018-12-20 22:54 UTC, gudenau commented
There are conflicts on this and I have no idea how one would fix that.

2018-12-20 22:55 UTC, gudenau commented
I also don't know how to pull the suggested changes.

2018-12-21 00:20 UTC, shadowfacts commented
Make the changes locally and then commit & push to your fork. I can deal with resolving the merge conflicts.

2018-12-21 16:41 UTC, gudenau commented
Changed the itemStack param to stack.

2018-12-22 03:34 UTC, shadowfacts approved these changes

2018-12-22 03:34 UTC, merged