Map armor trims and related things
asiekierka/MinecraftPOMF pull request #3463
Opened 2023-01-24 18:19 UTC by MattiDragon

Open to suggestions for more related things to map

2023-01-24 18:55 UTC, MattiDragon commented
Made this a draft as screen stuff is still WIP

2023-01-25 15:41 UTC, MattiDragon commented
I think I'll stop adding things now. Ready for review

2023-01-26 06:28 UTC, haykam821 requested changes

2023-01-26 06:28 UTC, haykam821 commented on mappings/net/minecraft/LegacySmithingScreen.mapping
> +CLASS net/minecraft/class_8065 net/minecraft/LegacySmithingScreen
This class is not in the correct package.

2023-01-26 06:28 UTC, haykam821 commented on mappings/net/minecraft/LegacySmithingScreenHandler.mapping
> +CLASS net/minecraft/class_8050 net/minecraft/LegacySmithingScreenHandler
This class is also not in the correct package.

2023-01-26 06:37 UTC, haykam821 requested changes

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/item/trim/ArmorTrimPattern.mapping
> +	METHOD method_48446 getDescripting (Lnet/minecraft/class_6880;)Lnet/minecraft/class_2561;
Is this correct?

```suggestion
	METHOD method_48446 getDescription (Lnet/minecraft/class_6880;)Lnet/minecraft/class_2561;
```

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/item/trim/ArmorTrimPatterns.mapping
> +		ARG 0 drm
```suggestion
		ARG 0 registryManager
```

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/recipe/Recipe.mapping
> +		ARG 1 drm
```suggestion
		ARG 1 registryManager
```

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/recipe/Recipe.mapping
> +		ARG 2 drm
```suggestion
		ARG 2 registryManager
```

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/screen/ForagingScreenSlots.mapping
> +	METHOD method_48371 getIndecies ()Ljava/util/List;
```suggestion
	METHOD method_48371 getIndices ()Ljava/util/List;
```

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/screen/ForagingScreenSlots.mapping
> +	METHOD method_48370 getInputSlotCount2 ()I
What's the difference between these two methods? Usually, methods don't have numeric suffixes.

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/screen/ForgingScreenHandler.mapping
> +	FIELD field_41903 inputSlotIndecies Ljava/util/List;
```suggestion
	FIELD field_41903 inputSlotIndices Ljava/util/List;
```

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/item/trim/ArmorTrim.mapping
> +		ARG 0 drm
```suggestion
		ARG 0 registryManager
```

2023-01-26 06:37 UTC, haykam821 commented on mappings/net/minecraft/item/trim/ArmorTrim.mapping
> +		ARG 1 drm
```suggestion
		ARG 1 registryManager
```

2023-01-26 13:22 UTC, Shnupbups requested changes, later dismissed

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/data/server/recipe/TransformSmithingRecipeJsonBuilder.mapping
> +	CLASS class_8075 TransfromSmithingRecipeJsonProvider
Misspelling, plus the id is `smithing_transform`, would be best to keep that naming order

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/screen/ForagingScreenSlots.mapping
> +CLASS net/minecraft/class_8047 net/minecraft/screen/ForagingScreenSlots
Misspelling

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/data/server/recipe/TrimSmithingRecipeJsonBuilder.mapping
> +CLASS net/minecraft/class_8076 net/minecraft/data/server/recipe/TrimSmithingRecipeJsonBuilder
The id is `smithing_trim`, would be best to keep that naming order

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/recipe/TrimSmithingRecipe.mapping
> +CLASS net/minecraft/class_8062 net/minecraft/recipe/TrimSmithingRecipe
The id is `smithing_trim`, would be best to keep that naming order

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/recipe/TransformSmithingRecipe.mapping
> +CLASS net/minecraft/class_8060 net/minecraft/recipe/TransformSmithingRecipe
The id is `smithing_transform`, would be best to keep that naming order

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/data/server/recipe/TransformSmithingRecipeJsonBuilder.mapping
> +CLASS net/minecraft/class_8074 net/minecraft/data/server/recipe/TransformSmithingRecipeJsonBuilder
The id is `smithing_transform`, would be best to keep that naming order

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/data/server/recipe/TrimSmithingRecipeJsonBuilder.mapping
> +	CLASS class_8077 TrimSmithingRecipeJsonProvider
The id is `smithing_trim`, would be best to keep that naming order

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/server/command/SpawnArmorTrimsCommand.mapping
> +	FIELD field_41889 TRIM_GETTER Ljava/util/function/ToIntFunction;
These get their indexes in the lists, not the patterns and trims themselves.

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/data/server/recipe/TrimSmithingRecipeJsonBuilder.mapping
> +	FIELD field_42102 serilizer Lnet/minecraft/class_1865;
Misspelling

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/client/gui/screen/ingame/ForgingScreen.mapping
> +	METHOD method_48467 drawBackgroundExtras (Lnet/minecraft/class_4587;II)V
This is specifically for drawing the arrow with a cross through it for when the recipe is invalid

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/item/ArmorItem.mapping
> +	CLASS class_8051 ArmorSlot
This is not a slot, it's a type of armor

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/item/trim/ArmorTrimMaterials.mapping
> +	METHOD method_48441 makeKey (Ljava/lang/String;)Lnet/minecraft/class_5321;
Usually we just call these `of`. Also why is the parameter not mapped?

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/item/trim/ArmorTrimPatterns.mapping
> +	METHOD method_48449 makeKey (Ljava/lang/String;)Lnet/minecraft/class_5321;
Usually we just call these `of`

2023-01-26 13:22 UTC, Shnupbups commented on mappings/net/minecraft/item/trim/ArmorTrimPatterns.mapping
> +		ARG 0 name
This should be `id`

2023-01-26 14:25 UTC, apple502j commented on mappings/net/minecraft/item/ArmorMaterials.mapping
> +	FIELD field_41944 isTrimmable Z
```suggestion
	FIELD field_41944 trimmable Z
```

2023-01-26 14:25 UTC, apple502j commented on mappings/net/minecraft/item/ArmorMaterials.mapping
> +		ARG 11 isTrimmable
same

2023-01-27 00:29 UTC, apple502j commented on mappings/net/minecraft/item/ArmorItem.mapping
> +	FIELD field_41933 slot Lnet/minecraft/class_1738$class_8051;
Wrong name, but shnupbups PR fixes it

2023-01-27 00:33 UTC, apple502j commented on mappings/net/minecraft/item/trim/ArmorTrim.mapping
> +		ARG 1 other
`o`, but we can fix later

2023-01-27 00:42 UTC, apple502j approved these changes
Issues to be fixed in another PR, let's merge the base

2023-01-27 00:42 UTC, merged