Miscelaneous Javadoc
asiekierka/MinecraftPOMF pull request #3483
Opened 2023-02-08 21:46 UTC by mineblock11

- Raycasts (HitResult classes)
- WorldSavePath constants
- ColorHelper `0xAABBGGRR`

2023-02-09 05:30 UTC, apple502j requested changes

2023-02-09 05:30 UTC, apple502j commented on mappings/net/minecraft/util/WorldSavePath.mapping
> +		COMMENT {@since 1.7.2}
No need for this, we didn't exist back then, and everything in the javadoc is specific to the current Minecraft version.

2023-02-09 05:30 UTC, apple502j commented on mappings/net/minecraft/util/hit/BlockHitResult.mapping
> +	COMMENT When a raycast hits a block, an instance of this class is returned as the {@see HitResult hit result.}
I believe this should be `@linkplain`, and dot should be outside the tag.

2023-02-09 05:30 UTC, apple502j commented on mappings/net/minecraft/util/hit/EntityHitResult.mapping
> +	COMMENT When a raycast hits an entity, an instance of this class is created as the {@see HitResult hit result.}
same

2023-02-09 05:30 UTC, apple502j commented on mappings/net/minecraft/util/hit/HitResult.mapping
> +	COMMENT <p>To get the current raycast of the client {@see net.minecraft.client.MinecraftClient#crosshairTarget you can read the current crosshair target.}
same

2023-02-09 05:30 UTC, apple502j commented on mappings/net/minecraft/util/hit/HitResult.mapping
> +		FIELD field_1333 Lnet/minecraft/class_239$class_240;
Hmm, what are these?

2023-02-09 05:30 UTC, apple502j commented on mappings/net/minecraft/util/math/ColorHelper.mapping
> +		COMMENT as {@code 0xAABBGGRR}
Missing period.

2023-02-09 05:30 UTC, apple502j commented on mappings/net/minecraft/util/math/ColorHelper.mapping
> +		COMMENT <p>ABGR is mostly used in {@see net.minecraft.client.texture.NativeImage native image blending.}
see above

2023-02-09 05:30 UTC, apple502j commented on mappings/net/minecraft/util/math/ColorHelper.mapping
>  			ARG 0 abgr
missing period

2023-02-09 17:23 UTC, mineblock11 commented on mappings/net/minecraft/util/hit/HitResult.mapping
> +		FIELD field_1333 Lnet/minecraft/class_239$class_240;
Odd, I didn't add those

2023-02-10 02:35 UTC, apple502j requested changes

2023-02-10 02:35 UTC, apple502j commented on mappings/net/minecraft/util/WorldSavePath.mapping
> +		COMMENT Only exists on worlds created before 1.7.6
Missing period.

2023-02-10 02:35 UTC, apple502j commented on mappings/net/minecraft/util/math/ColorHelper.mapping
> +			COMMENT <p> The returned value is between {@code 0} and {@code 255} (both inclusive).
Should not have space here, same below

2023-02-21 13:26 UTC, haykam821 requested changes

2023-02-21 13:26 UTC, haykam821 commented on mappings/net/minecraft/util/hit/HitResult.mapping
> +		COMMENT {@return the position where the raycast hit/}
```suggestion
		COMMENT {@return the position where the raycast hit}
```

2023-02-21 13:26 UTC, haykam821 commented on mappings/net/minecraft/util/hit/BlockHitResult.mapping
> +		COMMENT <p>Moves the hit result to a different block.
The documentation here seems to indicate that the instance is modified and returned. However, the method naming implies that a new instance is created instead. Is the documentation correct here?

2023-02-21 13:26 UTC, haykam821 commented on mappings/net/minecraft/util/hit/BlockHitResult.mapping
> +		COMMENT <p>Moves the hit result to a different side of the block.
The documentation here seems to indicate that the instance is modified and returned. However, the method naming implies that a new instance is created instead. Is the documentation correct here?

2024-03-06 07:57 UTC, closed without merging