23w06a client
asiekierka/MinecraftPOMF pull request #3489
Opened 2023-02-12 05:01 UTC by apple502j

Maps grid layout, world creation updates, and rendering (mostly debug renderer params)

2023-02-12 12:21 UTC, Shnupbups requested changes

2023-02-12 12:21 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> +		ARG 1 vertextConsumers
```suggestion
		ARG 1 vertexConsumers
```

2023-02-12 12:21 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> +		ARG 1 vertextConsumers
```suggestion
		ARG 1 vertexConsumers
```

2023-02-12 12:21 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> +		ARG 1 vertextConsumers
```suggestion
		ARG 1 vertexConsumers
```

2023-02-12 12:21 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> +		ARG 1 vertextConsumers
```suggestion
		ARG 1 vertexConsumers
```

2023-02-12 12:21 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> +		ARG 1 vertextConsumers
```suggestion
		ARG 1 vertexConsumers
```

2023-02-12 12:21 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> +		ARG 1 vertextConsumers
```suggestion
		ARG 1 vertexConsumers
```

2023-02-12 12:21 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> +		ARG 1 vertextConsumers
```suggestion
		ARG 1 vertexConsumers
```

2023-02-12 12:21 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/DebugRenderer.mapping
> +		ARG 1 vertextConsumers
```suggestion
		ARG 1 vertexConsumers
```

2023-02-12 12:32 UTC, Shnupbups approved these changes

2023-02-13 17:27 UTC, YanisBft approved these changes

2023-02-13 17:27 UTC, merged