[WIP] Yet more json models
asiekierka/MinecraftPOMF pull request #359
Opened 2018-12-24 15:11 UTC by shadowfacts

# Don't merge this yet.

2018-12-24 19:20 UTC, asiekierka requested changes

2018-12-24 19:20 UTC, asiekierka commented on mappings/net/minecraft/client/render/model/BasicBakedModel.mapping
> +			ARG 1 usesAO
usesAo

2018-12-24 19:20 UTC, asiekierka commented on mappings/net/minecraft/client/render/model/BasicBakedModel.mapping
>  		ARG 3 usesAO
usesAo

2018-12-24 19:46 UTC, asiekierka approved these changes

2018-12-26 08:54 UTC, SquidDev approved these changes

2018-12-26 09:53 UTC, merged