1.20.1-rc1 stuff
asiekierka/MinecraftPOMF pull request #3590
Opened 2023-06-09 15:31 UTC by apple502j

2023-06-09 15:33 UTC, Shnupbups approved these changes

2023-06-09 15:44 UTC, modmuss50 requested changes

2023-06-09 15:44 UTC, modmuss50 commented on mappings/net/minecraft/network/ClientConnection.mapping
> +	FIELD field_44972 disconnectReason Lnet/minecraft/class_2561;
There is already a `disconnectReason` in this class, this is causing a build failuire. Did you map this via enimga?

2023-06-09 15:47 UTC, apple502j commented on mappings/net/minecraft/network/ClientConnection.mapping
> +	FIELD field_44972 disconnectReason Lnet/minecraft/class_2561;
Oh no. Yep, it was Enigma.

2023-06-09 15:48 UTC, modmuss50 commented on mappings/net/minecraft/network/ClientConnection.mapping
> +	FIELD field_44972 disconnectReason Lnet/minecraft/class_2561;
Intresting, it should not have allowed that. I guess it was caused by this commit: https://github.com/FabricMC/Enigma/commit/b73d303f3aca9610d3bad866518f21cc813a2c87

2023-06-09 16:05 UTC, Shnupbups approved these changes

2023-06-09 16:25 UTC, YanisBft approved these changes

2023-06-10 15:56 UTC, modmuss50 approved these changes

2023-06-10 15:56 UTC, merged