The Great Lambda FixUp
asiekierka/MinecraftPOMF pull request #3593
Opened 2023-06-16 19:38 UTC by MiniDigger

Cleans up 125+ conflicting param names for lambda params

2023-06-17 07:45 UTC, MiniDigger commented
fixed some record related issues in [`ad80c98` (#3593)](https://github.com/FabricMC/yarn/pull/3593/commits/ad80c9847268c9a8b3c3fd7aa172ae48f468fbc4), can move to another PR if needed. other than that am happy now, have a compile clean workspace now 🎉

2023-06-17 07:50 UTC, liach commented
Did the record inference break, or is it some record accessor-interface inheritance issue?

2023-06-19 22:57 UTC, modmuss50 requested changes
I dont mind adding the x suffix to everything, its not ideal but better than the current clashing names. Ideally we would have the tools to prevent this from happening again in the future.

The record component name changes dont make a lot of sense to me, as they should already have auto mapped names. What was the reasoning behind this, its quite possible something isnt working correct elsewhere.

2023-06-19 22:57 UTC, modmuss50 commented on mappings/net/minecraft/server/world/ServerWorld.mapping
> +		ARG 1 pathParam # paper
```suggestion
		ARG 1 pathParam
```

2023-06-19 22:57 UTC, modmuss50 commented on mappings/net/minecraft/server/world/ServerWorld.mapping
> +		ARG 2 entityParam # paper
```suggestion
		ARG 2 entityParam
```

I dont think there is a reason for these comments?

2023-06-19 22:57 UTC, modmuss50 commented on mappings/net/minecraft/server/world/ServerWorld.mapping
> +		ARG 0 innerPos # yarn
```suggestion
		ARG 0 innerPos
```

2023-06-19 22:57 UTC, modmuss50 commented on mappings/net/minecraft/server/world/ServerWorld.mapping
> +		ARG 1 innerPos # yarn
```suggestion
		ARG 1 innerPos
```

2023-06-19 22:57 UTC, modmuss50 commented on mappings/net/minecraft/world/dimension/DimensionType.mapping
> +	FIELD comp_641 fixedTime Ljava/util/OptionalLong;
Why did you need to name these? They should have been automaticaly given these names via https://github.com/FabricMC/name-proposal/

2023-06-19 22:57 UTC, modmuss50 commented on mappings/net/minecraft/registry/entry/RegistryEntry.mapping
> +	METHOD comp_349 value ()Ljava/lang/Object;
I dont see a related record field mapping for this (I would expect this to be in one of the inner casses). Again this is already auto mapped.

2023-06-19 22:57 UTC, modmuss50 commented on mappings/net/minecraft/network/packet/c2s/play/ClientSettingsC2SPacket.mapping
> +	FIELD comp_273 allowsListing Z
As with the other record changes, this should (and is) auto mapped.

2023-06-20 07:49 UTC, MiniDigger commented
the record stuff I can clean up, hopefully today, it was only a symptom of a bug I had elsewhere in my code, I believe I dont need those changes anymore.

will clean the comments too then

2023-06-20 18:22 UTC, MiniDigger commented
that should be all now, stuff still compiles cleanly for me (if you run a jdk that has this stupid bug, that costed me way too much time, fixed... https://bugs.openjdk.org/browse/JDK-8288130), this is read to merge from my point of view

2023-06-20 18:26 UTC, modmuss50 approved these changes
Looks great!

I will allow a little time for anyone (CC: @FabricMC/yarn-triage ) to provide input on specifc lambda names, these renames wont affect modders so im not too worried, we can always improve them later.

👍

2023-06-20 18:54 UTC, MiniDigger commented
due to the amount I just gave up trying to name them, you can see that I tried for some of them but didnt want to spend that much time on...

2023-06-20 20:29 UTC, YanisBft approved these changes
As modmuss said, x suffixes are a good temporary solution, so thank you for your time

2023-06-20 22:11 UTC, merged