23w40a blocks
asiekierka/MinecraftPOMF pull request #3688
Opened 2023-10-07 11:58 UTC by apple502j

2023-10-07 21:13 UTC, Shnupbups requested changes

2023-10-07 21:13 UTC, Shnupbups commented on mappings/net/minecraft/block/ButtonBlock.mapping
> +		ARG 0 bloc
typo

2023-10-08 05:27 UTC, apple502j commented on mappings/net/minecraft/block/ButtonBlock.mapping
> +		ARG 0 bloc
```suggestion
		ARG 0 block
```

2023-10-08 08:00 UTC, YanisBft approved these changes

2023-10-08 08:30 UTC, Shnupbups approved these changes

2023-10-08 08:30 UTC, merged