23w45a Shinanigans
asiekierka/MinecraftPOMF pull request #3722
Opened 2023-11-10 16:34 UTC by zOnlyKroks

First contribution to yarn, just a random assortment of classes that came first under my mouse in enigma.

2023-11-10 17:59 UTC, apple502j requested changes

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +	FIELD field_47473 breezeDebugInfoList Ljava/util/Map;
```suggestion
	FIELD field_47473 breezes Ljava/util/Map;
```

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +	METHOD method_55255 clearMap ()V
```suggestion
	METHOD method_55255 clear ()V
```

Implementation detail should not be used as a name.

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +	METHOD method_55259 renderOutlines (Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;DDD)V
```suggestion
	METHOD method_55259 render (Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;DDD)V
```

Mojang forgot to override `DebugRenderer.Renderer`; if they did, this method would've been named "render".

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +		ARG 7 z
```suggestion
		ARG 1 matrices
		ARG 2 vertexConsumers
		ARG 3 cameraX
		ARG 5 cameraY
		ARG 7 cameraZ
```

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +		ARG 9 entityVec3
```suggestion
		ARG 9 targetPos
```

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +			COMMENT targetVec4
```suggestion
		ARG 9 jumpTarget
```

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +		ARG 9 vec4
```suggestion
	METHOD method_55262 drawLine (Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;DDDLnet/minecraft/class_243;Lnet/minecraft/class_243;I)V
		ARG 0 matrices
		ARG 1 vertexConsumers
		ARG 2 cameraX
		ARG 4 cameraY
		ARG 6 cameraZ
		ARG 8 entityPos
		ARG 9 targetPos
```

It's always a good idea to check other classes for naming conventions. Also, never name something "vec3" or "vec4". Vec4 is a vector of 4 values.

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +		ARG 10 breezeEntity
```suggestion
		ARG 10 breeze
```

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +		ARG 1 breezeId
```suggestion
```

2023-11-10 17:59 UTC, apple502j commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +		ARG 8 entityBox
```suggestion
```
FYI: This is not a box.

2023-11-10 18:14 UTC, Shnupbups commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +			COMMENT jumpTarget
```suggestion
		ARG 9 jumpTarget
```

2023-11-10 18:16 UTC, zOnlyKroks commented on mappings/net/minecraft/client/render/debug/BreezeDebugRenderer.mapping
> +			COMMENT jumpTarget
huh did i not just fix those

2023-11-11 03:55 UTC, apple502j approved these changes

2023-11-11 03:55 UTC, merged