24w04a stuff
asiekierka/MinecraftPOMF pull request #3774
Opened 2024-01-25 13:40 UTC by apple502j

2024-01-25 21:46 UTC, Shnupbups requested changes

2024-01-25 21:46 UTC, Shnupbups commented on mappings/net/minecraft/world/updater/WorldUpdater.mapping
> +	FIELD field_48727 FINISHED_ENTITTIES_TEXT Lnet/minecraft/class_5250;
```suggestion
	FIELD field_48727 FINISHED_ENTITIES_TEXT Lnet/minecraft/class_5250;
```
lol

2024-01-26 04:27 UTC, apple502j commented on mappings/net/minecraft/world/updater/WorldUpdater.mapping
> +	FIELD field_48727 FINISHED_ENTITTIES_TEXT Lnet/minecraft/class_5250;
Whoops 🤣

2024-01-26 07:29 UTC, Shnupbups approved these changes

2024-01-26 07:29 UTC, merged