24w11a stuff
asiekierka/MinecraftPOMF pull request #3818
Opened 2024-03-15 06:01 UTC by apple502j

2024-03-15 06:02 UTC, apple502j commented
wait apparently @Shnupbups has already filed the PR

2024-03-16 13:10 UTC, Shnupbups requested changes

2024-03-16 13:10 UTC, Shnupbups commented on mappings/net/minecraft/data/Main.mapping
> +		ARG 2 outpux
```suggestion
		ARG 2 outputx
```

2024-03-16 14:19 UTC, Shnupbups approved these changes

2024-03-16 14:19 UTC, merged