Add 'Client' suffix to some 'World' methods to indicate that they only work on the client
asiekierka/MinecraftPOMF pull request #4052
Opened 2024-11-17 18:05 UTC by Octol1ttle

- **change: add 'Client' suffix to some 'World' methods to indicate that they only work on the client**
- **change(World#playSound): explain the behavior on client vs. server in more detail**

2024-11-17 18:13 UTC, Syst3ms requested changes

2024-11-17 18:13 UTC, Syst3ms commented on mappings/net/minecraft/world/World.mapping
> +			COMMENT the player that caused this sound, or {@code null}. On the client, the sound will only if if the source is the same as the client's player.
```suggestion
			COMMENT the player that caused this sound, or {@code null}. On the client, the sound will only play if the source is the same as the client's player.
```
repeated across the other instances

2024-11-19 03:44 UTC, Syst3ms approved these changes

2025-01-10 12:00 UTC, Shnupbups approved these changes

2025-01-10 12:00 UTC, merged

2025-01-10 16:24 UTC, apple502j commented
Uhhh, this shouldn't be merged blindly as Mojang did have some rewrites here, but guess I can fix that...