Block entities
asiekierka/MinecraftPOMF pull request #417
Opened 2019-01-21 05:47 UTC by Runemoro

2019-01-21 19:44 UTC, se7kn8 reviewed
Looks good, but maybe there is a better name for `dispenseSimple`?

2019-01-21 20:03 UTC, Runemoro commented
> Looks good, but maybe there is a better name for `dispenseSimple`?

Do you have any suggestions? It's a method that dispenses the item without sound or particles.

2019-01-23 10:38 UTC, asiekierka requested changes
* dispenseSimple -> dispenseStack
* getTopMaterialColor? Is there a non-top material color?
* CoralParentBlock.checkIfInWater -> checkInWater? Maybe? Not sure...
* InfestedBlock.INFESTED_BLOCK_TO_REGULAR_BLOCK -> INFESTED_TO_REGULAR_MAP? INFESTED_REGULAR_MAP?
* Not sure how I feel about Infested/Regular as terminology
* LecternBlock.tryPuttingBook -> tryPutBook
* PoweredRailBlock.isPoweredFromOtherRails -> isPoweredByOtherRails or even isRailPowered depending on what it's used for
* RedstoneWireBlock.getWireConnections -> getWireConnectionMask
* StructureBlock.STRUCTURE_MODE -> MODE, you don't need to prefix it twice IMO in this case
* TrappedChestBlock.getOpenChestStat -> getOpeningStat? getOpenedStat? getOpenStat?
* VineBlock has shouldConnectTo and cannotConnectTo. I think it's fine, but worth pointing out in case anyone has a better idea
* spawnExperienceOrbs -> dropExperience? Unless it *literally* handles the spawning *only*...
* BarrelBlockEntity.isOpen field -> open? opened?
* lastBeamTextureProgressUpdateTime and beamTextureProgress? Can these be shorter?
* A list called "beam"? Not "beams" or anything?
* BeaconBlockEntity.EFFECTS -> ALL_EFFECTS?
* givePlayersEffects -> applyPlayerEffects?
* CommandBlockBlockEntity.updateAndGetConditionMet also seems verbose... just getConditionMet IMO
* CommandBlockBlockEntity -> CommandBlockEntity in general?
* ConduitBlockEntity.getAttackableZone -> getAttackZone? (Remember, most of these have question marks for a reason! You know better than I do - just suggestions!)
* EndGatewayBlockEntity.getRecentlyGeneratedBeamHeight also seems a bit verbose...
* HopperBlockEntity.tryTransfering -> tryTransfer? tryInsert? tryExtract?
* waterImmediatelyVaporizes/etc. in Dimension -> vaporizeWater?

The rest is good (or, rarely, is not worth bringing up and can be fixed later if someone complains). Amazing work - but could you please make *slightly* smaller PRs next time?

2019-01-23 12:45 UTC, Runemoro commented
> getTopMaterialColor? Is there a non-top material color?

Yes, there is. For logs, the return value depends on the axis. Maybe the method should actually be named `getMaaterialColor`/`getMapColor`?

> Not sure how I feel about Infested/Regular as terminology

The block names are "infested cobblestone", "infested stone", etc.

> A list called "beam"? Not "beams" or anything?

A list of beam segments forms the complete beam. Maybe it should be named `beamSegments`?

2019-01-23 13:39 UTC, asiekierka commented
>The block names are "infested cobblestone", "infested stone", etc.

Particularly "Regular". I guess it's the best, as "normal" could get confusing...

>A list of beam segments forms the complete beam. Maybe it should be named beamSegments?

Yes, please.

>Yes, there is. For logs, the return value depends on the axis. Maybe the method should actually be named getMaterialColor/getMapColor?

getMapColor is fine.

2019-01-23 18:39 UTC, Runemoro commented
> CommandBlockBlockEntity.updateAndGetConditionMet also seems verbose... just getConditionMet IMO
The problem is that there's already a `isConditionMet` that returns `conditionMet` without updating it. This method both updates and returns it. Maybe it could be just named updateConditionMet, since it's clear from the return type it returns the updated value?

2019-01-23 18:43 UTC, asiekierka commented
OK

2019-01-24 16:01 UTC, LemmaEOF approved these changes
I think I'm generally ok with these, but I'm not a Yarn Expert™.

2019-01-24 16:01 UTC, Boundarybreaker commented on mappings/net/minecraft/block/ChorusFlowerBlock.mapping
> +	METHOD a isSurroundedByAir (Lbcm;Let;Ley;)Z
maybe `isIsolated` would be better?

2019-01-24 16:08 UTC, merged