Gui Mappings
asiekierka/MinecraftPOMF pull request #430
Opened 2019-01-26 17:24 UTC by shedaniel

This is my first time contributing to yarn, and I've no idea how to use Enigma, so please tell me if anything is wrong.

2019-01-27 20:39 UTC, se7kn8 approved these changes

2019-01-29 18:04 UTC, modmuss50 requested changes

2019-01-29 18:04 UTC, modmuss50 commented on mappings/net/minecraft/client/gui/container/LoomGui.mapping
> +	FIELD GRAY GRAY Lawa;
Do not map out already mapped fields.

2019-01-30 10:56 UTC, asiekierka commented
Pretty sure that's unmergeable at this point, so don't fuss about getting it in early - I'll go through it by hand.

2019-01-30 11:47 UTC, shedaniel commented on mappings/net/minecraft/client/gui/container/LoomGui.mapping
> +	FIELD GRAY GRAY Lawa;
Alright, it is a mistake, Sorry!

2019-02-10 08:26 UTC, shedaniel commented
Will probably create another PR with a new snapshot

2019-02-10 08:26 UTC, closed without merging