(Nearly) complete MainMenuScreen and Container mappings
asiekierka/MinecraftPOMF pull request #513
Opened 2019-03-02 21:11 UTC by HoLLy-HaCKeR

Completes most of MainMenuScreen and ContainerScreen, adds CubeMapRenderer and RotatingCubeMapRenderer (panorama background) and adds some minor missing mappings for arguments.

I don't usually program in Java, so please do tell me if I screwed up some naming schemes.

2019-03-04 15:44 UTC, asiekierka requested changes
Too verbose, in general!

2019-03-04 15:44 UTC, asiekierka commented on mappings/net/minecraft/client/gui/ContainerScreen.mapping
> +	FIELD B touchDropPositionX I
Why not just touchDropX/touchDropY? There is such a thing as "too verbose".

2019-03-04 15:44 UTC, asiekierka commented on mappings/net/minecraft/client/gui/RotatingCubeMapRenderer.mapping
> +	FIELD a minecraftClient Lcqx;
client

2019-03-04 18:12 UTC, HoLLy-HaCKeR commented
I'd rather have the user instantly understand what they're reading than have them guess but read a few characters less, though I agree with you on the ones you mentioned. Fixed those.

2019-03-05 12:23 UTC, Gegy approved these changes

2019-03-05 13:54 UTC, asiekierka approved these changes

2019-03-05 13:54 UTC, merged