Add *.sh to .gitignore
asiekierka/MinecraftPOMF pull request #671
Opened 2019-05-05 22:01 UTC by InsomniaKitten

I use scripts to load Enigma and setup commits etc. Would be nice if Yarn itself ignored script files in Git.

2019-05-05 22:02 UTC, modmuss50 commented
Moving to a git include might not be a bad idea, I think we use it on all if not most of the other projects.

2019-05-05 22:07 UTC, InsomniaKitten commented
Sounds good to me.

2019-05-05 23:13 UTC, modmuss50 requested changes
this can be changed to a git include, either via this PR or I can do it later.

2019-05-06 00:04 UTC, closed without merging

2019-05-06 00:05 UTC, InsomniaKitten commented
I can make a new PR for it tomorrow