Add missing mappings in tick scheduler
asiekierka/MinecraftPOMF pull request #743
Opened 2019-06-08 20:06 UTC by kvverti

Mainly `TickScheduler#scheduleAll`, which in every implementation either forwards to `schedule` or copies its implementation. Also named some private methods in `ServerTickScheduler`.

2019-06-08 21:23 UTC, asiekierka approved these changes

2019-06-09 21:22 UTC, liach commented
some names previously in this class actually violate our guidelines (ticksCurrent should be currentTicks, etc.)

2019-06-15 06:45 UTC, Boundarybreaker commented
Are we moving to the standard of `toNbt` instead of `toTag`?

2019-06-18 12:32 UTC, modmuss50 approved these changes

2019-06-18 13:25 UTC, liach approved these changes

2019-06-18 21:26 UTC, ChloeDawn requested changes

2019-06-18 21:26 UTC, InsomniaKitten commented on mappings/net/minecraft/server/world/ServerTickScheduler.mapping
> +	FIELD c nameToId Ljava/util/function/Function;
`serializer`. There is no "name", it is T->Identifier used for serialization.

2019-06-18 21:26 UTC, InsomniaKitten commented on mappings/net/minecraft/server/world/ServerTickScheduler.mapping
>  	FIELD b idToName Ljava/util/function/Function;
`deserializer`. There is no "name", it is Identifier->T used for deserialization.

2019-06-18 21:26 UTC, InsomniaKitten commented on mappings/net/minecraft/world/ScheduledTick.mapping
> +	METHOD a getComparator ()Ljava/util/Comparator;
`comparing` (called as `ScheduledTick.comparing()`). Used in a similar fashion to utilities such as `Comparator.comparing(keyExtractor, keyComparator)`.

2019-06-19 17:33 UTC, modmuss50 commented
Merging due to update, any future comments can go into an issue or a followup PR.

2019-06-19 17:33 UTC, merged