EntitySize -> EntityDimensions
asiekierka/MinecraftPOMF pull request #745
Opened 2019-06-08 22:16 UTC by Sollace

Changes for the issue at https://github.com/FabricMC/yarn/issues/715

2019-06-08 23:11 UTC, Prospector approved these changes

2019-06-09 00:29 UTC, liach commented
please change all getter methods to getDimensions instead of getSize; same for fields/method params

2019-06-09 00:29 UTC, liach commented
also consider renaming constant to fixed

2019-06-09 01:26 UTC, ChloeDawn requested changes

2019-06-09 01:26 UTC, InsomniaKitten commented on mappings/net/minecraft/entity/EntityDimensions.mapping
>  	METHOD c constant (FF)Laim;
`fixed`

2019-06-09 01:29 UTC, InsomniaKitten commented
The parameter names for the static constructors are incorrect. They should be `width` and `height` not `x` and `z`.

2019-06-09 01:30 UTC, InsomniaKitten commented on mappings/net/minecraft/entity/EntityDimensions.mapping
>  	FIELD c constant Z
`fixed`

2019-06-09 01:30 UTC, InsomniaKitten commented on mappings/net/minecraft/entity/EntityDimensions.mapping
>  	METHOD c constant (FF)Laim;
Constructor parameter and field also need to be changed to `fixed`

2019-06-09 01:41 UTC, InsomniaKitten commented
**`field`**`EnderDragonPart#partSize` -> `EnderDragonPart#dimensions`
**`field`**`Entity#size` -> `Entity#dimensions`
**`field`**`EntityType#size` -> `EntityType#dimensions`
**`field`**`EntityType$Builder#size` -> `EntityType$Builder#dimensions`
**`field`**`LivingEntity.SLEEPING_SIZE` -> `LivingEntity.SLEEPING_DIMENSIONS`
**`field`**`PlayerEntity.SIZES` -> `PlayerEntity.POSE_DIMENSIONS`
**`field`**`PlayerEntity.STANDING_SIZE` -> `PlayerEntity.STANDING_DIMENSIONS`
**`method`**`Entity#getSize(EntityPose)` -> `Entity#getDimensions(EntityPose)`
**`method`**`EntityType#getDefaultSize` -> `EntityType#getDefaultDimensions`
**`param`**`Entity#getEyeHeight@size` -> `Entity#getEyeHeight@dimensions`
**`param`**`EntityType.<init>@size` -> ``EntityType.<init>@dimensions`
**`param`**`LivingEntity#getActiveEyeHeight@size` -> `LivingEntity#getActiveEyeHeight@dimensions`

2019-06-09 01:43 UTC, InsomniaKitten commented
Migration required for Fabric's `EntityTypeBuilder`:
**`field`**`size` -> `dimensions`
**`method`**`size` -> `dimensions`
**`param`**`size@size` -> `dimensions`

2019-06-09 01:49 UTC, kashike commented
I'm not a fan of this name change - it will cause confusion with world dimensions.

2019-06-09 01:52 UTC, InsomniaKitten commented
I agree, but either way, I do not want a partial migration. All or nothing. Personally, I would call this data class `EntityShape` as it implies the width and height, and separates it away from the concept of dimensions that the game already has.

2019-06-09 02:59 UTC, liach commented
i originally opposed this change, but i find that it will be clear if we call this one dimensions (with the s suffix) instead of dimension.

2019-06-09 07:38 UTC, Sollace commented
@liach @kashike Again, I remind everyone that it is `Dimensions` _with an S_.

@liach I did consider doing name changes for all the getters as well, however I don't believe it's neccessary to have it use the same terminology as the class name. It's clear enough to see that `getSize()` returns a some form of Dimensions. It also avoids confusion with a method like `getDimension()`.

2019-06-09 07:40 UTC, Sollace commented
@liach I thought people specifically didn't want that changed to fixed? (which is why it was left out of the PR)

2019-06-09 08:13 UTC, kashike commented
@Sollace I am well aware it has an `s`, my statement is not changing.

2019-06-09 08:27 UTC, Sollace commented
I was also thinking about world dimensions, and what's stopping us from calling them `Level`s or `LevelTye`s? Minecraft has used that term in the past when referring to the overworld, so I don't see why they wouldn't still have it internally.

2019-06-09 21:21 UTC, liach commented
how about EntityExtent?

2019-06-11 08:29 UTC, liach commented
`EntityMeasure` would be clear and non-confusing.

See defintion 4 at https://www.dictionary.com/browse/measures (noun section)
>the extent, dimensions, quantity, etc., of something, ascertained especially by comparison with a standard: 
>to take the measure of a thing.

This covers "dimensions" "extent" in a sense while it won't be confusing as "extent" or "dimension" (both has been used in spongeapi to refer to world stuff)

@kashike @InsomniaKitten @Prospector wanna hear your opinions.

2019-06-11 08:49 UTC, copygirl commented
> I was also thinking about world dimensions, and what's stopping us from calling them `Level`s or `LevelType`s?

The term is already standard in the entire community.
Very early on we had a discussion on this. It didn't really lead anywhere, but see #89.

----

That said, I'm split on the change.
**Pro:** `toString` clearly mentioning the actual name of the class.
**Con:** It kind of clashes with `Dimension`, for auto-complete suggestions and such.

I also don't necessarily see `Size` as a scalar value. It is often used in a 2D context to describe an element's width and height. And I don't think we should introduce another name that is different from Mojang's name.

2019-06-11 09:45 UTC, Sollace commented
> EntityMeasure would be clear and non-confusing.
@liach Even though you didn't ask for it, I don't know if I like using `EntityMeasure`. What is it a measure of? Volume? Age? Does it specify width/height in meters, or centimeters?

Measure to is something of standard, fixed, size or dimensions that you use to _measure_ something. Like how a meter stick is a measure of length.

2019-06-11 10:10 UTC, liach commented
this way, dimensions is a plain scalar as well. i'd say stay with size; we should not be trolled by mojang for such a tostring statement after all.

2019-06-11 10:16 UTC, NeunEinser commented
> this way, dimensions is a plain scalar as well.

Not sure what you are referring to. You can measure in m², too, which to my understanding is the case, when you measure dimensions.

I think Wikitonary's definition pretty much nails it and describes perfectly what this class is. (definition of a **single** dimension, not the plural form)
>A measure of spatial extent in a particular direction, such as height, width or breadth, or depth.

2019-06-11 12:00 UTC, Runemoro approved these changes

2019-06-11 12:07 UTC, Runemoro commented
To me a size is the overall size of something. I wouldn't expect a class named `EntitySize` to give both a width and height.

@kashike Currently Entity.getSize (which returns its dimensions, not size!) conflicts with SlimeEntity.getSlimeSize (which correctly returns a single integer size!).

2019-06-14 09:42 UTC, asiekierka commented
I say EntityDimensions.

2019-06-15 06:46 UTC, LemmaEOF approved these changes

2019-06-15 08:29 UTC, NeunEinser approved these changes

2019-06-15 09:53 UTC, Gegy approved these changes

2019-06-18 12:05 UTC, modmuss50 approved these changes

2019-06-18 12:05 UTC, merged