[WIP] Scrollable entry lists + LAN server querying
asiekierka/MinecraftPOMF pull request #80
Opened 2016-09-15 06:47 UTC by iamgreaser

The latter lead to the former. The former is more important, but it would be a waste of time to revert everything I did on the latter. So yeah, you get two things for the price of one.

Currently need names for these things:

* `bfb`: Abstract base class for all vertically-scrollable lists w/ entries of uniform height.
* `bew` extends `bfb`: Less abstract base class for lists where each entry can have its own draw and mouse functions.
  * `bew.a`: Interface for each entry in `bew`.
* `bid` extends `bew.a`: The `o o O` spoopy entry which tells you that it's scanning for LAN servers.
* `bie` extends `bew.a`: Visible entry for a LAN server.
* `bif` extends `bew.a`: Visible entry for a regular serverlist server.
* `big` extends `bew`: The server selection scrollbox itself.

2016-09-15 07:14 UTC, asiekierka commented
* bfb: Abstract base class for all vertically-scrollable lists w/ entries of uniform height.

net.minecraft.client.gui.widget.WidgetListBase (or WidgetListAbstract?)

* bew extends bfb: Less abstract base class for lists where each entry can have its own draw and mouse functions.

net.minecraft.client.gui.widget.WidgetList

* bew.a: Interface for each entry in bew.

net.minecraft.client.gui.widget.WidgetList.Entry

* bid extends bew.a: The o o O spoopy entry which tells you that it's scanning for LAN servers.

net.minecraft.client.gui.menu.ListEntryLocalScanProgress

* bie extends bew.a: Visible entry for a LAN server.

net.minecraft.client.gui.menu.ListEntryLocalServer

* bif extends bew.a: Visible entry for a regular serverlist server.

net.minecraft.client.gui.menu.ListEntryRemoteServer

* big extends bew: The server selection scrollbox itself.

net.minecraft.client.gui.menu.WidgetServerList

2016-09-15 07:26 UTC, iamgreaser commented
Only real problem with going with WidgetList is that it's incompatible with the other things that call themselves Widget*. If we *do* take this approach, I'd put it in `net.minecraft.client.gui.scroll` or something like that.

`bew` is also an abstract class, and there are also classes which depend on `bfb` but not `bew`.

2016-09-15 07:27 UTC, asiekierka commented
@iamgreaser Yes, but the Base one is more abstract. All you need to implement in bew is the entry getter, which is fair.

As for the Widget thing, it might not be, but it has roughly the same methods involved and I can't think of a better way to call it. Perhaps @copygirl?

2016-09-15 09:21 UTC, copygirl commented
These classes are only used in the menu, right? What about `MenuWidget`? It's also worth considering renaming our current `Widget` classes to something else.

2016-09-15 18:31 UTC, shadowfacts commented on mappings/net/minecraft/client/gui/menu/WidgetListBase.mapping
> +	METHOD b entryCount ()I
`entryCount` or `getEntryCount`?

2016-09-15 18:32 UTC, shadowfacts commented on mappings/net/minecraft/client/gui/menu/WidgetListBase.mapping
> +	METHOD c entryWidth ()I
`entryWidth` or `getEntryWidth`?

2016-09-15 18:32 UTC, shadowfacts commented on mappings/net/minecraft/client/gui/menu/WidgetListBase.mapping
> +	METHOD k contentHeight ()I
`contentHeight` or `getContentHeight`?

2016-09-15 18:33 UTC, shadowfacts commented on mappings/net/minecraft/server/LanServerPinger.mapping
> +	METHOD a makeAnnouncement (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
`make` or `create`?

2016-09-15 18:36 UTC, shadowfacts commented on mappings/net/minecraft/client/gui/menu/ListEntryRemoteServer.mapping
> +	FIELD b SERVER_PINGER Ljava/util/concurrent/ThreadPoolExecutor;
`PING_THREAD_POOL` or `PING_POOL` or something to indicate it's a thread pool?

2016-09-15 18:37 UTC, shadowfacts requested changes

2016-09-15 18:57 UTC, copygirl commented on mappings/net/minecraft/client/gui/menu/WidgetListBase.mapping
> +	METHOD b entryCount ()I
`get` for sure.

2016-09-15 22:34 UTC, iamgreaser commented on mappings/net/minecraft/server/LanServerPinger.mapping
> +	METHOD a makeAnnouncement (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Or `construct` perhaps?

2016-09-15 23:09 UTC, shadowfacts approved these changes

2016-09-16 23:02 UTC, merged

2016-09-16 23:03 UTC, copygirl commented
Haha, my first merge! :tada: