more mappings for SpawnHelper and ocean monument
asiekierka/MinecraftPOMF pull request #829
Opened 2019-08-23 05:54 UTC by valoeghese

2019-08-23 07:59 UTC, Runemoro approved these changes

2019-08-24 09:52 UTC, valoeghese commented
review pls

2019-08-25 03:18 UTC, liach commented on mappings/net/minecraft/structure/OceanMonumentGenerator.mapping
> +		METHOD method_14773 (Lnet/minecraft/class_1936;Lnet/minecraft/class_3341;IIIIII)V
What's the method's name

2019-08-25 03:37 UTC, valoeghese commented on mappings/net/minecraft/structure/OceanMonumentGenerator.mapping
> +		METHOD method_14773 (Lnet/minecraft/class_1936;Lnet/minecraft/class_3341;IIIIII)V
setAirAndWater

2019-08-25 03:43 UTC, liach approved these changes

2019-08-25 15:15 UTC, merged

2019-08-25 17:23 UTC, Runemoro requested changes
Ignore this, wrong PR.