[WIP] Particle system
asiekierka/MinecraftPOMF pull request #91
Opened 2016-09-23 06:43 UTC by iamgreaser

Will still need a lot of work. Mostly trying to suss out where everything is supposed to even go.

2016-09-23 09:50 UTC, copygirl commented on mappings/net/minecraft/client/particle/Particle.mapping
> +	FIELD E sprite Lnone/bxe;
We haven't used sprite before, why start now?

2016-09-23 09:50 UTC, copygirl commented on mappings/net/minecraft/client/particle/ParticleManager.mapping
> +	FIELD f random Ljava/util/Random;
`rand` (This isn't static? Odd.)

2016-09-23 09:53 UTC, copygirl commented on mappings/net/minecraft/client/particle/ParticleManager.mapping
> +	METHOD a tickParticleQueue (Ljava/util/Queue;)V
`update`?

2016-09-23 09:53 UTC, copygirl commented on mappings/net/minecraft/client/particle/ParticleManager.mapping
> +	METHOD b tickParticle (Lnone/bnl;)V
`update`?

2016-09-23 09:55 UTC, copygirl commented on mappings/net/minecraft/client/particle/Particle.mapping
> +	METHOD a tick ()V
`update`? We should keep things consistent and I believe we've been using `update` for everything.

2016-09-23 09:57 UTC, copygirl requested changes

2016-09-23 10:11 UTC, iamgreaser commented on mappings/net/minecraft/client/particle/Particle.mapping
> +	METHOD a tick ()V
`tick` is used in other places.

2016-09-23 10:11 UTC, iamgreaser commented on mappings/net/minecraft/client/particle/Particle.mapping
> +	FIELD E sprite Lnone/bxe;
There's a class called `Sprite`, what are these instances *usually* called?

2016-09-23 10:16 UTC, iamgreaser commented on mappings/net/minecraft/client/particle/Particle.mapping
> +	METHOD a tick ()V
Also, `tick` is also less vague. If you insist though I can move it back to update.

2016-09-23 10:17 UTC, iamgreaser commented on mappings/net/minecraft/client/particle/ParticleManager.mapping
> +	METHOD a tickParticleQueue (Ljava/util/Queue;)V
Comment as per `tick`->`update` but I will NOT overload these into all being called `update`.

2016-09-23 10:20 UTC, unascribed commented on mappings/net/minecraft/client/particle/ParticleManager.mapping
> +	METHOD a tickParticleQueue (Ljava/util/Queue;)V
I think they mean `updateParticleQueue`, not just `update`.

2016-09-23 11:47 UTC, unascribed commented on mappings/net/minecraft/client/particle/Particle.mapping
> +	FIELD E sprite Lnone/bxe;
none/bxe *is* `Sprite`, so this seems fine to me.

2016-09-23 11:50 UTC, copygirl commented on mappings/net/minecraft/client/particle/Particle.mapping
> +	METHOD a tick ()V
I agree. Then we should update all other mentions of update, too.

2016-09-23 22:50 UTC, iamgreaser commented
OK, how should all the different particles be named?

Should we go e.g. `ParticleFire` or `FireParticle`? The former is hell from a tab-completion perspective, and they're all going to be in `net.minecraft.client.particle.*` anyway.

2016-09-23 22:56 UTC, darkevilmac commented
> OK, how should all the different particles be named?
> 
> Should we go e.g. ParticleFire or FireParticle? The former is hell from a tab-completion perspective, and they're all going to be in net.minecraft.client.particle.* anyway.

ParticleFire matches better to the current naming of other things.

2016-09-23 22:57 UTC, iamgreaser commented
I guess from that perspective you won't be using the classes directly, so I guess `ParticleFire` could still work fine.

2016-09-24 01:43 UTC, copygirl approved these changes

2016-09-24 07:31 UTC, exaskye approved these changes

2016-09-25 03:52 UTC, iamgreaser commented
Would you rather I dropped the WIP tag and had this pulled now, or would you rather I get names for the particle classes first?

2016-09-25 10:51 UTC, copygirl commented
This PR looks good to me so I can merge it and have another one for the particle class names.

2016-09-26 02:03 UTC, iamgreaser commented
@copygirl Go for it.

2016-09-26 03:28 UTC, merged