New vector and direction methods used in ModelPart
asiekierka/MinecraftPOMF pull request #961
Opened 2019-11-15 17:50 UTC by Sollace

# Vector3f
`getRotationQuaternion` -> `getDegreesQuarernion`
`method_23626` -> `getRadialQuarternion`
These create a quarternions for degree an radian angles respectively.
    
`method_23691` -> `crossMultiplyRow`
does the single component multiplication seen when multiplying a vector by a matrix

`method_23850` -> `copy`
Returns a new copy of `this` vector. I could have called it `clone` but I didn't want to potentially conflict with `Object.clone`.

# Direction

`method_23955` -> `getUnitVector`
It returns the unit vector for the direction.

2019-11-15 17:53 UTC, Juuxel requested changes
I don't know a lot about quaternions, but I think those are typos.

2019-11-15 17:53 UTC, Juuxel commented on mappings/net/minecraft/client/util/math/Vector3f.mapping
> +	METHOD method_23626 getRadialQuarternion (F)Lnet/minecraft/class_1158;
`...Quaternion`?

2019-11-15 17:53 UTC, Juuxel commented on mappings/net/minecraft/client/util/math/Vector3f.mapping
> +	METHOD method_23214 getDegreesQuarernion (F)Lnet/minecraft/class_1158;
`...Quaternion`?

2019-11-15 17:56 UTC, Sollace commented
> 
> 
> I don't know a lot about quaternions, but I think those are typos.

Those were typos. You commented before I could get the fix in.

2019-11-15 17:57 UTC, Juuxel approved these changes

2019-11-15 17:59 UTC, YanisBft approved these changes

2019-11-18 11:36 UTC, modmuss50 approved these changes

2019-11-18 11:36 UTC, merged